### ISSUE TITLE
Bugs: @raw2sqlalchemy

### ISSUE THREAD

**Issue by spirillen** [funilrys/PyFunceble#104]
First of, all these are from Ubuntu 20 running with miniconda from @PyFunceble https://github.com/PyFunceble-Templates/pyfunceble-miniconda with manual copy pasting to shell with modifications to @raw2sqlalchemy commit 5c05383:

= Setup

```shell
:~$ pythonVersion="3.8.5"
:~$ condaInstallDir="${HOME}/miniconda"
:~$ pyfunceblePackageName="pyfunceble-raw2sqlalchemy"
:~$ source "${condaInstallDir}/etc/profile.d/conda.sh"
:~$ hash conda
:~$ conda update -q conda
:~$ conda create -y -q -n "${pyfunceblePackageName}" python="${pythonVersion}"
:~$ conda activate "${pyfunceblePackageName}"
:~$ python -VVV

= Python 3.8.5 (default, Aug  5 2020, 08:36:46) 
= [GCC 7.3.0]

:~$ pip --version
= pip 20.2.2 from $HOME/miniconda/envs/pyfunceble-raw2sqlalchemy/lib/python3.8/site-packages/pip (python 3.8)
:~$ pyfunceble --version
= pyfunceble: command not found

:~$ pip install --no-cache-dir --upgrade git+https://github.com/funilrys/PyFunceble.git@raw2sqlalchemy
```

To the first test `pyfunceble --version` (Expected behavior)
```shell
A configuration key is missing or a new version is available.
Try to merge upstream configuration file into '$HOME/.config/PyFunceble/.PyFunceble.yaml'? [y/n] y
pyfunceble 3.2.11.pre-dev (Teal Blauwbok: Bombardier)
```

Now, if we run `pyfunceble --version` again, we get the same reply, missing value
Let's see if the yaml seems to have been upgrade

`4.9K Aug 23 11:20 $HOME/.config/PyFunceble/.PyFunceble.yaml`

That's is absolutely now (time of writing) 

```shell
date
Sun 23 Aug 11:30:15 CEST 2020
```
`4.9K Aug 23 11:30 $HOME/.config/PyFunceble/.PyFunceble.yaml`

```shell
conda env list
# conda environments:
#
base                  *  $HOME/miniconda
pyfunceble               $HOME/miniconda/envs/pyfunceble
pyfunceble-dev           $HOME/miniconda/envs/pyfunceble-dev
pyfunceble-raw2sqlalchemy     $HOME/miniconda/envs/pyfunceble-raw2sqlalchemy

```

== Test enviroment
```bash
:~$ condaInstallDir="${HOME}/miniconda"
:~$ pyfunceblePackageName="pyfunceble-raw2sqlalchemy"
:~$ source "${condaInstallDir}/etc/profile.d/conda.sh"
:~$ 
:~$ hash conda
:~$ export PYFUNCEBLE_AUTO_CONFIGURATION=yes
:~$ export PYFUNCEBLE_OUTPUT_LOCATION="/tmp/raw2sqlalchemy"
:~$ cp "$HOME/.config/PyFunceble/.pyfunceble-env" "${condaInstallDir}/envs/${pyfunceblePackageName}/"
:~$ export PYFUNCEBLE_CONFIG_DIR="${condaInstallDir}/envs/${pyfunceblePackageName}/"
```

== 1. test
```bash
pyfunceble --version
pyfunceble 3.2.11.pre-dev (Teal Blauwbok: Bombardier)
```

== 2. test
```bash
pyfunceble -f 'https://raw.githubusercontent.com/PyFunceble/ci_test/master/test.list' --dns ns1.dns.mypdns.org ns2.dns.mypdns.org -h -a --idna --mining -vsc -m -p $(nproc --ignore=2) -ex --hierarchical -db --database-type mariadb -dbr 0
```

<details><summary>Test result (failure)</summary>

```shell
Your version is more recent!
You should really think about sharing your changes with the community!
Your version: 3.2.11.pre-dev (Teal Blauwbok: Bombardier)
Upstream version: 3.2.10.dev (Teal Blauwbok: Bombardier)

Traceback (most recent call last):
  File "${condaInstallDir}/envs/${pyfunceblePackageName}/lib/python3.8/site-packages/alembic/script/base.py", line 162, in _catch_revision_errors
    yield
  File "${condaInstallDir}/envs/${pyfunceblePackageName}/lib/python3.8/site-packages/alembic/script/base.py", line 364, in _upgrade_revs
    revs = list(revs)
  File "${condaInstallDir}/envs/${pyfunceblePackageName}/lib/python3.8/site-packages/alembic/script/revision.py", line 765, in _iterate_revisions
    requested_lowers = self.get_revisions(lower)
  File "${condaInstallDir}/envs/${pyfunceblePackageName}/lib/python3.8/site-packages/alembic/script/revision.py", line 319, in get_revisions
    return sum([self.get_revisions(id_elem) for id_elem in id_], ())
  File "${condaInstallDir}/envs/${pyfunceblePackageName}/lib/python3.8/site-packages/alembic/script/revision.py", line 319, in <listcomp>
    return sum([self.get_revisions(id_elem) for id_elem in id_], ())
  File "${condaInstallDir}/envs/${pyfunceblePackageName}/lib/python3.8/site-packages/alembic/script/revision.py", line 322, in get_revisions
    return tuple(
  File "${condaInstallDir}/envs/${pyfunceblePackageName}/lib/python3.8/site-packages/alembic/script/revision.py", line 323, in <genexpr>
    self._revision_for_ident(rev_id, branch_label)
  File "${condaInstallDir}/envs/${pyfunceblePackageName}/lib/python3.8/site-packages/alembic/script/revision.py", line 386, in _revision_for_ident
    raise ResolutionError(
alembic.script.revision.ResolutionError: No such revision or branch 'd8893cd406db'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "${condaInstallDir}/envs/${pyfunceblePackageName}/bin/pyfunceble", line 8, in <module>
    sys.exit(tool())
  File "${condaInstallDir}/envs/${pyfunceblePackageName}/lib/python3.8/site-packages/PyFunceble/cli/__init__.py", line 1188, in tool
    raise exception
  File "${condaInstallDir}/envs/${pyfunceblePackageName}/lib/python3.8/site-packages/PyFunceble/cli/__init__.py", line 1173, in tool
    Dispatcher(
  File "${condaInstallDir}/envs/${pyfunceblePackageName}/lib/python3.8/site-packages/PyFunceble/cli/dispatcher.py", line 117, in __init__
    self.preset.init_all()
  File "${condaInstallDir}/envs/${pyfunceblePackageName}/lib/python3.8/site-packages/PyFunceble/config/preset.py", line 104, in init_all
    self.upgrade_database()
  File "${condaInstallDir}/envs/${pyfunceblePackageName}/lib/python3.8/site-packages/PyFunceble/config/preset.py", line 480, in upgrade_database
    Alembic(credential.Credential(), db_session).upgrade()
  File "${condaInstallDir}/envs/${pyfunceblePackageName}/lib/python3.8/site-packages/PyFunceble/engine/database/migrations/alembic.py", line 113, in upgrade
    command.upgrade(self.alembic_config, revision)
  File "${condaInstallDir}/envs/${pyfunceblePackageName}/lib/python3.8/site-packages/alembic/command.py", line 298, in upgrade
    script.run_env()
  File "${condaInstallDir}/envs/${pyfunceblePackageName}/lib/python3.8/site-packages/alembic/script/base.py", line 489, in run_env
    util.load_python_file(self.dir, "env.py")
  File "${condaInstallDir}/envs/${pyfunceblePackageName}/lib/python3.8/site-packages/alembic/util/pyfiles.py", line 98, in load_python_file
    module = load_module_py(module_id, path)
  File "${condaInstallDir}/envs/${pyfunceblePackageName}/lib/python3.8/site-packages/alembic/util/compat.py", line 184, in load_module_py
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "${condaInstallDir}/envs/${pyfunceblePackageName}/lib/python3.8/site-packages/PyFunceble/data/alembic/env.py", line 114, in <module>
    run_migrations_online()
  File "${condaInstallDir}/envs/${pyfunceblePackageName}/lib/python3.8/site-packages/PyFunceble/data/alembic/env.py", line 108, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "${condaInstallDir}/envs/${pyfunceblePackageName}/lib/python3.8/site-packages/alembic/runtime/environment.py", line 846, in run_migrations
    self.get_context().run_migrations(**kw)
  File "${condaInstallDir}/envs/${pyfunceblePackageName}/lib/python3.8/site-packages/alembic/runtime/migration.py", line 509, in run_migrations
    for step in self._migrations_fn(heads, self):
  File "${condaInstallDir}/envs/${pyfunceblePackageName}/lib/python3.8/site-packages/alembic/command.py", line 287, in upgrade
    return script._upgrade_revs(revision, rev)
  File "${condaInstallDir}/envs/${pyfunceblePackageName}/lib/python3.8/site-packages/alembic/script/base.py", line 365, in _upgrade_revs
    return [
  File "${condaInstallDir}/envs/${pyfunceblePackageName}/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "${condaInstallDir}/envs/${pyfunceblePackageName}/lib/python3.8/site-packages/alembic/script/base.py", line 194, in _catch_revision_errors
    compat.raise_from_cause(util.CommandError(resolution))
  File "${condaInstallDir}/envs/${pyfunceblePackageName}/lib/python3.8/site-packages/alembic/util/compat.py", line 308, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=exc_value)
  File "${condaInstallDir}/envs/${pyfunceblePackageName}/lib/python3.8/site-packages/alembic/util/compat.py", line 301, in reraise
    raise value.with_traceback(tb)
  File "${condaInstallDir}/envs/${pyfunceblePackageName}/lib/python3.8/site-packages/alembic/script/base.py", line 162, in _catch_revision_errors
    yield
  File "${condaInstallDir}/envs/${pyfunceblePackageName}/lib/python3.8/site-packages/alembic/script/base.py", line 364, in _upgrade_revs
    revs = list(revs)
  File "${condaInstallDir}/envs/${pyfunceblePackageName}/lib/python3.8/site-packages/alembic/script/revision.py", line 765, in _iterate_revisions
    requested_lowers = self.get_revisions(lower)
  File "${condaInstallDir}/envs/${pyfunceblePackageName}/lib/python3.8/site-packages/alembic/script/revision.py", line 319, in get_revisions
    return sum([self.get_revisions(id_elem) for id_elem in id_], ())
  File "${condaInstallDir}/envs/${pyfunceblePackageName}/lib/python3.8/site-packages/alembic/script/revision.py", line 319, in <listcomp>
    return sum([self.get_revisions(id_elem) for id_elem in id_], ())
  File "${condaInstallDir}/envs/${pyfunceblePackageName}/lib/python3.8/site-packages/alembic/script/revision.py", line 322, in get_revisions
    return tuple(
  File "${condaInstallDir}/envs/${pyfunceblePackageName}/lib/python3.8/site-packages/alembic/script/revision.py", line 323, in <genexpr>
    self._revision_for_ident(rev_id, branch_label)
  File "${condaInstallDir}/envs/${pyfunceblePackageName}/lib/python3.8/site-packages/alembic/script/revision.py", line 386, in _revision_for_ident
    raise ResolutionError(
alembic.util.exc.CommandError: Can't locate revision identified by 'd8893cd406db'
```

</details>

**Comment by funilrys** [comment]
@spirillen That's a normal behavior. As soon as we are going to be in the `dev` branch it should be gone. 

Let's rediscuss about it if it's still like that once deployed in the `dev` version.
