### ISSUE TITLE
Bugs: @raw2sqlalchemy (Debian 10 on fdeb5a8)

### ISSUE THREAD

**Issue by spirillen** [funilrys/PyFunceble#105]
Same setup as #104 This one running fdeb5a8 on Debian 10 (HP ml350 g6 (8Cores))

<details><sumary>Error output</summary>

```bash
Your version is more recent!
You should really think about sharing your changes with the community!
Your version: 3.2.11.pre-dev (Teal Blauwbok: Bombardier)
Upstream version: 3.2.10.dev (Teal Blauwbok: Bombardier)

Starting switch to SQLAlchemy ...
Exception in thread Thread-11501:
Traceback (most recent call last):
  File "$HOME/miniconda/envs/pyfunceble-raw2sqlalchemy/lib/python3.8/site-packages/pymysql/connections.py", line 569, in connect
    sock = socket.create_connection(
  File "$HOME/miniconda/envs/pyfunceble-raw2sqlalchemy/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "$HOME/miniconda/envs/pyfunceble-raw2sqlalchemy/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "$HOME/miniconda/envs/pyfunceble-raw2sqlalchemy/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "$HOME/miniconda/envs/pyfunceble-raw2sqlalchemy/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "$HOME/miniconda/envs/pyfunceble-raw2sqlalchemy/lib/python3.8/site-packages/PyFunceble/engine/database/migrations/old2new.py", line 265, in __tested_migration
    old_connection = self.get_old_connection()
  File "$HOME/miniconda/envs/pyfunceble-raw2sqlalchemy/lib/python3.8/site-packages/PyFunceble/engine/database/migrations/old2new.py", line 132, in get_old_connection
    return pymysql.connect(
  File "$HOME/miniconda/envs/pyfunceble-raw2sqlalchemy/lib/python3.8/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "$HOME/miniconda/envs/pyfunceble-raw2sqlalchemy/lib/python3.8/site-packages/pymysql/connections.py", line 327, in __init__
    self.connect()
  File "$HOME/miniconda/envs/pyfunceble-raw2sqlalchemy/lib/python3.8/site-packages/pymysql/connections.py", line 619, in connect
    raise exc
pymysql.err.OperationalError: (2003, "Can't connect to MySQL server on 'ip' (timed out)")
Exception in thread Thread-11506:
Traceback (most recent call last):
  File "$HOME/miniconda/envs/pyfunceble-raw2sqlalchemy/lib/python3.8/site-packages/pymysql/connections.py", line 569, in connect
    sock = socket.create_connection(
  File "$HOME/miniconda/envs/pyfunceble-raw2sqlalchemy/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "$HOME/miniconda/envs/pyfunceble-raw2sqlalchemy/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "$HOME/miniconda/envs/pyfunceble-raw2sqlalchemy/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2338, in _wrap_pool_connect
    return fn()
  File "$HOME/miniconda/envs/pyfunceble-raw2sqlalchemy/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 364, in connect
    return _ConnectionFairy._checkout(self)
  File "$HOME/miniconda/envs/pyfunceble-raw2sqlalchemy/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 778, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "$HOME/miniconda/envs/pyfunceble-raw2sqlalchemy/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 495, in checkout
    rec = pool._do_get()
  File "$HOME/miniconda/envs/pyfunceble-raw2sqlalchemy/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 140, in _do_get
    self._dec_overflow()
  File "$HOME/miniconda/envs/pyfunceble-raw2sqlalchemy/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.raise_(
  File "$HOME/miniconda/envs/pyfunceble-raw2sqlalchemy/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "$HOME/miniconda/envs/pyfunceble-raw2sqlalchemy/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 137, in _do_get
    return self._create_connection()
  File "$HOME/miniconda/envs/pyfunceble-raw2sqlalchemy/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 309, in _create_connection
    return _ConnectionRecord(self)
  File "$HOME/miniconda/envs/pyfunceble-raw2sqlalchemy/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 440, in __init__
    self.__connect(first_connect_check=True)
  File "$HOME/miniconda/envs/pyfunceble-raw2sqlalchemy/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "$HOME/miniconda/envs/pyfunceble-raw2sqlalchemy/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.raise_(
  File "$HOME/miniconda/envs/pyfunceble-raw2sqlalchemy/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "$HOME/miniconda/envs/pyfunceble-raw2sqlalchemy/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 656, in __connect
    connection = pool._invoke_creator(self)
  File "$HOME/miniconda/envs/pyfunceble-raw2sqlalchemy/lib/python3.8/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "$HOME/miniconda/envs/pyfunceble-raw2sqlalchemy/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 493, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "$HOME/miniconda/envs/pyfunceble-raw2sqlalchemy/lib/python3.8/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "$HOME/miniconda/envs/pyfunceble-raw2sqlalchemy/lib/python3.8/site-packages/pymysql/connections.py", line 327, in __init__
    self.connect()
  File "$HOME/miniconda/envs/pyfunceble-raw2sqlalchemy/lib/python3.8/site-packages/pymysql/connections.py", line 619, in connect
    raise exc
pymysql.err.OperationalError: (2003, "Can't connect to MySQL server on 'ip' (timed out)")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "$HOME/miniconda/envs/pyfunceble-raw2sqlalchemy/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "$HOME/miniconda/envs/pyfunceble-raw2sqlalchemy/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "$HOME/miniconda/envs/pyfunceble-raw2sqlalchemy/lib/python3.8/site-packages/PyFunceble/engine/database/migrations/old2new.py", line 227, in __tested_migration
    db_session.query(File).filter(File.path == data["file_path"]).one()
  File "$HOME/miniconda/envs/pyfunceble-raw2sqlalchemy/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3463, in one
    ret = self.one_or_none()
  File "$HOME/miniconda/envs/pyfunceble-raw2sqlalchemy/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3432, in one_or_none
    ret = list(self)
  File "$HOME/miniconda/envs/pyfunceble-raw2sqlalchemy/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3508, in __iter__
    return self._execute_and_instances(context)
  File "$HOME/miniconda/envs/pyfunceble-raw2sqlalchemy/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3529, in _execute_and_instances
    conn = self._get_bind_args(
  File "$HOME/miniconda/envs/pyfunceble-raw2sqlalchemy/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3544, in _get_bind_args
    return fn(
  File "$HOME/miniconda/envs/pyfunceble-raw2sqlalchemy/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3523, in _connection_from_session
    conn = self.session.connection(**kw)
  File "$HOME/miniconda/envs/pyfunceble-raw2sqlalchemy/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1138, in connection
    return self._connection_for_bind(
  File "$HOME/miniconda/envs/pyfunceble-raw2sqlalchemy/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1146, in _connection_for_bind
    return self.transaction._connection_for_bind(
  File "$HOME/miniconda/envs/pyfunceble-raw2sqlalchemy/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 433, in _connection_for_bind
    conn = bind._contextual_connect()
  File "$HOME/miniconda/envs/pyfunceble-raw2sqlalchemy/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2304, in _contextual_connect
    self._wrap_pool_connect(self.pool.connect, None),
  File "$HOME/miniconda/envs/pyfunceble-raw2sqlalchemy/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2341, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "$HOME/miniconda/envs/pyfunceble-raw2sqlalchemy/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1583, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "$HOME/miniconda/envs/pyfunceble-raw2sqlalchemy/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "$HOME/miniconda/envs/pyfunceble-raw2sqlalchemy/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2338, in _wrap_pool_connect
    return fn()
  File "$HOME/miniconda/envs/pyfunceble-raw2sqlalchemy/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 364, in connect
    return _ConnectionFairy._checkout(self)
  File "$HOME/miniconda/envs/pyfunceble-raw2sqlalchemy/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 778, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "$HOME/miniconda/envs/pyfunceble-raw2sqlalchemy/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 495, in checkout
    rec = pool._do_get()
  File "$HOME/miniconda/envs/pyfunceble-raw2sqlalchemy/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 140, in _do_get
    self._dec_overflow()
  File "$HOME/miniconda/envs/pyfunceble-raw2sqlalchemy/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.raise_(
  File "$HOME/miniconda/envs/pyfunceble-raw2sqlalchemy/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "$HOME/miniconda/envs/pyfunceble-raw2sqlalchemy/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 137, in _do_get
    return self._create_connection()
  File "$HOME/miniconda/envs/pyfunceble-raw2sqlalchemy/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 309, in _create_connection
    return _ConnectionRecord(self)
  File "$HOME/miniconda/envs/pyfunceble-raw2sqlalchemy/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 440, in __init__
    self.__connect(first_connect_check=True)
  File "$HOME/miniconda/envs/pyfunceble-raw2sqlalchemy/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "$HOME/miniconda/envs/pyfunceble-raw2sqlalchemy/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.raise_(
  File "$HOME/miniconda/envs/pyfunceble-raw2sqlalchemy/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "$HOME/miniconda/envs/pyfunceble-raw2sqlalchemy/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 656, in __connect
    connection = pool._invoke_creator(self)
  File "$HOME/miniconda/envs/pyfunceble-raw2sqlalchemy/lib/python3.8/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "$HOME/miniconda/envs/pyfunceble-raw2sqlalchemy/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 493, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "$HOME/miniconda/envs/pyfunceble-raw2sqlalchemy/lib/python3.8/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "$HOME/miniconda/envs/pyfunceble-raw2sqlalchemy/lib/python3.8/site-packages/pymysql/connections.py", line 327, in __init__
    self.connect()
  File "$HOME/miniconda/envs/pyfunceble-raw2sqlalchemy/lib/python3.8/site-packages/pymysql/connections.py", line 619, in connect
    raise exc
sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (2003, "Can't connect to MySQL server on 'ip' (timed out)")
(Background on this error at: http://sqlalche.me/e/13/e3q8)
```

<details>

Same script but on 5c05383 is still hanging on trying to connect (See keybase)

**Comment by funilrys** [comment]
Fixed by https://github.com/funilrys/PyFunceble/commit/18d533056fe9da213b36cfd6f2b6003aa8d9529f (and its children).

**P.S: Please DO NOT close this issue manually. This issue is going to be closed automatically once https://github.com/funilrys/PyFunceble/commit/18d533056fe9da213b36cfd6f2b6003aa8d9529f will be merged to master.**
