### ISSUE TITLE
[Bug]: FileNotFoundError, First start fresh installaton 

### ISSUE THREAD

**Issue by ZeroDot1** [funilrys/PyFunceble#112]
## Bug description
Directly after the start a file not found error occurs. 

```bash
pyfunceble -m -a -f "/home/Your_file.txt"
'/home/user/.config/PyFunceble/.PyFunceble.yaml' was not found.
Install and load hte default configuration at the mentioned location? [y/n] y
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/PyFunceble/config/loader.py", line 334, in __load_central_config
    raise FileNotFoundError(self.path_to_config)
FileNotFoundError: /home/user/.config/PyFunceble/.PyFunceble.yaml
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/PyFunceble/config/loader.py", line 505, in __load_them_all
    self.__load_central_config()
  File "/usr/lib/python3.8/site-packages/PyFunceble/config/loader.py", line 124, in wrapper
    return func(self, *args, **kwargs)  # pylint: disable=not-callable
  File "/usr/lib/python3.8/site-packages/PyFunceble/config/loader.py", line 340, in __load_central_config
    raise PyFunceble.exceptions.ConfigurationFileNotFound()
PyFunceble.exceptions.ConfigurationFileNotFound

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/pyfunceble", line 33, in <module>
    sys.exit(load_entry_point('PyFunceble-dev==3.2.10', 'console_scripts', 'pyfunceble')())
  File "/usr/lib/python3.8/site-packages/PyFunceble/cli/__init__.py", line 1186, in tool
    raise exception
  File "/usr/lib/python3.8/site-packages/PyFunceble/cli/__init__.py", line 89, in tool
    PyFunceble.load_config(generate_directory_structure=False)
  File "/usr/lib/python3.8/site-packages/PyFunceble/__init__.py", line 700, in load_config
    loader.get_config()
  File "/usr/lib/python3.8/site-packages/PyFunceble/config/loader.py", line 136, in wrapper
    self.__load_them_all()  # pylint: disable=protected-access
  File "/usr/lib/python3.8/site-packages/PyFunceble/config/loader.py", line 511, in __load_them_all
    self.__load_central_config()
  File "/usr/lib/python3.8/site-packages/PyFunceble/config/loader.py", line 124, in wrapper
    return func(self, *args, **kwargs)  # pylint: disable=not-callable
  File "/usr/lib/python3.8/site-packages/PyFunceble/config/loader.py", line 342, in __load_central_config
    self.fix_paths()
  File "/usr/lib/python3.8/site-packages/PyFunceble/config/loader.py", line 438, in fix_paths
    self.config["outputs"][main_key]["directory"]
TypeError: 'NoneType' object is not subscriptable

```

## Modifications under `.PyFunceble.yaml`
NO.
## Reproduction

1. Run 'pyfunceble -m -a -f "/home/Your_file.txt"'
2. Press Y &ENTER and the error occurs.

## Expected behavior
That a standard configuration is created that I can use directly for testing.

## Versions

**OS:** Arch Linux 5.8.7-arch1-2
**Python Version:** 3.8.5
**PyFunceble Version:** pyfunceble-dev  3.2.10-1

**Comment by spirillen** [comment]
Hi @ZeroDot1 That bug was fixed in the in a later release, if you upgrade to at least 3.2.2 it is solved. Also another inportant bug was solved where the source file was deleted :unamused:  See: <https://github.com/funilrys/PyFunceble/issues/98>

And unless you use a SQL backend I would recommend you to switch to the 3.2.12@dev version, until the 3.3.0@master is released (Build failure)

If you uses a SQL backend, I'll endorce you to start by the 3.2.2 master and then when you are dong, get the @dev op and running to convert the DB as it takes it's time. I have been running 20 travis-ci +`-m  -p 19` from for over a week now, however I have 7.2m+ records....

**Comment by ZeroDot1** [comment]
@spirillen @funilrys OK, with the newer version the problem is solved, thanks.

**Comment by ZeroDot1** [comment]
https://github.com/funilrys/PyFunceble/pull/113

**Comment by spirillen** [comment]
Your welcome :smile:

**Comment by funilrys** [comment]
Thanks @spirillen for handling this!

Closing.
