### ISSUE TITLE
Travis-CI local db + sqlalchemy

### ISSUE THREAD

**Issue by spirillen** [funilrys/PyFunceble#118]
## Bug description
```
pymysql.err.DataError: (1264, "Out of range value for column 'epoch' at row 1")
(Background on this error at: http://sqlalche.me/e/13/9h9h)
```

## Modifications under `.PyFunceble.yaml`

None

## Reproduction

Follow the failed builds at <https://travis-ci.com/github/Import-External-Sources/google.tld/builds>

## Expected behavior
Don't think this is a necessary point to describe :smiley: 

## Versions

**OS:** conda 4.8.5
**Python Version:** 3.8.5
**PyFunceble Version:** 3.3.3.dev (Teal Blauwbok: Tick)

## Additional context
<details><summary>Full error log</summary>

Traceback (most recent call last):

  File "/home/travis/miniconda/envs/test-environment/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context

    self.dialect.do_execute(

  File "/home/travis/miniconda/envs/test-environment/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute

    cursor.execute(statement, parameters)

  File "/home/travis/miniconda/envs/test-environment/lib/python3.8/site-packages/pymysql/cursors.py", line 163, in execute

    result = self._query(query)

  File "/home/travis/miniconda/envs/test-environment/lib/python3.8/site-packages/pymysql/cursors.py", line 321, in _query

    conn.query(q)

  File "/home/travis/miniconda/envs/test-environment/lib/python3.8/site-packages/pymysql/connections.py", line 505, in query

    self._affected_rows = self._read_query_result(unbuffered=unbuffered)

  File "/home/travis/miniconda/envs/test-environment/lib/python3.8/site-packages/pymysql/connections.py", line 724, in _read_query_result

    result.read()

  File "/home/travis/miniconda/envs/test-environment/lib/python3.8/site-packages/pymysql/connections.py", line 1069, in read

    first_packet = self.connection._read_packet()

  File "/home/travis/miniconda/envs/test-environment/lib/python3.8/site-packages/pymysql/connections.py", line 676, in _read_packet

    packet.raise_for_error()

  File "/home/travis/miniconda/envs/test-environment/lib/python3.8/site-packages/pymysql/protocol.py", line 223, in raise_for_error

    err.raise_mysql_exception(self._data)

  File "/home/travis/miniconda/envs/test-environment/lib/python3.8/site-packages/pymysql/err.py", line 107, in raise_mysql_exception

    raise errorclass(errno, errval)

pymysql.err.DataError: (1264, "Out of range value for column 'epoch' at row 1")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "/home/travis/miniconda/envs/test-environment/bin/[secure]", line 8, in <module>

    sys.exit(tool())

  File "/home/travis/miniconda/envs/test-environment/lib/python3.8/site-packages/[secure]/cli/__init__.py", line 1209, in tool

    raise exception

  File "/home/travis/miniconda/envs/test-environment/lib/python3.8/site-packages/[secure]/cli/__init__.py", line 1194, in tool

    Dispatcher(

  File "/home/travis/miniconda/envs/test-environment/lib/python3.8/site-packages/[secure]/cli/dispatcher.py", line 131, in __init__

    self.dispatch_file_test(

  File "/home/travis/miniconda/envs/test-environment/lib/python3.8/site-packages/[secure]/cli/dispatcher.py", line 183, in dispatch_file_test

    [secure].core.File(file_path, "domain").run_test()

  File "/home/travis/miniconda/envs/test-environment/lib/python3.8/site-packages/[secure]/core/file.py", line 655, in run_test

    self.__test_line(line)

  File "/home/travis/miniconda/envs/test-environment/lib/python3.8/site-packages/[secure]/core/file.py", line 537, in __test_line

    self.__run_single_test(

  File "/home/travis/miniconda/envs/test-environment/lib/python3.8/site-packages/[secure]/core/file.py", line 489, in __run_single_test

    result = self.test(subject)

  File "/home/travis/miniconda/envs/test-environment/lib/python3.8/site-packages/[secure]/core/file.py", line 310, in test

    result = [secure].status.DomainAndIpAvailability(

  File "/home/travis/miniconda/envs/test-environment/lib/python3.8/site-packages/[secure]/status/availability/domain_and_ip.py", line 73, in __init__

    self.__gather()

  File "/home/travis/miniconda/envs/test-environment/lib/python3.8/site-packages/[secure]/status/availability/domain_and_ip.py", line 186, in __gather

    ) = self.__gather_expiration_date()

  File "/home/travis/miniconda/envs/test-environment/lib/python3.8/site-packages/[secure]/status/availability/domain_and_ip.py", line 121, in __gather_expiration_date

    self.whois_db.add(

  File "/home/travis/miniconda/envs/test-environment/lib/python3.8/site-packages/[secure]/database/whois.py", line 385, in add

    self[subject] = data

  File "/home/travis/miniconda/envs/test-environment/lib/python3.8/site-packages/[secure]/database/whois.py", line 202, in __setitem__

    self.__setitem_mysql(index, value)

  File "/home/travis/miniconda/envs/test-environment/lib/python3.8/site-packages/[secure]/database/whois.py", line 193, in __setitem_mysql

    db_session.commit()

  File "/home/travis/miniconda/envs/test-environment/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1042, in commit

    self.transaction.commit()

  File "/home/travis/miniconda/envs/test-environment/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 504, in commit

    self._prepare_impl()

  File "/home/travis/miniconda/envs/test-environment/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 483, in _prepare_impl

    self.session.flush()

  File "/home/travis/miniconda/envs/test-environment/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 2523, in flush

    self._flush(objects)

  File "/home/travis/miniconda/envs/test-environment/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 2664, in _flush

    transaction.rollback(_capture_exception=True)

  File "/home/travis/miniconda/envs/test-environment/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__

    compat.raise_(

  File "/home/travis/miniconda/envs/test-environment/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_

    raise exception

  File "/home/travis/miniconda/envs/test-environment/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 2624, in _flush

    flush_context.execute()

  File "/home/travis/miniconda/envs/test-environment/lib/python3.8/site-packages/sqlalchemy/orm/unitofwork.py", line 422, in execute

    rec.execute(self)

  File "/home/travis/miniconda/envs/test-environment/lib/python3.8/site-packages/sqlalchemy/orm/unitofwork.py", line 586, in execute

    persistence.save_obj(

  File "/home/travis/miniconda/envs/test-environment/lib/python3.8/site-packages/sqlalchemy/orm/persistence.py", line 239, in save_obj

    _emit_insert_statements(

  File "/home/travis/miniconda/envs/test-environment/lib/python3.8/site-packages/sqlalchemy/orm/persistence.py", line 1135, in _emit_insert_statements

    result = cached_connections[connection].execute(

  File "/home/travis/miniconda/envs/test-environment/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1011, in execute

    return meth(self, multiparams, params)

  File "/home/travis/miniconda/envs/test-environment/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection

    return connection._execute_clauseelement(self, multiparams, params)

  File "/home/travis/miniconda/envs/test-environment/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1124, in _execute_clauseelement

    ret = self._execute_context(

  File "/home/travis/miniconda/envs/test-environment/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1316, in _execute_context

    self._handle_dbapi_exception(

  File "/home/travis/miniconda/envs/test-environment/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1510, in _handle_dbapi_exception

    util.raise_(

  File "/home/travis/miniconda/envs/test-environment/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_

    raise exception

  File "/home/travis/miniconda/envs/test-environment/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context

    self.dialect.do_execute(

  File "/home/travis/miniconda/envs/test-environment/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute

    cursor.execute(statement, parameters)

  File "/home/travis/miniconda/envs/test-environment/lib/python3.8/site-packages/pymysql/cursors.py", line 163, in execute

    result = self._query(query)

  File "/home/travis/miniconda/envs/test-environment/lib/python3.8/site-packages/pymysql/cursors.py", line 321, in _query

    conn.query(q)

  File "/home/travis/miniconda/envs/test-environment/lib/python3.8/site-packages/pymysql/connections.py", line 505, in query

    self._affected_rows = self._read_query_result(unbuffered=unbuffered)

  File "/home/travis/miniconda/envs/test-environment/lib/python3.8/site-packages/pymysql/connections.py", line 724, in _read_query_result

    result.read()

  File "/home/travis/miniconda/envs/test-environment/lib/python3.8/site-packages/pymysql/connections.py", line 1069, in read

    first_packet = self.connection._read_packet()

  File "/home/travis/miniconda/envs/test-environment/lib/python3.8/site-packages/pymysql/connections.py", line 676, in _read_packet

    packet.raise_for_error()

  File "/home/travis/miniconda/envs/test-environment/lib/python3.8/site-packages/pymysql/protocol.py", line 223, in raise_for_error

    err.raise_mysql_exception(self._data)

  File "/home/travis/miniconda/envs/test-environment/lib/python3.8/site-packages/pymysql/err.py", line 107, in raise_mysql_exception

    raise errorclass(errno, errval)

sqlalchemy.exc.DataError: (pymysql.err.DataError) (1264, "Out of range value for column 'epoch' at row 1")

[SQL: INSERT INTO pyfunceble_whois_record (created, modified, subject, expiration_date, epoch, state, record, server) VALUES (%(created)s, %(modified)s, %(subject)s, %(expiration_date)s, %(epoch)s, %(state)s, %(record)s, %(server)s)]

[parameters: {'created': datetime.datetime(2020, 9, 15, 9, 12, 41, 320589), 'modified': datetime.datetime(2020, 9, 15, 9, 12, 41, 320595), 'subject': 'abc.gs', 'expiration_date': '01-dec-2050', 'epoch': 2553465600.0, 'state': 'future', 'record': None, 'server': 'whois.nic.gs'}]

(Background on this error at: http://sqlalche.me/e/13/9h9h)

</details>

**Comment by funilrys** [comment]
The one which caused this was the `mining` tables. As of 4.0.0, we deleted it.
The reason I deleted it is because there is no need for it anymore because of the new multithreading schema I introduced for the CLI testing.

More insight into the new schema:
![Thread Model PyFunceble CLI](https://user-images.githubusercontent.com/14127285/102711790-95d54900-42bc-11eb-82a9-b8b5eb0205d8.png)


--------
Note to self: Document the new threading schema.
