### ISSUE TITLE
sqlalchemy +empty database (new)

### ISSUE THREAD

**Issue by spirillen** [funilrys/PyFunceble#120]
## Bug description
Created a new Database in MariaDB 10.5 and tested with the rpz files from <https://github.com/funilrys/PyFunceble/issues/86>

## Modifications under `.PyFunceble.yaml`

Added the `RPZ: false` to the pyfunceble-env.yml

## Reproduction
Greate a empty DB and append info to `$HOME/.config/PyFunceble/.pyfunceble-env`

Test string
```
pyfunceble -db --database-type mariadb --syntax -m --rpz -a -f /tmp/adult.mypdns.cloud
```

The tables are only partly generated

![image](https://user-images.githubusercontent.com/44526987/93687749-5a11c400-fac0-11ea-87be-bcf3151aff80.png)

<details><summary>Error message</summary>

Subject                                                                                              Status      Expiration Date   Source     HTTP Code 
---------------------------------------------------------------------------------------------------- ----------- ----------------- ---------- ----------
Traceback (most recent call last):
  File "/home/spirillen/miniconda/envs/pyfunceble-rpz/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/home/spirillen/miniconda/envs/pyfunceble-rpz/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
  File "/home/spirillen/miniconda/envs/pyfunceble-rpz/lib/python3.8/site-packages/pymysql/cursors.py", line 163, in execute
    result = self._query(query)
  File "/home/spirillen/miniconda/envs/pyfunceble-rpz/lib/python3.8/site-packages/pymysql/cursors.py", line 321, in _query
    conn.query(q)
  File "/home/spirillen/miniconda/envs/pyfunceble-rpz/lib/python3.8/site-packages/pymysql/connections.py", line 505, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/spirillen/miniconda/envs/pyfunceble-rpz/lib/python3.8/site-packages/pymysql/connections.py", line 724, in _read_query_result
    result.read()
  File "/home/spirillen/miniconda/envs/pyfunceble-rpz/lib/python3.8/site-packages/pymysql/connections.py", line 1069, in read
    first_packet = self.connection._read_packet()
  File "/home/spirillen/miniconda/envs/pyfunceble-rpz/lib/python3.8/site-packages/pymysql/connections.py", line 676, in _read_packet
    packet.raise_for_error()
  File "/home/spirillen/miniconda/envs/pyfunceble-rpz/lib/python3.8/site-packages/pymysql/protocol.py", line 223, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/spirillen/miniconda/envs/pyfunceble-rpz/lib/python3.8/site-packages/pymysql/err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1146, "Table 'pyfunceble.pyfunceble_status' doesn't exist")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/spirillen/miniconda/envs/pyfunceble-rpz/bin/pyfunceble", line 8, in <module>
    sys.exit(tool())
  File "/home/spirillen/miniconda/envs/pyfunceble-rpz/lib/python3.8/site-packages/PyFunceble/cli/__init__.py", line 1226, in tool
    raise exception
  File "/home/spirillen/miniconda/envs/pyfunceble-rpz/lib/python3.8/site-packages/PyFunceble/cli/__init__.py", line 1211, in tool
    Dispatcher(
  File "/home/spirillen/miniconda/envs/pyfunceble-rpz/lib/python3.8/site-packages/PyFunceble/cli/dispatcher.py", line 131, in __init__
    self.dispatch_file_test(
  File "/home/spirillen/miniconda/envs/pyfunceble-rpz/lib/python3.8/site-packages/PyFunceble/cli/dispatcher.py", line 174, in dispatch_file_test
    PyFunceble.core.Multiprocess(file_path, "domain").run_test()
  File "/home/spirillen/miniconda/envs/pyfunceble-rpz/lib/python3.8/site-packages/PyFunceble/core/multiprocess.py", line 566, in run_test
    self.__run_multiprocess_test(shadow_file, manager, tracker=tracker)
  File "/home/spirillen/miniconda/envs/pyfunceble-rpz/lib/python3.8/site-packages/PyFunceble/core/multiprocess.py", line 422, in __run_multiprocess_test
    self.__start_process(
  File "/home/spirillen/miniconda/envs/pyfunceble-rpz/lib/python3.8/site-packages/PyFunceble/core/multiprocess.py", line 303, in __start_process
    if subject in self.autocontinue:
  File "/home/spirillen/miniconda/envs/pyfunceble-rpz/lib/python3.8/site-packages/PyFunceble/engine/auto_continue.py", line 152, in __contains__
    db_session.query(Status)
  File "/home/spirillen/miniconda/envs/pyfunceble-rpz/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3463, in one
    ret = self.one_or_none()
  File "/home/spirillen/miniconda/envs/pyfunceble-rpz/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3432, in one_or_none
    ret = list(self)
  File "/home/spirillen/miniconda/envs/pyfunceble-rpz/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3508, in __iter__
    return self._execute_and_instances(context)
  File "/home/spirillen/miniconda/envs/pyfunceble-rpz/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3533, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/home/spirillen/miniconda/envs/pyfunceble-rpz/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1011, in execute
    return meth(self, multiparams, params)
  File "/home/spirillen/miniconda/envs/pyfunceble-rpz/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/spirillen/miniconda/envs/pyfunceble-rpz/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1124, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/spirillen/miniconda/envs/pyfunceble-rpz/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1316, in _execute_context
    self._handle_dbapi_exception(
  File "/home/spirillen/miniconda/envs/pyfunceble-rpz/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1510, in _handle_dbapi_exception
    util.raise_(
  File "/home/spirillen/miniconda/envs/pyfunceble-rpz/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/home/spirillen/miniconda/envs/pyfunceble-rpz/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/home/spirillen/miniconda/envs/pyfunceble-rpz/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
  File "/home/spirillen/miniconda/envs/pyfunceble-rpz/lib/python3.8/site-packages/pymysql/cursors.py", line 163, in execute
    result = self._query(query)
  File "/home/spirillen/miniconda/envs/pyfunceble-rpz/lib/python3.8/site-packages/pymysql/cursors.py", line 321, in _query
    conn.query(q)
  File "/home/spirillen/miniconda/envs/pyfunceble-rpz/lib/python3.8/site-packages/pymysql/connections.py", line 505, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/spirillen/miniconda/envs/pyfunceble-rpz/lib/python3.8/site-packages/pymysql/connections.py", line 724, in _read_query_result
    result.read()
  File "/home/spirillen/miniconda/envs/pyfunceble-rpz/lib/python3.8/site-packages/pymysql/connections.py", line 1069, in read
    first_packet = self.connection._read_packet()
  File "/home/spirillen/miniconda/envs/pyfunceble-rpz/lib/python3.8/site-packages/pymysql/connections.py", line 676, in _read_packet
    packet.raise_for_error()
  File "/home/spirillen/miniconda/envs/pyfunceble-rpz/lib/python3.8/site-packages/pymysql/protocol.py", line 223, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/spirillen/miniconda/envs/pyfunceble-rpz/lib/python3.8/site-packages/pymysql/err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
sqlalchemy.exc.ProgrammingError: (pymysql.err.ProgrammingError) (1146, "Table 'pyfunceble.pyfunceble_status' doesn't exist")
[SQL: SELECT pyfunceble_status.id AS pyfunceble_status_id, pyfunceble_status.created AS pyfunceble_status_created, pyfunceble_status.modified AS pyfunceble_status_modified, pyfunceble_status.file_id AS pyfunceble_status_file_id, pyfunceble_status.tested AS pyfunceble_status_tested, pyfunceble_status._status AS pyfunceble_status__status, pyfunceble_status.status AS pyfunceble_status_status, pyfunceble_status._status_source AS pyfunceble_status__status_source, pyfunceble_status.status_source AS pyfunceble_status_status_source, pyfunceble_status.domain_syntax_validation AS pyfunceble_status_domain_syntax_validation, pyfunceble_status.expiration_date AS pyfunceble_status_expiration_date, pyfunceble_status.http_status_code AS pyfunceble_status_http_status_code, pyfunceble_status.ipv4_range_syntax_validation AS pyfunceble_status_ipv4_range_syntax_validation, pyfunceble_status.ipv4_syntax_validation AS pyfunceble_status_ipv4_syntax_validation, pyfunceble_status.ipv6_range_syntax_validation AS pyfunceble_status_ipv6_range_syntax_validation, pyfunceble_status.ipv6_syntax_validation AS pyfunceble_status_ipv6_syntax_validation, pyfunceble_status.subdomain_syntax_validation AS pyfunceble_status_subdomain_syntax_validation, pyfunceble_status.url_syntax_validation AS pyfunceble_status_url_syntax_validation, pyfunceble_status.is_complement AS pyfunceble_status_is_complement, pyfunceble_status.test_completed AS pyfunceble_status_test_completed, pyfunceble_status.tested_at AS pyfunceble_status_tested_at 
FROM pyfunceble_status INNER JOIN pyfunceble_file ON pyfunceble_file.id = pyfunceble_status.file_id 
WHERE pyfunceble_status.tested = %(tested_1)s AND pyfunceble_file.path = %(path_1)s]
[parameters: {'tested_1': 'adult.mypdns.cloud.', 'path_1': '/tmp/adult.mypdns.cloud'}]
(Background on this error at: http://sqlalche.me/e/13/f405)

</details>

## Expected behavior
I had expected that PyFunceble with sqlalchemy had created the tables that is need in the Database

## Versions

**OS:** MiniConda
**Python Version:** 3.8.5 on Debian 10 (Buster)
**PyFunceble Version:** <https://github.com/funilrys/PyFunceble/tree/rpz-syntax-check>

## Additional context
> ProgrammingError
> 
> Exception raised for programming errors, e.g. table not found or already exists, syntax error in the SQL statement, wrong number of parameters specified, etc.
> 
> This error is a DBAPI Error and originates from the database driver (DBAPI), not SQLAlchemy itself.
> 
> The ProgrammingError is sometimes raised by drivers in the context of the database connection being dropped, or not being able to connect to the database. For tips on how to deal with this, see the section Dealing with Disconnects.
> NotSupportedError
> 
> Exception raised in case a method or database API was used which is not supported by the database, e.g. requesting a .rollback() on a connection that does not support transaction or has transactions turned off.
> 
> This error is a DBAPI Error and originates from the database driver (DBAPI), not SQLAlchemy itself.
> 
> <http://sqlalche.me/e/13/f405>

**Comment by spirillen** [comment]
Just tested the same flow with the `pyfunceble-dev` version, and the expected behavior is satisfied, tables is generated.

This turns this "issue" into a remember to alter CREATE tables

**Comment by funilrys** [comment]
It depends on the version written into your `alembic_version`. Alembic (the one who actually apply layout change from SQLAlchemy Models/Schemas) will upgrade the database layout only if the version you have in your database is lower than the latest one in his record (`PyFunceble/data/alembic/versions`). 

I'm not sure this is actually an issue. I know in the past I always ensured that the database was created but I now delegate everything to alembic+sqlalchemy. Normally, if you don't manually alter your database, this should not happen.

**Comment by spirillen** [comment]
> I'm not sure this is actually an issue. I know in the past I always ensured that the database was created but I now delegate everything to alembic+sqlalchemy. Normally, if you don't manually alter your database, this should not happen.

True, but in this case, I'm talking about a entire clean DB. DB only, No tables, then it failed, therefor I re-ran the test with the `pyfunceble 3.3.3.dev (Teal Blauwbok: Tick)` and the tables was creates, and I changed the issue state to a "remember" as it only applied to the `@rpz-syntax` version :)

I going to give it a new spin later, whit your latest commits :+1:

**Comment by funilrys** [comment]
Should I guess that this is not happening anymore with the latest versions?

**Comment by spirillen** [comment]
> Should I guess that this is not happening anymore with the latest versions?

I'm not going to test any further with 3.x :smiley: I'm only looking ahead toward 4.x from here

**Comment by funilrys** [comment]
Closing as I assume that this is not happening again.
