### ISSUE TITLE
pyfunceble 3.3.3.dev (Teal Blauwbok: Tick) and a thread of bugs by teststring...

### ISSUE THREAD

**Issue by spirillen** [funilrys/PyFunceble#123]
## Bug description
I'm going to alter this issue template, as I will be posting a series of errors with `pyfunceble 3.3.3.dev (Teal Blauwbok: Tick)` under different test strings.

## Modifications under `.PyFunceble.yaml`

None

## Reproduction

See #Versions and following test strings.

## Expected behavior
Mostly no errors

## Versions

**OS:** conda 4.8.5  on Ubuntu 20.04
**Python Version:** 3.8.5
**PyFunceble Version:** pyfunceble 3.3.3.dev (Teal Blauwbok: Tick)

**Comment by spirillen** [comment]
# String
`
pyfunceble -h -nf -db --database-type mariadb -f /var/storage01/repos/github/mypdns/porn-records/submit_here/adult.mypdns.cloud/wildcard.list --dns 192.168.1.105 --mining -m -ex -a -ua firefox --complements --share-logs
`
<details><summary>Error output</summary>

Traceback (most recent call last):
  File "/home/joakim/miniconda/envs/pyfunceble-dev/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3463, in one
    ret = self.one_or_none()
  File "/home/joakim/miniconda/envs/pyfunceble-dev/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3440, in one_or_none
    raise orm_exc.MultipleResultsFound(
sqlalchemy.orm.exc.MultipleResultsFound: Multiple rows were found for one_or_none()

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/joakim/miniconda/envs/pyfunceble-dev/lib/python3.8/site-packages/PyFunceble/core/multiprocess.py", line 92, in run
    Process.run(self)
  File "/home/joakim/miniconda/envs/pyfunceble-dev/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/joakim/miniconda/envs/pyfunceble-dev/lib/python3.8/site-packages/PyFunceble/core/multiprocess.py", line 205, in test
    self.post_test_treatment(
  File "/home/joakim/miniconda/envs/pyfunceble-dev/lib/python3.8/site-packages/PyFunceble/core/file.py", line 403, in post_test_treatment
    mining.mine(test_output["tested"], file_content_type)
  File "/home/joakim/miniconda/envs/pyfunceble-dev/lib/python3.8/site-packages/PyFunceble/engine/mining.py", line 478, in mine
    self[subject] = [local_result]
  File "/home/joakim/miniconda/envs/pyfunceble-dev/lib/python3.8/site-packages/PyFunceble/engine/mining.py", line 166, in __setitem__
    db_session.query(Status)
  File "/home/joakim/miniconda/envs/pyfunceble-dev/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3465, in one
    util.raise_(
  File "/home/joakim/miniconda/envs/pyfunceble-dev/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
sqlalchemy.orm.exc.MultipleResultsFound: Multiple rows were found for one()

</details>

**Comment by spirillen** [comment]
# String
```shell
pyfunceble -h --plain -db --database-type mariadb -f https://raw.githubusercontent.com/mypdns/porn-records/master/submit_here/adult.mypdns.cloud/wildcard.list --dns 192.168.1.105 --mining -m -ex -a -ua firefox -nf --complements --share-logs
```
<details><summary>Error output</summary>

Traceback (most recent call last):
  File "/home/joakim/miniconda/envs/pyfunceble-dev/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3463, in one
    ret = self.one_or_none()
  File "/home/joakim/miniconda/envs/pyfunceble-dev/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3440, in one_or_none
    raise orm_exc.MultipleResultsFound(
sqlalchemy.orm.exc.MultipleResultsFound: Multiple rows were found for one_or_none()

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/joakim/miniconda/envs/pyfunceble-dev/lib/python3.8/site-packages/PyFunceble/core/multiprocess.py", line 92, in run
    Process.run(self)
  File "/home/joakim/miniconda/envs/pyfunceble-dev/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/joakim/miniconda/envs/pyfunceble-dev/lib/python3.8/site-packages/PyFunceble/core/multiprocess.py", line 205, in test
    self.post_test_treatment(
  File "/home/joakim/miniconda/envs/pyfunceble-dev/lib/python3.8/site-packages/PyFunceble/core/file.py", line 403, in post_test_treatment
    mining.mine(test_output["tested"], file_content_type)
  File "/home/joakim/miniconda/envs/pyfunceble-dev/lib/python3.8/site-packages/PyFunceble/engine/mining.py", line 478, in mine
    self[subject] = [local_result]
  File "/home/joakim/miniconda/envs/pyfunceble-dev/lib/python3.8/site-packages/PyFunceble/engine/mining.py", line 166, in __setitem__
    db_session.query(Status)
  File "/home/joakim/miniconda/envs/pyfunceble-dev/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3465, in one
    util.raise_(
  File "/home/joakim/miniconda/envs/pyfunceble-dev/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
sqlalchemy.orm.exc.MultipleResultsFound: Multiple rows were found for one()

</details>

**Comment by spirillen** [comment]
# String
```shell
pyfunceble -h --plain -db --database-type mariadb -f https://raw.githubusercontent.com/mypdns/porn-records/master/submit_here/adult.mypdns.cloud/wildcard.list --dns 192.168.1.105 --mining -m -ex -a --reputation -ua firefox -nf --complements --share-logs
```
<details><summary>Error output</summary>

Traceback (most recent call last):
  File "/home/joakim/miniconda/envs/pyfunceble-dev/bin/pyfunceble", line 8, in <module>
    sys.exit(tool())
  File "/home/joakim/miniconda/envs/pyfunceble-dev/lib/python3.8/site-packages/PyFunceble/cli/__init__.py", line 1209, in tool
    raise exception
  File "/home/joakim/miniconda/envs/pyfunceble-dev/lib/python3.8/site-packages/PyFunceble/cli/__init__.py", line 1194, in tool
    Dispatcher(
  File "/home/joakim/miniconda/envs/pyfunceble-dev/lib/python3.8/site-packages/PyFunceble/cli/dispatcher.py", line 131, in __init__
    self.dispatch_file_test(
  File "/home/joakim/miniconda/envs/pyfunceble-dev/lib/python3.8/site-packages/PyFunceble/cli/dispatcher.py", line 174, in dispatch_file_test
    PyFunceble.core.Multiprocess(file_path, "domain").run_test()
  File "/home/joakim/miniconda/envs/pyfunceble-dev/lib/python3.8/site-packages/PyFunceble/core/multiprocess.py", line 142, in __init__
    super().__init__(file, file_content_type=file_content_type)
  File "/home/joakim/miniconda/envs/pyfunceble-dev/lib/python3.8/site-packages/PyFunceble/core/file.py", line 100, in __init__
    self.autocontinue = PyFunceble.engine.AutoContinue(
  File "/home/joakim/miniconda/envs/pyfunceble-dev/lib/python3.8/site-packages/PyFunceble/engine/auto_continue.py", line 128, in __init__
    PyFunceble.output.Clean(file_path=self.filename)
  File "/home/joakim/miniconda/envs/pyfunceble-dev/lib/python3.8/site-packages/PyFunceble/output/clean.py", line 84, in __init__
    self.almost_everything(clean_all, file_path)
  File "/home/joakim/miniconda/envs/pyfunceble-dev/lib/python3.8/site-packages/PyFunceble/output/clean.py", line 265, in almost_everything
    db_session.query(File).filter(File.path == file_path).one()
  File "/home/joakim/miniconda/envs/pyfunceble-dev/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3473, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()

</details>

**Comment by spirillen** [comment]
# String
```shell
pyfunceble -h --plain -db --database-type mariadb --dns 192.168.1.105 --mining -m -ex -a --reputation --use-reputation-data -ua firefox -nf --complements --share-logs -f https://raw.githubusercontent.com/mypdns/porn-records/master/submit_here/adult.mypdns.cloud/wildcard.list
```
<details><summary>Error output</summary>

Traceback (most recent call last):
  File "/home/joakim/miniconda/envs/pyfunceble-dev/bin/pyfunceble", line 8, in <module>
    sys.exit(tool())
  File "/home/joakim/miniconda/envs/pyfunceble-dev/lib/python3.8/site-packages/PyFunceble/cli/__init__.py", line 1209, in tool
    raise exception
  File "/home/joakim/miniconda/envs/pyfunceble-dev/lib/python3.8/site-packages/PyFunceble/cli/__init__.py", line 1194, in tool
    Dispatcher(
  File "/home/joakim/miniconda/envs/pyfunceble-dev/lib/python3.8/site-packages/PyFunceble/cli/dispatcher.py", line 131, in __init__
    self.dispatch_file_test(
  File "/home/joakim/miniconda/envs/pyfunceble-dev/lib/python3.8/site-packages/PyFunceble/cli/dispatcher.py", line 174, in dispatch_file_test
    PyFunceble.core.Multiprocess(file_path, "domain").run_test()
  File "/home/joakim/miniconda/envs/pyfunceble-dev/lib/python3.8/site-packages/PyFunceble/core/multiprocess.py", line 142, in __init__
    super().__init__(file, file_content_type=file_content_type)
  File "/home/joakim/miniconda/envs/pyfunceble-dev/lib/python3.8/site-packages/PyFunceble/core/file.py", line 100, in __init__
    self.autocontinue = PyFunceble.engine.AutoContinue(
  File "/home/joakim/miniconda/envs/pyfunceble-dev/lib/python3.8/site-packages/PyFunceble/engine/auto_continue.py", line 128, in __init__
    PyFunceble.output.Clean(file_path=self.filename)
  File "/home/joakim/miniconda/envs/pyfunceble-dev/lib/python3.8/site-packages/PyFunceble/output/clean.py", line 84, in __init__
    self.almost_everything(clean_all, file_path)
  File "/home/joakim/miniconda/envs/pyfunceble-dev/lib/python3.8/site-packages/PyFunceble/output/clean.py", line 265, in almost_everything
    db_session.query(File).filter(File.path == file_path).one()
  File "/home/joakim/miniconda/envs/pyfunceble-dev/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3473, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()

</details>

**Comment by spirillen** [comment]
# String
```shell
pyfunceble -h -db --database-type mariadb -f https://raw.githubusercontent.com/mypdns/porn-records/master/submit_here/adult.mypdns.cloud/wildcard.list --dns 192.168.1.105 --mining -m -ex -a --reputation --use-reputation-data -ua firefox -nf --complements --share-logs
```
<details><summary>Error output</summary>

Traceback (most recent call last):
  File "/home/joakim/miniconda/envs/pyfunceble-dev/bin/pyfunceble", line 8, in <module>
    sys.exit(tool())
  File "/home/joakim/miniconda/envs/pyfunceble-dev/lib/python3.8/site-packages/PyFunceble/cli/__init__.py", line 1209, in tool
    raise exception
  File "/home/joakim/miniconda/envs/pyfunceble-dev/lib/python3.8/site-packages/PyFunceble/cli/__init__.py", line 1194, in tool
    Dispatcher(
  File "/home/joakim/miniconda/envs/pyfunceble-dev/lib/python3.8/site-packages/PyFunceble/cli/dispatcher.py", line 131, in __init__
    self.dispatch_file_test(
  File "/home/joakim/miniconda/envs/pyfunceble-dev/lib/python3.8/site-packages/PyFunceble/cli/dispatcher.py", line 174, in dispatch_file_test
    PyFunceble.core.Multiprocess(file_path, "domain").run_test()
  File "/home/joakim/miniconda/envs/pyfunceble-dev/lib/python3.8/site-packages/PyFunceble/core/multiprocess.py", line 142, in __init__
    super().__init__(file, file_content_type=file_content_type)
  File "/home/joakim/miniconda/envs/pyfunceble-dev/lib/python3.8/site-packages/PyFunceble/core/file.py", line 100, in __init__
    self.autocontinue = PyFunceble.engine.AutoContinue(
  File "/home/joakim/miniconda/envs/pyfunceble-dev/lib/python3.8/site-packages/PyFunceble/engine/auto_continue.py", line 128, in __init__
    PyFunceble.output.Clean(file_path=self.filename)
  File "/home/joakim/miniconda/envs/pyfunceble-dev/lib/python3.8/site-packages/PyFunceble/output/clean.py", line 84, in __init__
    self.almost_everything(clean_all, file_path)
  File "/home/joakim/miniconda/envs/pyfunceble-dev/lib/python3.8/site-packages/PyFunceble/output/clean.py", line 265, in almost_everything
    db_session.query(File).filter(File.path == file_path).one()
  File "/home/joakim/miniconda/envs/pyfunceble-dev/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3473, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()

</details>

```
breake;
```

**Comment by spirillen** [comment]
@PyFunceble 3.3.6.dev (Teal Blauwbok: Gander)

Under Travis-ci there is a common error which I'm wondering about where is happening.

Using the central  DB to store the test results, however, on several CI's the following error occur

```
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.

Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#build-times-out-because-no-output-was-received
```

Links to a couple of the affected CI's:
  - https://travis-ci.com/github/dns-test/rpz.mypdns.cloud
  - https://travis-ci.com/github/dns-test/adult.mypdns.org
  - https://travis-ci.com/github/dns-test-26-30
  - https://travis-ci.com/github/DNS-test-01-05
  - https://travis-ci.com/github/DNS-test-36-40
  - https://travis-ci.com/github/dns-test-31-35

I have tried to activate the `- PYFUNCEBLE_DEBUG_ON_SCREEN: true` but log lines became to many, and the build failed before reviling the eventual error.

**Comment by ZeroDot1** [comment]
Another bug:

PyFunceble does not find all bad entries in a file.

Example for not found invalid entries: 

```js
0.0.0.0 140.82.32.54\032discord.actinium.org
0.0.0.0 140.82.32.54\032fastpool.actinium.org
0.0.0.0 140.82.32.54\032explorer.actinium.org
0.0.0.0 140.82.32.54\032faucet.actinium.org
0.0.0.0 140.82.32.54\032ln-explorer.actinium.org
0.0.0.0 140.82.32.54\032test-explorer.actinium.org
0.0.0.0 140.82.32.54\032transfer.actinium.org
0.0.0.0 140.82.32.54\032www.discord.actinium.org
```

**Comment by spirillen** [comment]
> Another bug:
> 
> PyFunceble does not find all bad entries in a file.
> 
> Example for not found invalid entries:
> 
> ```js
> 0.0.0.0 140.82.32.54\032discord.actinium.org
> 0.0.0.0 140.82.32.54\032fastpool.actinium.org
> 0.0.0.0 140.82.32.54\032explorer.actinium.org
> 0.0.0.0 140.82.32.54\032faucet.actinium.org
> 0.0.0.0 140.82.32.54\032ln-explorer.actinium.org
> 0.0.0.0 140.82.32.54\032test-explorer.actinium.org
> 0.0.0.0 140.82.32.54\032transfer.actinium.org
> 0.0.0.0 140.82.32.54\032www.discord.actinium.org
> ```

Interesting @ZeroDot1, so a mix of hex and non-hex fails (As I assume the `\032` is the dns hex ref.)
Thanks for sharing and help improving :+1: I know @funilrys will appreciate, as he is about rewriting the entire codebase and spending days writing test codes.

**Comment by funilrys** [comment]
> # String
> `pyfunceble -h -nf -db --database-type mariadb -f /var/storage01/repos/github/mypdns/porn-records/submit_here/adult.mypdns.cloud/wildcard.list --dns 192.168.1.105 --mining -m -ex -a -ua firefox --complements --share-logs`
> 
> Error output

The mining table is now gone.

**Comment by funilrys** [comment]
> # String
> ```shell
> pyfunceble -h --plain -db --database-type mariadb -f https://raw.githubusercontent.com/mypdns/porn-records/master/submit_here/adult.mypdns.cloud/wildcard.list --dns 192.168.1.105 --mining -m -ex -a -ua firefox -nf --complements --share-logs
> ```
> 
> Error output
> Traceback (most recent call last):
> File "/home/joakim/miniconda/envs/pyfunceble-dev/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3463, in one
> ret = self.one_or_none()
> File "/home/joakim/miniconda/envs/pyfunceble-dev/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3440, in one_or_none
> raise orm_exc.MultipleResultsFound(
> sqlalchemy.orm.exc.MultipleResultsFound: Multiple rows were found for one_or_none()
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
> File "/home/joakim/miniconda/envs/pyfunceble-dev/lib/python3.8/site-packages/PyFunceble/core/multiprocess.py", line 92, in run
> Process.run(self)
> File "/home/joakim/miniconda/envs/pyfunceble-dev/lib/python3.8/multiprocessing/process.py", line 108, in run
> self._target(*self._args, **self._kwargs) File "/home/joakim/miniconda/envs/pyfunceble-dev/lib/python3.8/site-packages/PyFunceble/core/multiprocess.py", line 205, in test self.post_test_treatment( File "/home/joakim/miniconda/envs/pyfunceble-dev/lib/python3.8/site-packages/PyFunceble/core/file.py", line 403, in post_test_treatment mining.mine(test_output["tested"], file_content_type) File "/home/joakim/miniconda/envs/pyfunceble-dev/lib/python3.8/site-packages/PyFunceble/engine/mining.py", line 478, in mine self[subject] = [local_result] File "/home/joakim/miniconda/envs/pyfunceble-dev/lib/python3.8/site-packages/PyFunceble/engine/mining.py", line 166, in **setitem** db_session.query(Status) File "/home/joakim/miniconda/envs/pyfunceble-dev/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3465, in one util.raise_( File "/home/joakim/miniconda/envs/pyfunceble-dev/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
> raise exception
> sqlalchemy.orm.exc.MultipleResultsFound: Multiple rows were found for one()

The mining table is now gone.

**Comment by funilrys** [comment]
> # String
> ```shell
> pyfunceble -h --plain -db --database-type mariadb --dns 192.168.1.105 --mining -m -ex -a --reputation --use-reputation-data -ua firefox -nf --complements --share-logs -f https://raw.githubusercontent.com/mypdns/porn-records/master/submit_here/adult.mypdns.cloud/wildcard.list
> ```
> 
> Error output

The mining table is now gone.

**Comment by funilrys** [comment]
> # String
> ```shell
> pyfunceble -h -db --database-type mariadb -f https://raw.githubusercontent.com/mypdns/porn-records/master/submit_here/adult.mypdns.cloud/wildcard.list --dns 192.168.1.105 --mining -m -ex -a --reputation --use-reputation-data -ua firefox -nf --complements --share-logs
> ```
> 
> Error output
> ```
> breake;
> ```

The mining table is now gone.

**Comment by funilrys** [comment]
Thanks, everybody. I'm closing this. I created some new issues to keep an eye on some of the things that may be still relevant to the incoming version. 

Closing.
