### ISSUE TITLE
Yet another odd error message that prevents me from running PyFunceble 

### ISSUE THREAD

**Issue by DandelionSprout** [funilrys/PyFunceble#125]
## Bug description
When trying to run PyFunceble on a file, the following error is shown:

```
imree@ImresPC /cygdrive/c/Users/imree/Desktop/Skrivebordsbilder/PyFunceble-greier/PyFunceble
$ PyFunceble -f Torsk1.txt

██████╗ ██╗   ██╗███████╗██╗   ██╗███╗   ██╗ ██████╗███████╗██████╗ ██╗     ███████╗
██╔══██╗╚██╗ ██╔╝██╔════╝██║   ██║████╗  ██║██╔════╝██╔════╝██╔══██╗██║     ██╔════╝
██████╔╝ ╚████╔╝ █████╗  ██║   ██║██╔██╗ ██║██║     █████╗  ██████╔╝██║     █████╗
██╔═══╝   ╚██╔╝  ██╔══╝  ██║   ██║██║╚██╗██║██║     ██╔══╝  ██╔══██╗██║     ██╔══╝
██║        ██║   ██║     ╚██████╔╝██║ ╚████║╚██████╗███████╗██████╔╝███████╗███████╗
╚═╝        ╚═╝   ╚═╝      ╚═════╝ ╚═╝  ╚═══╝ ╚═════╝╚══════╝╚═════╝ ╚══════╝╚══════╝



Subject                                                                                              Status      HTTP Code
---------------------------------------------------------------------------------------------------- ----------- ----------
Traceback (most recent call last):
  File "/usr/bin/PyFunceble", line 11, in <module>
    load_entry_point('PyFunceble==3.3.3', 'console_scripts', 'pyfunceble')()
  File "/cygdrive/c/Users/imree/Desktop/Skrivebordsbilder/PyFunceble-greier/PyFunceble/PyFunceble/cli/__init__.py", line 1209, in tool
    raise exception
  File "/cygdrive/c/Users/imree/Desktop/Skrivebordsbilder/PyFunceble-greier/PyFunceble/PyFunceble/cli/__init__.py", line 1201, in tool
    generate_all_results_only=args.generate_all_files_from_database,
  File "/cygdrive/c/Users/imree/Desktop/Skrivebordsbilder/PyFunceble-greier/PyFunceble/PyFunceble/cli/dispatcher.py", line 132, in __init__
    file_path, generate_results_only, generate_all_results_only
  File "/cygdrive/c/Users/imree/Desktop/Skrivebordsbilder/PyFunceble-greier/PyFunceble/PyFunceble/cli/dispatcher.py", line 183, in dispatch_file_test
    PyFunceble.core.File(file_path, "domain").run_test()
  File "/cygdrive/c/Users/imree/Desktop/Skrivebordsbilder/PyFunceble-greier/PyFunceble/PyFunceble/core/file.py", line 655, in run_test
    self.__test_line(line)
  File "/cygdrive/c/Users/imree/Desktop/Skrivebordsbilder/PyFunceble-greier/PyFunceble/PyFunceble/core/file.py", line 538, in __test_line
    subject, ignore_inactive_db_check=ignore_inactive_db_check
  File "/cygdrive/c/Users/imree/Desktop/Skrivebordsbilder/PyFunceble-greier/PyFunceble/PyFunceble/core/file.py", line 489, in __run_single_test
    result = self.test(subject)
  File "/cygdrive/c/Users/imree/Desktop/Skrivebordsbilder/PyFunceble-greier/PyFunceble/PyFunceble/core/file.py", line 314, in test
    filename=self.file,
  File "/cygdrive/c/Users/imree/Desktop/Skrivebordsbilder/PyFunceble-greier/PyFunceble/PyFunceble/status/availability/domain_and_ip.py", line 69, in __init__
    subject, filename=filename, whois_db=whois_db, inactive_db=inactive_db
  File "/cygdrive/c/Users/imree/Desktop/Skrivebordsbilder/PyFunceble-greier/PyFunceble/PyFunceble/status/gatherer_base.py", line 101, in __init__
    self.status = Status(self.subject)
  File "/cygdrive/c/Users/imree/Desktop/Skrivebordsbilder/PyFunceble-greier/PyFunceble/PyFunceble/status/status.py", line 148, in __init__
    "whois_server": PyFunceble.lookup.Referer(self.subject).get()[-1],
  File "/cygdrive/c/Users/imree/Desktop/Skrivebordsbilder/PyFunceble-greier/PyFunceble/PyFunceble/lookup/referer.py", line 260, in get
    resolved_referer = PyFunceble.DNSLOOKUP.a_record(referer)
  File "/cygdrive/c/Users/imree/Desktop/Skrivebordsbilder/PyFunceble-greier/PyFunceble/PyFunceble/lookup/dns.py", line 260, in a_record
    result = [str(x) for x in self.resolver.resolve(subject, "A", tcp=tcp)]
AttributeError: 'Resolver' object has no attribute 'resolve'
```

## Modifications under `.PyFunceble.yaml`

None that I'm aware of.

## Reproduction

1. Install PyFunceble through "Pure Python method"
2. Run `PyFunceble -v`
3. See that that command works as intended.
4. Run `PyFunceble -f [whatever filename]`
5. Receive the error shown above.

## Expected behavior
Running PyFunceble on local files should work.

## Screenshots
N/A

## Versions

**OS:** Windows 10 May 2020 Update + Cygwin 3.1.7
**Python Version:** 3.7.7
**PyFunceble Version:** 3.3.3

## Additional context

To the limited degree I understand Python error messages, this seems to me like a problem with PyFunceble itself for once, as opposed to my PC's convoluted Cygwin setup.

**Comment by DandelionSprout** [comment]
I can now confirm that this also happens when installing through "Pure Python method" in PowerShell 7.0.3 with Python 3.8.1.

**Comment by spirillen** [comment]
Thanks for your feedback, error report @DandelionSprout :+1: I know @funilrys is busy solving similar issues we have found in another branch when using SQL backend.

From my part, I'm glad to see some feedback to help improve the program, cheers

**Comment by funilrys** [comment]
Thanks a lot for the feedback @DandelionSprout! 

-----

Fixed with https://github.com/funilrys/PyFunceble/commit/024dc9223633dd18682826147359270e25b4883e.

**P.S: Help us, DO NOT close this issue manually. This issue is going to be closed automatically once https://github.com/funilrys/PyFunceble/commit/024dc9223633dd18682826147359270e25b4883e will be merged to master.**

**Comment by funilrys** [comment]
Closing so that I can keep track of what I still have to fix.
Feel free to test and reopen if not fixed or if necessary.
