### ISSUE TITLE
Using pip3 in Cygwin to install PyFunceble doesn't work

### ISSUE THREAD

**Issue by DandelionSprout** [funilrys/PyFunceble#126]
## Bug description

When using pip3 to install PyFunceble, running `PyFunceble` leads to `NameError: name 'CONFIG_DIRECTORY' is not defined`:

```
imree@ImresPC /cygdrive/c/Users/imree/Desktop/Skrivebordsbilder/PyFunceble-greier
$ pip3 install --user PyFunceble
Collecting PyFunceble
  Using cached PyFunceble-3.3.3-py3-none-any.whl (321 kB)
Requirement already satisfied: dnspython in /usr/lib/python3.7/site-packages/dnspython-1.16.0-py3.7.egg (from PyFunceble) (1.16.0)
Requirement already satisfied: inflection in /home/imree/.local/lib/python3.7/site-packages (from PyFunceble) (0.5.1)
Requirement already satisfied: PyYAML in /usr/lib/python3.7/site-packages/PyYAML-5.3.1-py3.7-cygwin-3.1.7-x86_64.egg (from PyFunceble) (5.3.1)
Requirement already satisfied: alembic in /home/imree/.local/lib/python3.7/site-packages (from PyFunceble) (1.4.3)
Requirement already satisfied: python-dotenv in /usr/lib/python3.7/site-packages (from PyFunceble) (0.11.0)
Requirement already satisfied: requests<3 in /usr/lib/python3.7/site-packages (from PyFunceble) (2.24.0)
Requirement already satisfied: cryptography in /usr/lib/python3.7/site-packages (from PyFunceble) (3.0)
Requirement already satisfied: PyMySQL in /usr/lib/python3.7/site-packages/PyMySQL-0.9.3-py3.7.egg (from PyFunceble) (0.9.3)
Requirement already satisfied: python-box[all] in /usr/lib/python3.7/site-packages (from PyFunceble) (5.1.1)
Requirement already satisfied: setuptools in /usr/lib/python3.7/site-packages (from PyFunceble) (46.4.0)
Requirement already satisfied: sqlalchemy in /home/imree/.local/lib/python3.7/site-packages (from PyFunceble) (1.3.19)
Requirement already satisfied: domain2idna in /usr/lib/python3.7/site-packages/domain2idna-1.9.1-py3.7.egg (from PyFunceble) (1.9.1)
Requirement already satisfied: colorama in /usr/lib/python3.7/site-packages/colorama-0.4.3-py3.7.egg (from PyFunceble) (0.4.3)
Requirement already satisfied: python-dateutil in /home/imree/.local/lib/python3.7/site-packages (from alembic->PyFunceble) (2.8.1)
Requirement already satisfied: python-editor>=0.3 in /home/imree/.local/lib/python3.7/site-packages (from alembic->PyFunceble) (1.0.4)
Requirement already satisfied: Mako in /home/imree/.local/lib/python3.7/site-packages (from alembic->PyFunceble) (1.1.3)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/lib/python3.7/site-packages (from requests<3->PyFunceble) (3.0.4)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/lib/python3.7/site-packages (from requests<3->PyFunceble) (1.25.10)
Requirement already satisfied: idna<3,>=2.5 in /usr/lib/python3.7/site-packages (from requests<3->PyFunceble) (2.10)
Requirement already satisfied: six>=1.4.1 in /usr/lib/python3.7/site-packages (from cryptography->PyFunceble) (1.15.0)
Requirement already satisfied: cffi!=1.11.3,>=1.8 in /usr/lib/python3.7/site-packages (from cryptography->PyFunceble) (1.14.0)
Requirement already satisfied: toml; extra == "all" in /usr/lib/python3.7/site-packages/toml-0.10.0-py3.7.egg (from python-box[all]->PyFunceble) (0.10.0)
Requirement already satisfied: ruamel.yaml; extra == "all" in /usr/lib/python3.7/site-packages/ruamel.yaml-0.16.10-py3.7.egg (from python-box[all]->PyFunceble) (0.16.10)
Requirement already satisfied: msgpack; extra == "all" in /usr/lib/python3.7/site-packages (from python-box[all]->PyFunceble) (1.0.0)
Requirement already satisfied: MarkupSafe>=0.9.2 in /home/imree/.local/lib/python3.7/site-packages (from Mako->alembic->PyFunceble) (1.1.1)
Requirement already satisfied: pycparser in /usr/lib/python3.7/site-packages (from cffi!=1.11.3,>=1.8->cryptography->PyFunceble) (2.20)
Requirement already satisfied: ruamel.yaml.clib>=0.1.2 in /usr/lib/python3.7/site-packages/ruamel.yaml.clib-0.2.2-py3.7-cygwin-3.1.7-x86_64.egg (from ruamel.yaml; extra == "all"->python-box[all]->PyFunceble) (0.2.2)
Installing collected packages: PyFunceble
Successfully installed PyFunceble-3.3.3
WARNING: You are using pip version 20.2.2; however, version 20.2.3 is available.
You should consider upgrading via the '/usr/bin/python3.7 -m pip install --upgrade pip' command.

imree@ImresPC /cygdrive/c/Users/imree/Desktop/Skrivebordsbilder/PyFunceble-greier
$ PyFunceble
Traceback (most recent call last):
  File "/home/imree/.local/bin/PyFunceble", line 5, in <module>
    from PyFunceble.cli import tool
  File "/home/imree/.local/lib/python3.7/site-packages/PyFunceble/__init__.py", line 150, in <module>
    if not CONFIG_DIRECTORY.endswith(directory_separator):
NameError: name 'CONFIG_DIRECTORY' is not defined
```

## Modifications under `.PyFunceble.yaml`

None that I'm aware of.

## Reproduction

1) Delete all folders on the PC with the string "PyFunceble" in them.
2) Run `pip3 install --user PyFunceble`
3) Run `PyFunceble`

## Expected behavior
Installing PyFunceble through pip3 should work.

## Screenshots
N/A

## Versions

**OS:** Windows 10 May 2020 Update + Cygwin 3.1.7
**Python Version:** 3.7.7
**PyFunceble Version:** 3.3.3

## Additional context
None that I'm aware of.

**Comment by spirillen** [comment]
Can have some relation to <https://github.com/funilrys/PyFunceble/issues/83>

Could you please try to set `PYFUNCEBLE_CONFIG_DIR` and `PYFUNCEBLE_OUTPUT_LOCATION` before running pyfunceble?

more info on variables at <https://pyfunceble.readthedocs.io/en/master/components/environment-variables.html?highlight=PYFUNCEBLE_CONFIG_DIR#what-do-we-use-and-why>

**Comment by DandelionSprout** [comment]
I'll see if I have time to do so later tonight.

**Comment by funilrys** [comment]
Thanks a lot for the feedback @DandelionSprout! Do you mind giving me your current version of Cygwin?

-----

Fixed with https://github.com/funilrys/PyFunceble/commit/0bb5f60311192f56c80b810eeaed0ed5bb2a5fda.

**P.S: Help us, DO NOT close this issue manually. This issue is going to be closed automatically once https://github.com/funilrys/PyFunceble/commit/0bb5f60311192f56c80b810eeaed0ed5bb2a5fda will be merged to master.**

**Comment by DandelionSprout** [comment]
It was version 3.1.7 when I wrote the OP.

**Comment by funilrys** [comment]
Closing. Feel free to test and reopen if not fixed or if necessary.
