### ISSUE TITLE
Too many open files (-m)

### ISSUE THREAD

**Issue by spirillen** [funilrys/PyFunceble#129]
## Bug description
```python
Subject                                                                                              Status      HTTP Code 
---------------------------------------------------------------------------------------------------- ----------- ----------
Traceback (most recent call last):
  File "$HOME/miniconda/envs/pyfunceble-dev/bin/pyfunceble", line 8, in <module>
    sys.exit(tool())
  File "$HOME/miniconda/envs/pyfunceble-dev/lib/python3.9/site-packages/PyFunceble/cli/__init__.py", line 1222, in tool
    raise exception
  File "$HOME/miniconda/envs/pyfunceble-dev/lib/python3.9/site-packages/PyFunceble/cli/__init__.py", line 1207, in tool
    Dispatcher(
  File "$HOME/miniconda/envs/pyfunceble-dev/lib/python3.9/site-packages/PyFunceble/cli/dispatcher.py", line 131, in __init__
    self.dispatch_file_test(
  File "$HOME/miniconda/envs/pyfunceble-dev/lib/python3.9/site-packages/PyFunceble/cli/dispatcher.py", line 174, in dispatch_file_test
    PyFunceble.core.Multiprocess(file_path, "domain").run_test()
  File "$HOME/miniconda/envs/pyfunceble-dev/lib/python3.9/site-packages/PyFunceble/core/multiprocess.py", line 575, in run_test
    self.__run_multiprocess_test(shadow_file, manager, tracker=tracker)
  File "$HOME/miniconda/envs/pyfunceble-dev/lib/python3.9/site-packages/PyFunceble/core/multiprocess.py", line 428, in __run_multiprocess_test
    self.__start_process(
  File "$HOME/miniconda/envs/pyfunceble-dev/lib/python3.9/site-packages/PyFunceble/core/multiprocess.py", line 331, in __start_process
    process.start()
  File "$HOME/miniconda/envs/pyfunceble-dev/lib/python3.9/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "$HOME/miniconda/envs/pyfunceble-dev/lib/python3.9/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "$HOME/miniconda/envs/pyfunceble-dev/lib/python3.9/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
  File "$HOME/miniconda/envs/pyfunceble-dev/lib/python3.9/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "$HOME/miniconda/envs/pyfunceble-dev/lib/python3.9/multiprocessing/popen_fork.py", line 64, in _launch
    parent_r, child_w = os.pipe()
OSError: [Errno 24] Too many open files
```

## Modifications under `.PyFunceble.yaml`
None

## Reproduction
1. `pyfunceble -db --database-type mariadb --dns x.x.x.x  -m -f https://osint.digitalside.it/Threat-Intel/lists/latestdomains.txt`

Related to <https://github.com/FadeMind/hosts.extras/issues/45> to see what might be diff from the actually urlhaus list

## Expected behavior
Really :smiley: :smiling_imp: 

## Screenshots

![image](https://user-images.githubusercontent.com/44526987/96367815-58373100-1150-11eb-958b-cc5053f26c1b.png)

## Versions

**OS:** Kubuntu 20.04.1 conda 4.8.5
**Python Version:** 3.9.0
**PyFunceble Version:** pyfunceble 3.3.7.dev (Teal Blauwbok: Gander)

## Additional context
Haven't been digging a lot in this issue as it was about 4 in the morning when this occurred.

**Comment by funilrys** [comment]
Just wondering... How many cores does that machine have ?

**Comment by spirillen** [comment]
> Just wondering... How many cores does that machine have ?

Not sure I can count to many, let me use my fingers 1.. 2.. 3.. 4  :laughing:

**Comment by funilrys** [comment]
The new threading model should resolve this issue because I went away from the hard to manage multiprocessing.

**Comment by funilrys** [comment]
Closing, assuming that we are not going to meet this anymore in 4.x+. 

Please feel free to open if this issue happens again.
