### ISSUE TITLE
error when updating. 'pyfunceble' in section 'console_scripts' already exists

### ISSUE THREAD

**Issue by jawz101** [funilrys/PyFunceble#14]
```
user@computer:~/repos/PyFunceble$ . venv/bin/activate && pip3 install -e .
Obtaining file:///home/user/repos/PyFunceble
Collecting colorama>=0.3.9 (from PyFunceble-dev==0.133.1)
  Downloading https://files.pythonhosted.org/packages/4f/a6/728666f39bfff1719fc94c481890b2106837da9318031f71a8424b662e12/colorama-0.4.1-py2.py3-none-any.whl
Collecting domain2idna>=1.6.1 (from PyFunceble-dev==0.133.1)
  Using cached https://files.pythonhosted.org/packages/4e/27/b7336824583e26d3e33f7b6917c00e51b7c8a94bc1d4b78d6aa1eb9c7e8b/domain2idna-1.6.1-py3-none-any.whl
Collecting PyYAML>=3.13 (from PyFunceble-dev==0.133.1)
Collecting requests>=2.19.1 (from PyFunceble-dev==0.133.1)
  Using cached https://files.pythonhosted.org/packages/ff/17/5cbb026005115301a8fb2f9b0e3e8d32313142fe8b617070e7baad20554f/requests-2.20.1-py2.py3-none-any.whl
Collecting setuptools>=40.4.3 (from PyFunceble-dev==0.133.1)
  Using cached https://files.pythonhosted.org/packages/e7/16/da8cb8046149d50940c6110310983abb359bbb8cbc3539e6bef95c29428a/setuptools-40.6.2-py2.py3-none-any.whl
Collecting urllib3>=1.23 (from PyFunceble-dev==0.133.1)
  Using cached https://files.pythonhosted.org/packages/62/00/ee1d7de624db8ba7090d1226aebefab96a2c71cd5cfa7629d6ad3f61b79e/urllib3-1.24.1-py2.py3-none-any.whl
Collecting certifi>=2017.4.17 (from requests>=2.19.1->PyFunceble-dev==0.133.1)
  Downloading https://files.pythonhosted.org/packages/9f/e0/accfc1b56b57e9750eba272e24c4dddeac86852c2bebd1236674d7887e8a/certifi-2018.11.29-py2.py3-none-any.whl (154kB)
    100% |████████████████████████████████| 163kB 2.9MB/s 
Collecting chardet<3.1.0,>=3.0.2 (from requests>=2.19.1->PyFunceble-dev==0.133.1)
  Using cached https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl
Collecting idna<2.8,>=2.5 (from requests>=2.19.1->PyFunceble-dev==0.133.1)
  Using cached https://files.pythonhosted.org/packages/4b/2a/0276479a4b3caeb8a8c1af2f8e4355746a97fab05a372e4a2c6a6b876165/idna-2.7-py2.py3-none-any.whl
Installing collected packages: colorama, setuptools, domain2idna, PyYAML, certifi, chardet, idna, urllib3, requests, PyFunceble-dev
  Found existing installation: PyFunceble-dev 0.127.5
Exception:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 360, in run
    prefix=options.prefix_path,
  File "/usr/lib/python3/dist-packages/pip/req/req_set.py", line 778, in install
    requirement.uninstall(auto_confirm=True)
  File "/usr/lib/python3/dist-packages/pip/req/req_install.py", line 734, in uninstall
    FakeFile(dist.get_metadata_lines('entry_points.txt'))
  File "/usr/lib/python3.6/configparser.py", line 763, in readfp
    self.read_file(fp, source=filename)
  File "/usr/lib/python3.6/configparser.py", line 718, in read_file
    self._read(f, source)
  File "/usr/lib/python3.6/configparser.py", line 1092, in _read
    fpname, lineno)
configparser.DuplicateOptionError: While reading from '<???>' [line  3]: option 'pyfunceble' in section 'console_scripts' already exists

```

**Comment by jawz101** [comment]
and in the PyFunceble_dev.egg-info/entry_points.txt file it just keeps appending `PyFunceble = PyFunceble:_command_line`

```
[console_scripts]
PyFunceble = PyFunceble:_command_line
pyfunceble = PyFunceble:_command_line
```

**Comment by funilrys** [comment]
Hi, It's not against you but I do not have the time to answer this directly (yet). Will explain and clarify this later this afternoon (Berlin Time).

Have a nice day/night!

Cheers,
Nissar

**Comment by jawz101** [comment]
Ok... now I'm at these commands:
```
$ cd PyFunceble
$ git fetch origin && git merge origin/dev
$ . venv/bin/activate && pip3 install --upgrade git+https://github.com/funilrys/PyFunceble.git@dev#egg=PyFunceble
```
```
(venv) user@computer:~/repos/PyFunceble$ PyFunceble -f /home/user/Downloads/easyprivacy.txt
A configuration key is missing.
Try to merge upstream configuration file into /home/user/repos/PyFunceble/.PyFunceble.yaml ? [y/n] 
```

so now I do this:
```
$ cd PyFunceble
$ git fetch origin && git merge origin/dev
$ . venv/bin/activate && pip3 install --upgrade git+https://github.com/funilrys/PyFunceble.git@dev#egg=PyFunceble
$ rm PyFunceble.yaml
```

**Comment by funilrys** [comment]
So, sorry for the waiting time. 
You pointed one thing: The documentation is not complete.

Let's fix that lack here before updating the documentation.

If you installed with `pip install -e .` then a simple update of the repository will update your version of PyFunceble automatically (thanks to pip). Which means you don't need to rerun `pip install -e .`.

That also means that you only have to fix the `git` merge issue then pip will rest for you.

For your merge issue. I'll suggest:

```
$ cp iana-domains-db.json iana-domains-db.json.bak
$ cp  public-suffix.json public-suffix.json.bak
$ git stash && git fetch origin && git merge origin/dev
$ mv iana-domains-db.json.bak iana-domains-db.json
$ mv  public-suffix.json.bak public-suffix.json
```

If you installed with `pip install git+https://github.com/funilrys/PyFunceble.git@dev#egg=PyFunceble` then you will only have to do `pip install --upgrade git+https://github.com/funilrys/PyFunceble.git@dev#egg=PyFunceble` to update. No need to handle anything else.

# About the "merge upstream" function

```
KeyError
```

That's what you got before I introduced this feature. It was quite annoying. 

Indeed, you always had to delete your configuration file (after each update) then run PyFunceble to get the most recent version of the configuration file. It was a good idea but in between, you lost everything you set up yourself.

So the merge function simply adds the nonpresent keys but also keep everything you set up before.

If you don't want the system to do it for you, simply answer `N` and delete or update the `.PyFunceble.yaml` file yourself.

I hope I did answer everything. If something is still not clear, let me know, I'll be glad to take the time to clarify or help.

Have a nice day/night.

Cheers,
Nissar

**Comment by jawz101** [comment]
Thanks.  You did.

It's 2:48PM Saturday afternoon here :)

**Comment by jayvdb** [comment]
This issue still exists when pyfunceble is installed using setuptools, and breaks "everything" else installed in the virtualenv that uses setuptools/pkg_resources/importlib_metadata.

e.g. pytest failing
```py
Traceback (most recent call last):
  File "/usr/lib64/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.7/site-packages/pytest.py", line 101, in <module>
    raise SystemExit(pytest.main())
  File "/usr/lib/python3.7/site-packages/_pytest/config/__init__.py", line 71, in main
    config = _prepareconfig(args, plugins)
  File "/usr/lib/python3.7/site-packages/_pytest/config/__init__.py", line 216, in _prepareconfig
    pluginmanager=pluginmanager, args=args
  File "/usr/lib/python3.7/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/usr/lib/python3.7/site-packages/pluggy/manager.py", line 92, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/usr/lib/python3.7/site-packages/pluggy/manager.py", line 86, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/usr/lib/python3.7/site-packages/pluggy/callers.py", line 203, in _multicall
    gen.send(outcome)
  File "/usr/lib/python3.7/site-packages/_pytest/helpconfig.py", line 89, in pytest_cmdline_parse
    config = outcome.get_result()
  File "/usr/lib/python3.7/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/usr/lib/python3.7/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/usr/lib/python3.7/site-packages/_pytest/config/__init__.py", line 733, in pytest_cmdline_parse
    self.parse(args)
  File "/usr/lib/python3.7/site-packages/_pytest/config/__init__.py", line 940, in parse
    self._preparse(args, addopts=addopts)
  File "/usr/lib/python3.7/site-packages/_pytest/config/__init__.py", line 882, in _preparse
    self._consider_importhook(args)
  File "/usr/lib/python3.7/site-packages/_pytest/config/__init__.py", line 830, in _consider_importhook
    self._mark_plugins_for_rewrite(hook)
  File "/usr/lib/python3.7/site-packages/_pytest/config/__init__.py", line 852, in _mark_plugins_for_rewrite
    for name in _iter_rewritable_modules(package_files):
  File "/usr/lib/python3.7/site-packages/_pytest/config/__init__.py", line 626, in _iter_rewritable_modules
    for fn in package_files:
  File "/usr/lib/python3.7/site-packages/_pytest/config/__init__.py", line 848, in <genexpr>
    if any(ep.group == "pytest11" for ep in dist.entry_points)
  File "/usr/lib/python3.7/site-packages/importlib_metadata/__init__.py", line 226, in entry_points
    return EntryPoint._from_text(self.read_text('entry_points.txt'))
  File "/usr/lib/python3.7/site-packages/importlib_metadata/__init__.py", line 109, in _from_text
    config.read_string(text)
  File "/usr/lib64/python3.7/configparser.py", line 722, in read_string
    self.read_file(sfile, source)
  File "/usr/lib64/python3.7/configparser.py", line 717, in read_file
    self._read(f, source)
  File "/usr/lib64/python3.7/configparser.py", line 1091, in _read
    fpname, lineno)
configparser.DuplicateOptionError: While reading from '<string>' [line  3]: option 'pyfunceble' in section 'console_scripts' already exists
```

Why are there two entries in https://github.com/funilrys/PyFunceble/blob/master/setup.py#L166 ?

**Comment by funilrys** [comment]
Hi @jayvdb, first you should avoid `python setup.py install` if you one day wish to uninstall it. In most case `pip install -e .` works.

Also, I'm not using pytest ... Please try from the dev branch as it will be merged in the coming days/week.

Cheer!

**Comment by jayvdb** [comment]
I am using setup.py as part of distro packaging
https://build.opensuse.org/package/show/home:jayvdb:py-new/python-PyFunceble

The dev branch also has the same problem https://github.com/funilrys/PyFunceble/blob/dev/setup.py#L193

Note this breaks any use of pkg_resources after installation, even unrelated to pyfunceble ; it breaks *other* packages installed into the same site-packages that pyfunceble is installed into.  pytest is just one example.

**Comment by funilrys** [comment]
@jawz101, please submit a new issue. I'll look into this.
