### ISSUE TITLE
convert string to float (4.x Alpha)

### ISSUE THREAD

**Issue by spirillen** [funilrys/PyFunceble#140]
## Bug description
`Fatal Error: could not convert string to float:`

## Modifications under `.PyFunceble.yaml`

None

## Reproduction

1. `pyfunceble -h -a -dbr 0 -d mypdns.org --mining`

Fatal Error: could not convert string to float: '14-mar-2021'
Fatal Error: could not convert string to float: '1609628400.01610492400.0'
Fatal Error: could not convert string to float: '07-jun-2022'

## Expected behavior
```
Subject                                                                                              Status      Source     Expiration Date   HTTP Code  Checker      
---------------------------------------------------------------------------------------------------- ----------- ---------- ----------------- ---------- -------------
mypdns.org                                                                                           ACTIVE      WHOIS      04-oct-2028       Unknown    AVAILABILITY
```

However I would have expected the actually HTTP code

## Versions

**OS:** Ubuntu 20.04 Focal + Conda
**Python Version:** 3.9.0
**PyFunceble Version:** 4.0.0a6.dev (Blue Duckling)

## Additional context
```
pyfunceble -h -a -dbr 0 -d www.mypdns.org --mining --logging-level debug

[2020-12-21 10:43:54,763::DEBUG::/$HOME/miniconda/envs/pyfunceble4/lib/python3.9/site-packages/PyFunceble/cli/system/integrator.py:161@start](PID140504402646848:MainThread): Given arguments:
Namespace(domains=['www.mypdns.org'], urls=None, files=None, url_files=None, cli_decoding__adblock=False, cli_decoding__adblock_aggressive=False, cli_testing__complements=False, cli_testing__file_filter=None, cli_testing__mining=True, cli_testing__autocontinue=False, cli_testing__cooldown_time=None, cli_testing__local_network=False, lookup__http_status_code=False, lookup__special=False, lookup__whois=False, lookup__netinfo=False, lookup__dns=False, lookup__reputation=False, cli_testing__testing_mode__reputation=False, cli_decoding__rpz=False, cli_testing__testing_mode__syntax=False, lookup__timeout=None, user_agent__custom=None, verify_ssl_certificate=False, cli_decoding__wildcard=False, dns__server=None, dns__protocol=None, cli_testing__inactive_db=False, cli_testing__db_type=None, cli_testing__days_between__db_retest=0, cli_testing__days_between__db_clean=None, cli_testing__whois_db=None, cli_testing__display_mode__all=True, cli_testing__display_mode__execution_time=False, cli_testing__sorting_mode__hierarchical=False, cli_testing__file_generation__hosts=True, cli_testing__hosts_ip=None, cli_testing__file_generation__no_file=False, cli_testing__file_generation__unified_results=False, cli_testing__display_mode__percentage=False, cli_testing__file_generation__plain=False, cli_testing__display_mode__dots=False, cli_testing__display_mode__quiet=False, share_logs=False, cli_testing__display_mode__simple=False, cli_testing__max_workers=None, cli_testing__ci__max_exec_minutes=None, cli_testing__ci__active=False, cli_testing__ci__branch=None, cli_testing__ci__distribution_branch=None, cli_testing__ci__command=None, cli_testing__ci__end_command=None, cli_testing__ci__commit_message=None, cli_testing__ci__end_commit_message=None, debug__active=False, debug__level='debug')
[2020-12-21 10:43:54,763::INFO::/$HOME/miniconda/envs/pyfunceble4/lib/python3.9/site-packages/PyFunceble/cli/system/integrator.py:115@inject_into_config](PID140504402646848:MainThread): Started to inject arguments info configuration.
[2020-12-21 10:43:54,783::DEBUG::/$HOME/miniconda/envs/pyfunceble4/lib/python3.9/site-packages/PyFunceble/cli/system/integrator.py:143@inject_into_config](PID140504402646848:MainThread): Injected into config: {'cli_testing': {'mining': True, 'display_mode': {'all': True}, 'file_generation': {'hosts': False}}, 'debug': {'level': 'debug'}}
[2020-12-21 10:43:54,784::INFO::/$HOME/miniconda/envs/pyfunceble4/lib/python3.9/site-packages/PyFunceble/cli/system/integrator.py:147@inject_into_config](PID140504402646848:MainThread): Finished to inject arguments info configuration.

██████╗ ██╗   ██╗███████╗██╗   ██╗███╗   ██╗ ██████╗███████╗██████╗ ██╗     ███████╗
██╔══██╗╚██╗ ██╔╝██╔════╝██║   ██║████╗  ██║██╔════╝██╔════╝██╔══██╗██║     ██╔════╝
██████╔╝ ╚████╔╝ █████╗  ██║   ██║██╔██╗ ██║██║     █████╗  ██████╔╝██║     █████╗
██╔═══╝   ╚██╔╝  ██╔══╝  ██║   ██║██║╚██╗██║██║     ██╔══╝  ██╔══██╗██║     ██╔══╝
██║        ██║   ██║     ╚██████╔╝██║ ╚████║╚██████╗███████╗██████╔╝███████╗███████╗
╚═╝        ╚═╝   ╚═╝      ╚═════╝ ╚═╝  ╚═══╝ ╚═════╝╚══════╝╚═════╝ ╚══════╝╚══════╝

[2020-12-21 10:43:54,787::INFO::/$HOME/miniconda/envs/pyfunceble4/lib/python3.9/site-packages/PyFunceble/cli/threads/base.py:276@start](PID140504402646848:MainThread): Started underlying thread of 'pyfunceble_migrator' (daemon=False).
[2020-12-21 10:43:54,865::INFO::/$HOME/miniconda/envs/pyfunceble4/lib/python3.9/site-packages/PyFunceble/cli/threads/migrator.py:279@target](PID140504350844672:pyfunceble_migrator): Submitted 'hashes_file_cleanup_target'
[2020-12-21 10:43:54,906::INFO::/$HOME/miniconda/envs/pyfunceble4/lib/python3.9/site-packages/PyFunceble/cli/threads/migrator.py:279@target](PID140504350844672:pyfunceble_migrator): Submitted 'json2csv_inactive_target'
[2020-12-21 10:43:54,943::INFO::/$HOME/miniconda/envs/pyfunceble4/lib/python3.9/site-packages/PyFunceble/cli/threads/migrator.py:232@hashes_file_cleanup_target](PID140504342189824:pyfunceble_migrator_0): Stopped hashes_file_cleanup_target. File does not exist.
[2020-12-21 10:43:54,954::INFO::/$HOME/miniconda/envs/pyfunceble4/lib/python3.9/site-packages/PyFunceble/cli/threads/migrator.py:279@target](PID140504350844672:pyfunceble_migrator): Submitted 'json2csv_whois_target'
[2020-12-21 10:43:54,964::INFO::/$HOME/miniconda/envs/pyfunceble4/lib/python3.9/site-packages/PyFunceble/cli/threads/migrator.py:128@json2csv_inactive_target](PID140504333797120:pyfunceble_migrator_1): Stopped json2csv_inactive_target. File does not exist.
[2020-12-21 10:43:54,985::INFO::/$HOME/miniconda/envs/pyfunceble4/lib/python3.9/site-packages/PyFunceble/cli/threads/migrator.py:279@target](PID140504350844672:pyfunceble_migrator): Submitted 'mariadb_file_and_status_target'
[2020-12-21 10:43:54,991::INFO::/$HOME/miniconda/envs/pyfunceble4/lib/python3.9/site-packages/PyFunceble/cli/threads/migrator.py:153@json2csv_whois_target](PID140504342189824:pyfunceble_migrator_0): Stopped json2csv_whois_target. File does not exist.
[2020-12-21 10:43:55,012::INFO::/$HOME/miniconda/envs/pyfunceble4/lib/python3.9/site-packages/PyFunceble/cli/threads/migrator.py:279@target](PID140504350844672:pyfunceble_migrator): Submitted 'mariadb_whois_record_idna_subject_target'
[2020-12-21 10:43:55,018::INFO::/$HOME/miniconda/envs/pyfunceble4/lib/python3.9/site-packages/PyFunceble/cli/threads/migrator.py:279@target](PID140504350844672:pyfunceble_migrator): Submitted 'mining_file_cleanup_target'
[2020-12-21 10:43:55,023::INFO::/$HOME/miniconda/envs/pyfunceble4/lib/python3.9/site-packages/PyFunceble/cli/threads/migrator.py:207@mariadb_file_and_status_target](PID140504333797120:pyfunceble_migrator_1): Stopped mariadb_file_and_status_target. Not authorized.
[2020-12-21 10:43:55,034::INFO::/$HOME/miniconda/envs/pyfunceble4/lib/python3.9/site-packages/PyFunceble/cli/threads/migrator.py:179@mariadb_whois_record_idna_subject_target](PID140504342189824:pyfunceble_migrator_0): Stopped mariadb_whois_record_idna_subject_target. Not authorized.
[2020-12-21 10:43:55,040::INFO::/$HOME/miniconda/envs/pyfunceble4/lib/python3.9/site-packages/PyFunceble/cli/threads/migrator.py:257@mining_file_cleanup_target](PID140504333797120:pyfunceble_migrator_1): Stopped hashes_file_cleanup_target. File does not exist.
[2020-12-21 10:43:55,097::INFO::/$HOME/miniconda/envs/pyfunceble4/lib/python3.9/site-packages/PyFunceble/cli/threads/base.py:276@start](PID140504402646848:MainThread): Started underlying thread of 'pyfunceble_tester' (daemon=True).
[2020-12-21 10:43:55,159::INFO::/$HOME/miniconda/envs/pyfunceble4/lib/python3.9/site-packages/PyFunceble/cli/threads/base.py:276@start](PID140504402646848:MainThread): Started underlying thread of 'pyfunceble_producer' (daemon=True).
[2020-12-21 10:43:55,200::INFO::/$HOME/miniconda/envs/pyfunceble4/lib/python3.9/site-packages/PyFunceble/cli/threads/base.py:276@start](PID140504402646848:MainThread): Started underlying thread of 'pyfunceble_mining' (daemon=True).
[2020-12-21 10:44:02,830::CRITICAL::/$HOME/miniconda/envs/pyfunceble4/lib/python3.9/site-packages/PyFunceble/cli/system/launcher.py:708@start](PID140504402646848:MainThread): Fatal error.
Traceback (most recent call last):
  File "/$HOME/miniconda/envs/pyfunceble4/lib/python3.9/site-packages/PyFunceble/cli/system/launcher.py", line 698, in start
    PyFunceble.checker.utils.whois.get_whois_dataset_object().cleanup()
  File "/$HOME/miniconda/envs/pyfunceble4/lib/python3.9/site-packages/PyFunceble/dataset/whois/csv.py", line 164, in cleanup
    for row in self.get_content():
  File "/$HOME/miniconda/envs/pyfunceble4/lib/python3.9/site-packages/PyFunceble/dataset/whois/csv.py", line 99, in get_content
    row["epoch"] = float(row["epoch"])
ValueError: could not convert string to float: 'kojywvexdq.com'
Fatal Error: could not convert string to float: 'kojywvexdq.com'
```

**Comment by spirillen** [comment]
```
grep -nri 'kojywvexdq.com'
whois.csv:1560:kojywvexdq.com,kojywvexdq.com,01-jun-2021,1622498400.0
```

**Comment by funilrys** [comment]
Closing. Feel free to reopen if you still meet this issue with the latest version.

**Comment by spirillen** [comment]
Confirmed fixed
