### ISSUE TITLE
Appkit path guessing not working

### ISSUE THREAD

**Issue by speedmann** [funilrys/PyFunceble#15]
**Describe the bug**
AppKit for macos not working or even needed.

As far as i can see, appkit python module is used to figure out what the config directory on macos should be. I do not get why this needs to be any different from what linux does, so i changed line 108 to

`if system().lower() == "linux" or system().lower() == "darwin":`

Works flawlessly

**Modifications under `.PyFunceble.yaml`**
nothing

**To Reproduce**
1. python setup.py install
2. pyfunceble google.de

**Expected behavior**
Working script telling me google.de is valid domain

**Screenshots**
srsly? Screenshots of a terminal?
```$ ./pyfunceble google.de
Traceback (most recent call last):
  File "./pyfunceble", line 11, in <module>
    load_entry_point('PyFunceble==1.0.0', 'console_scripts', 'pyfunceble')()
  File "/Users/sebastian/.pyenv/versions/funceble/lib/python3.6/site-packages/pkg_resources/__init__.py", line 487, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Users/sebastian/.pyenv/versions/funceble/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2728, in load_entry_point
    return ep.load()
  File "/Users/sebastian/.pyenv/versions/funceble/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2346, in load
    return self.resolve()
  File "/Users/sebastian/.pyenv/versions/funceble/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2352, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Users/sebastian/.pyenv/versions/funceble/lib/python3.6/site-packages/PyFunceble-1.0.0-py3.6.egg/PyFunceble/__init__.py", line 141, in <module>
    from AppKit import (  # pylint: disable=import-error
ModuleNotFoundError: No module named 'AppKit'
```

**Versions (please complete the following information):**
 - OS: macos mojave
 - Python Version: 3.6.7
 - PyFunceble Version: master

**Additional context**

**Comment by funilrys** [comment]
Hi @speedmann, welcome here and thanks for submitting this.

As I do not have a mac, I wrote the code theoretically. You normally need PyObjC.

Can you stash your changes and retry with the following:

```
$ pip3 install PyObjC
$ PyFunceble -d github.com
```

If it is working I'll add PyObjC to the dependencies for the Mac users and will release a new version with the patch.

Thanks in advance for the help.

Have a good night.

Cheers,
Nissar

**Comment by funilrys** [comment]
Implementation of your fix introduced with https://github.com/funilrys/PyFunceble/commit/134ebc8fff1b180829d08f665efe424e0c6cf7f7.

P.S: Please DO NOT close this issue manually. This issue is gonna be closed automatically once https://github.com/funilrys/PyFunceble/commit/134ebc8fff1b180829d08f665efe424e0c6cf7f7 will be merged to master.

**Comment by speedmann** [comment]
Thank you for fixing this. Works fine now
