### ISSUE TITLE
--dns-protocol https fails

### ISSUE THREAD

**Issue by spirillen** [funilrys/PyFunceble#160]
## Bug description
```python
exception calling callback for <Future at 0x7fcad65017f0 state=finished raised SSLError>

Traceback (most recent call last):

  File "/home/travis/miniconda/envs/test-environment/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen

    httplib_response = self._make_request(

  File "/home/travis/miniconda/envs/test-environment/lib/python3.9/site-packages/urllib3/connectionpool.py", line 382, in _make_request

    self._validate_conn(conn)

  File "/home/travis/miniconda/envs/test-environment/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn

    conn.connect()

  File "/home/travis/miniconda/envs/test-environment/lib/python3.9/site-packages/urllib3/connection.py", line 464, in connect

    _match_hostname(cert, self.assert_hostname or server_hostname)

  File "/home/travis/miniconda/envs/test-environment/lib/python3.9/site-packages/urllib3/connection.py", line 508, in _match_hostname

    match_hostname(cert, asserted_hostname)

  File "/home/travis/miniconda/envs/test-environment/lib/python3.9/ssl.py", line 420, in match_hostname

    raise CertificateError("hostname %r "

ssl.SSLCertVerificationError: ("hostname '136.144.215.158' doesn't match 'doh.powerdns.org'",)
```

<https://travis-ci.com/github/dns-test/PyFunceble-Sandboxed/jobs/464806396>

Sandbox <https://github.com/dns-test/PyFunceble-Sandboxed/tree/alpha_test_adblock>

## Modifications under `.PyFunceble.yaml`

None

## Reproduction

```bash
pyfunceble --ci -a --database-type mariadb -ex -w $(nproc --ignore=2) --adblock -f 'https://raw.githubusercontent.com/easylist/easylist/master/easyprivacy/easyprivacy_trackingservers.txt' 'https://raw.githubusercontent.com/easylist/easylist/master/easylist_cookie/easylist_cookie_general_hide.txt' 'https://raw.githubusercontent.com/easylist/easylist/master/fanboy-addon/fanboy_annoyance_specific_block.txt' --ci-branch "${TRAVIS_BRANCH}" --ci-distribution-branch "${TRAVIS_BRANCH}" -dbr 0 --dns doh.powerdns.org --dns-protocol HTTPS --dots --share-logs
```

## Expected behavior
<https://travis-ci.com/github/dns-test/PyFunceble-Sandboxed/jobs/464806395>

## Screenshots
![image](https://user-images.githubusercontent.com/44526987/103151278-d3cee300-477c-11eb-80de-211c0c4db8bf.png)

## Versions

**OS:** Ubuntu Focal + Conda
**Python Version:** 3.9.1
**PyFunceble Version:** pyfunceble 4.0.0a27.dev (Blue Duckling)

**Comment by spirillen** [comment]
Test parsed

https://travis-ci.com/github/dns-test/PyFunceble-Sandboxed/builds/210608136

**Comment by spirillen** [comment]
Just tested that the values `UDP`, `TCP`, `HTTPS` and `TLS` They are CaseSensitive, I think we should consider making them CaseInSensitive in at least the Beta release.
