### ISSUE TITLE
sql connection lost

### ISSUE THREAD

**Issue by spirillen** [funilrys/PyFunceble#162]
**Is your feature request related to a problem? Please describe.**
Append a reconnect/retry to the sql

**Describe the solution you'd like**
```
bigsexvideos.net                                                                                     ACTIVE      WHOIS      03-oct-2021       Unknown    AVAILABILITY 
/home/spirillen/miniconda/envs/pyfunceble4/lib/python3.9/site-packages/sqlalchemy/engine/default.py:409: SAWarning: Exception attempting to detect unicode returns: OperationalError("(pymysql.err.OperationalError) (2013, 'Lost connection to MySQL server during query ([Errno 104] Connection reset by peer)')")
  util.warn
```
With this we can minimize lost results, in case the DB is to busy or what have made it temponary unavailble, it could also be as simple as a security update of the DB, reboot etc.

In addition we should add a short wait like x seconds until test continues

**Describe alternatives you've considered**

**Additional context**

**Comment by spirillen** [comment]
TEST FAILED

```bash
./pyfunceble4.sh https://gitlab.com/ZeroDot1/CoinBlockerLists/-/raw/master/hosts
        I'm your hungry cheese missing a piece...
        Are you ready to go hunting the red pills
        so we can hunt down evil ghosts

        Are you ready to start?

        loading kacman...
Enter output directory for test results: /tmp/pyfunceble4/1156
Which version of PyFunceble would you like to use?: pyfunceble4: pyfunceble4
Enter any custom test string: --share-logs -dbr 6 -ex --dns 192.168.1.104:53 -w 6 -a --database-type mariadb --no-files --local
Would you like to use your default pyfunceble enviroment
  /$HOME/miniconda/envs/pyfunceble4?: [Y/n] Y
Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... done

# All requested packages already installed.

pyfunceble 4.0.0a38.dev (Blue Duckling)
uhb-whitelist 3.25.0
```

```python
01.easyx.cc                                                                                          INACTIVE    STDLOOKUP  Unknown           Unknown    AVAILABILITY 
Exception during reset or similar
Traceback (most recent call last):
  File "/$HOME/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 749, in _rollback_impl
    self.engine.dialect.do_rollback(self.connection)
  File "/$HOME/.local/lib/python3.9/site-packages/sqlalchemy/dialects/mysql/base.py", line 2496, in do_rollback
    dbapi_connection.rollback()
  File "/$HOME/.local/lib/python3.9/site-packages/pymysql/connections.py", line 431, in rollback
    self._execute_command(COMMAND.COM_QUERY, "ROLLBACK")
  File "/$HOME/.local/lib/python3.9/site-packages/pymysql/connections.py", line 742, in _execute_command
    raise err.InterfaceError(0, '')
pymysql.err.InterfaceError: (0, '')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/$HOME/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 697, in _finalize_fairy
    fairy._reset(pool)
  File "/$HOME/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 891, in _reset
    self._reset_agent.rollback()
  File "/$HOME/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1751, in rollback
    self._do_rollback()
  File "/$HOME/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1789, in _do_rollback
    self.connection._rollback_impl()
  File "/$HOME/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 751, in _rollback_impl
    self._handle_dbapi_exception(e, None, None, None, None)
  File "/$HOME/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1510, in _handle_dbapi_exception
    util.raise_(
  File "/$HOME/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/$HOME/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 749, in _rollback_impl
    self.engine.dialect.do_rollback(self.connection)
  File "/$HOME/.local/lib/python3.9/site-packages/sqlalchemy/dialects/mysql/base.py", line 2496, in do_rollback
    dbapi_connection.rollback()
  File "/$HOME/.local/lib/python3.9/site-packages/pymysql/connections.py", line 431, in rollback
    self._execute_command(COMMAND.COM_QUERY, "ROLLBACK")
  File "/$HOME/.local/lib/python3.9/site-packages/pymysql/connections.py", line 742, in _execute_command
    raise err.InterfaceError(0, '')
sqlalchemy.exc.InterfaceError: (pymysql.err.InterfaceError) (0, '')
(Background on this error at: http://sqlalche.me/e/13/rvf5)
Exception during reset or similar
Traceback (most recent call last):
  File "/$HOME/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 749, in _rollback_impl
    self.engine.dialect.do_rollback(self.connection)
  File "/$HOME/.local/lib/python3.9/site-packages/sqlalchemy/dialects/mysql/base.py", line 2496, in do_rollback
    dbapi_connection.rollback()
  File "/$HOME/.local/lib/python3.9/site-packages/pymysql/connections.py", line 431, in rollback
    self._execute_command(COMMAND.COM_QUERY, "ROLLBACK")
  File "/$HOME/.local/lib/python3.9/site-packages/pymysql/connections.py", line 742, in _execute_command
    raise err.InterfaceError(0, '')
pymysql.err.InterfaceError: (0, '')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/$HOME/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 697, in _finalize_fairy
    fairy._reset(pool)
  File "/$HOME/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 891, in _reset
    self._reset_agent.rollback()
  File "/$HOME/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1751, in rollback
    self._do_rollback()
  File "/$HOME/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1789, in _do_rollback
    self.connection._rollback_impl()
  File "/$HOME/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 751, in _rollback_impl
    self._handle_dbapi_exception(e, None, None, None, None)
  File "/$HOME/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1510, in _handle_dbapi_exception
    util.raise_(
  File "/$HOME/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/$HOME/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 749, in _rollback_impl
    self.engine.dialect.do_rollback(self.connection)
  File "/$HOME/.local/lib/python3.9/site-packages/sqlalchemy/dialects/mysql/base.py", line 2496, in do_rollback
    dbapi_connection.rollback()
  File "/$HOME/.local/lib/python3.9/site-packages/pymysql/connections.py", line 431, in rollback
    self._execute_command(COMMAND.COM_QUERY, "ROLLBACK")
  File "/$HOME/.local/lib/python3.9/site-packages/pymysql/connections.py", line 742, in _execute_command
    raise err.InterfaceError(0, '')
sqlalchemy.exc.InterfaceError: (pymysql.err.InterfaceError) (0, '')
(Background on this error at: http://sqlalche.me/e/13/rvf5)
01.node.hiveon.net
```

**Comment by spirillen** [comment]
:sob: 

<details><summary>Very looong log output</summary>

```python
Process pyfunceble_tester_worker_3:
Traceback (most recent call last):
  File "$HOME/miniconda/envs/pyfunceble4/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "$HOME/miniconda/envs/pyfunceble4/lib/python3.9/site-packages/PyFunceble/cli/processes/workers/base.py", line 370, in run
    raise exception
  File "$HOME/miniconda/envs/pyfunceble4/lib/python3.9/site-packages/PyFunceble/cli/processes/workers/base.py", line 354, in run
    result = self.target(consumed)
  File "$HOME/miniconda/envs/pyfunceble4/lib/python3.9/site-packages/PyFunceble/cli/processes/workers/tester.py", line 254, in target
    testing_object.set_subject(test_dataset["idna_subject"])
  File "$HOME/miniconda/envs/pyfunceble4/lib/python3.9/site-packages/PyFunceble/checker/base.py", line 198, in set_subject
    self.subject = value
  File "$HOME/miniconda/envs/pyfunceble4/lib/python3.9/site-packages/PyFunceble/checker/base.py", line 104, in wrapper
    self.subject_propagator()
  File "$HOME/miniconda/envs/pyfunceble4/lib/python3.9/site-packages/PyFunceble/checker/availability/base.py", line 422, in subject_propagator
    self.dns_query_tool.set_subject(self.idna_subject)
  File "$HOME/miniconda/envs/pyfunceble4/lib/python3.9/site-packages/PyFunceble/query/dns/query_tool.py", line 287, in set_subject
    self.subject = value
  File "$HOME/miniconda/envs/pyfunceble4/lib/python3.9/site-packages/PyFunceble/query/dns/query_tool.py", line 137, in wrapper
    self.dns_name = self.get_dns_name_from_subject_and_query_type()
  File "$HOME/miniconda/envs/pyfunceble4/lib/python3.9/site-packages/PyFunceble/query/dns/query_tool.py", line 211, in wrapper
    return func(self, *args, **kwargs)  # pylint: disable=not-callable
  File "$HOME/miniconda/envs/pyfunceble4/lib/python3.9/site-packages/PyFunceble/query/dns/query_tool.py", line 245, in get_dns_name_from_subject_and_query_type
    return dns.name.from_text(self.subject)
  File "$HOME/.local/lib/python3.9/site-packages/dns/name.py", line 964, in from_text
    return Name(labels)
  File "$HOME/.local/lib/python3.9/site-packages/dns/name.py", line 324, in __init__
    _validate_labels(self.labels)
  File "$HOME/.local/lib/python3.9/site-packages/dns/name.py", line 284, in _validate_labels
    raise LabelTooLong
dns.name.LabelTooLong: A DNS label is > 63 octets long.
1                                                                                                    ACTIVE      NETINFO    Unknown           Unknown    AVAILABILITY 
Lisens                                                                                               INVALID     SYNTAX     Unknown           Unknown    AVAILABILITY 
day                                                                                                  INVALID     SYNTAX     Unknown           Unknown    AVAILABILITY 
/                                                                                                    INVALID     SYNTAX     Unknown           Unknown    AVAILABILITY 
Licence:                                                                                             INVALID     SYNTAX     Unknown           Unknown    AVAILABILITY 
https://github.com/DandelionSprout/adfilt/blob/master/LICENSE.md                                     INACTIVE    STDLOOKUP  Unknown           200        AVAILABILITY 
^C
Thank you for using PyFunceble!
Do you have a feedback, an issue or an improvement idea? Let us know on GitHub!
Process pyfunceble_tester_worker_4:
Process pyfunceble_tester_worker_5:
Process pyfunceble_producer_worker_1:
Process pyfunceble_tester_worker_2:
Process pyfunceble_tester_worker_6:
Process pyfunceble_tester_worker_1:
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
  File "$HOME/miniconda/envs/pyfunceble4/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "$HOME/miniconda/envs/pyfunceble4/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "$HOME/miniconda/envs/pyfunceble4/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "$HOME/miniconda/envs/pyfunceble4/lib/python3.9/site-packages/PyFunceble/cli/processes/workers/base.py", line 354, in run
    result = self.target(consumed)
  File "$HOME/miniconda/envs/pyfunceble4/lib/python3.9/site-packages/PyFunceble/cli/processes/workers/base.py", line 354, in run
    result = self.target(consumed)
  File "$HOME/miniconda/envs/pyfunceble4/lib/python3.9/site-packages/PyFunceble/cli/processes/workers/base.py", line 354, in run
    result = self.target(consumed)
  File "$HOME/miniconda/envs/pyfunceble4/lib/python3.9/site-packages/PyFunceble/cli/processes/workers/tester.py", line 210, in target
    if self.continue_dataset.exists(test_dataset):
  File "$HOME/miniconda/envs/pyfunceble4/lib/python3.9/site-packages/PyFunceble/cli/processes/workers/tester.py", line 210, in target
    if self.continue_dataset.exists(test_dataset):
  File "$HOME/miniconda/envs/pyfunceble4/lib/python3.9/site-packages/PyFunceble/cli/processes/workers/tester.py", line 210, in target
    if self.continue_dataset.exists(test_dataset):
  File "$HOME/miniconda/envs/pyfunceble4/lib/python3.9/site-packages/PyFunceble/dataset/db_base.py", line 106, in wrapper
    return func(self, *args, **kwargs)  # pylint: disable=not-callable
  File "$HOME/miniconda/envs/pyfunceble4/lib/python3.9/site-packages/PyFunceble/dataset/db_base.py", line 106, in wrapper
    return func(self, *args, **kwargs)  # pylint: disable=not-callable
  File "$HOME/miniconda/envs/pyfunceble4/lib/python3.9/site-packages/PyFunceble/dataset/db_base.py", line 106, in wrapper
    return func(self, *args, **kwargs)  # pylint: disable=not-callable
  File "$HOME/miniconda/envs/pyfunceble4/lib/python3.9/site-packages/PyFunceble/dataset/mariadb_base.py", line 115, in wrapper
    return func(self, *args, **kwargs)  # pylint: disable=not-callable
  File "$HOME/miniconda/envs/pyfunceble4/lib/python3.9/site-packages/PyFunceble/dataset/mariadb_base.py", line 115, in wrapper
    return func(self, *args, **kwargs)  # pylint: disable=not-callable
  File "$HOME/miniconda/envs/pyfunceble4/lib/python3.9/site-packages/PyFunceble/dataset/mariadb_base.py", line 267, in exists
    return result.first() is not None
  File "$HOME/miniconda/envs/pyfunceble4/lib/python3.9/site-packages/PyFunceble/dataset/mariadb_base.py", line 115, in wrapper
    return func(self, *args, **kwargs)  # pylint: disable=not-callable
  File "$HOME/miniconda/envs/pyfunceble4/lib/python3.9/site-packages/PyFunceble/dataset/mariadb_base.py", line 267, in exists
    return result.first() is not None
  File "$HOME/.local/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 3429, in first
    ret = list(self[0:1])
  File "$HOME/miniconda/envs/pyfunceble4/lib/python3.9/site-packages/PyFunceble/dataset/mariadb_base.py", line 267, in exists
    return result.first() is not None
  File "$HOME/.local/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 3429, in first
    ret = list(self[0:1])
  File "$HOME/.local/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 3203, in __getitem__
    return list(res)
  File "$HOME/.local/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 3429, in first
    ret = list(self[0:1])
  File "$HOME/.local/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 3203, in __getitem__
    return list(res)
  File "$HOME/.local/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 3535, in __iter__
    return self._execute_and_instances(context)
  File "$HOME/.local/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 3203, in __getitem__
    return list(res)
  File "$HOME/.local/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 3535, in __iter__
    return self._execute_and_instances(context)
  File "$HOME/.local/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 3556, in _execute_and_instances
    conn = self._get_bind_args(
  File "$HOME/.local/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 3535, in __iter__
    return self._execute_and_instances(context)
  File "$HOME/.local/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 3560, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "$HOME/.local/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 3571, in _get_bind_args
    return fn(
  File "$HOME/.local/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 3560, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "$HOME/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1011, in execute
    return meth(self, multiparams, params)
  File "$HOME/.local/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 3550, in _connection_from_session
    conn = self.session.connection(**kw)
  File "$HOME/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1011, in execute
    return meth(self, multiparams, params)
  File "$HOME/.local/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "$HOME/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1138, in connection
    return self._connection_for_bind(
  File "$HOME/.local/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "$HOME/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1124, in _execute_clauseelement
    ret = self._execute_context(
  File "$HOME/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1146, in _connection_for_bind
    return self.transaction._connection_for_bind(
  File "$HOME/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1124, in _execute_clauseelement
    ret = self._execute_context(
  File "$HOME/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1316, in _execute_context
    self._handle_dbapi_exception(
  File "$HOME/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 433, in _connection_for_bind
    conn = bind._contextual_connect()
  File "$HOME/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1316, in _execute_context
    self._handle_dbapi_exception(
  File "$HOME/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1514, in _handle_dbapi_exception
    util.raise_(exc_info[1], with_traceback=exc_info[2])
  File "$HOME/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2302, in _contextual_connect
    self._wrap_pool_connect(self.pool.connect, None),
  File "$HOME/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1514, in _handle_dbapi_exception
    util.raise_(exc_info[1], with_traceback=exc_info[2])
  File "$HOME/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "$HOME/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2336, in _wrap_pool_connect
    return fn()
  File "$HOME/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "$HOME/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "$HOME/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 364, in connect
    return _ConnectionFairy._checkout(self)
  File "$HOME/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "$HOME/.local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
  File "$HOME/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 778, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "$HOME/.local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
  File "$HOME/.local/lib/python3.9/site-packages/pymysql/cursors.py", line 163, in execute
    result = self._query(query)
  File "$HOME/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 495, in checkout
    rec = pool._do_get()
  File "$HOME/.local/lib/python3.9/site-packages/pymysql/cursors.py", line 163, in execute
    result = self._query(query)
  File "$HOME/.local/lib/python3.9/site-packages/pymysql/cursors.py", line 321, in _query
    conn.query(q)
  File "$HOME/.local/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 241, in _do_get
    return self._create_connection()
  File "$HOME/.local/lib/python3.9/site-packages/pymysql/cursors.py", line 321, in _query
    conn.query(q)
  File "$HOME/.local/lib/python3.9/site-packages/pymysql/connections.py", line 505, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "$HOME/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 309, in _create_connection
    return _ConnectionRecord(self)
  File "$HOME/.local/lib/python3.9/site-packages/pymysql/connections.py", line 505, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "$HOME/.local/lib/python3.9/site-packages/pymysql/connections.py", line 724, in _read_query_result
    result.read()
  File "$HOME/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 440, in __init__
    self.__connect(first_connect_check=True)
  File "$HOME/.local/lib/python3.9/site-packages/pymysql/connections.py", line 724, in _read_query_result
    result.read()
  File "$HOME/.local/lib/python3.9/site-packages/pymysql/connections.py", line 1069, in read
    first_packet = self.connection._read_packet()
  File "$HOME/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 668, in __connect
    pool.dispatch.connect(self.connection, self)
  File "$HOME/.local/lib/python3.9/site-packages/pymysql/connections.py", line 1069, in read
    first_packet = self.connection._read_packet()
  File "$HOME/.local/lib/python3.9/site-packages/pymysql/connections.py", line 646, in _read_packet
    packet_header = self._read_bytes(4)
  File "$HOME/.local/lib/python3.9/site-packages/sqlalchemy/event/attr.py", line 322, in __call__
    fn(*args, **kw)
  File "$HOME/.local/lib/python3.9/site-packages/pymysql/connections.py", line 646, in _read_packet
    packet_header = self._read_bytes(4)
  File "$HOME/.local/lib/python3.9/site-packages/pymysql/connections.py", line 683, in _read_bytes
    data = self._rfile.read(num_bytes)
  File "$HOME/.local/lib/python3.9/site-packages/sqlalchemy/engine/strategies.py", line 189, in on_connect
    do_on_connect(conn)
  File "$HOME/.local/lib/python3.9/site-packages/pymysql/connections.py", line 683, in _read_bytes
    data = self._rfile.read(num_bytes)
  File "$HOME/miniconda/envs/pyfunceble4/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "$HOME/.local/lib/python3.9/site-packages/sqlalchemy/dialects/mysql/mysqldb.py", line 131, in on_connect
    cursor.execute("SET NAMES %s" % charset_name)
  File "$HOME/miniconda/envs/pyfunceble4/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "$HOME/.local/lib/python3.9/site-packages/pymysql/cursors.py", line 163, in execute
    result = self._query(query)
KeyboardInterrupt
  File "$HOME/.local/lib/python3.9/site-packages/pymysql/cursors.py", line 321, in _query
    conn.query(q)
KeyboardInterrupt
  File "$HOME/.local/lib/python3.9/site-packages/pymysql/connections.py", line 505, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "$HOME/.local/lib/python3.9/site-packages/pymysql/connections.py", line 724, in _read_query_result
    result.read()
  File "$HOME/.local/lib/python3.9/site-packages/pymysql/connections.py", line 1069, in read
    first_packet = self.connection._read_packet()
  File "$HOME/.local/lib/python3.9/site-packages/pymysql/connections.py", line 646, in _read_packet
    packet_header = self._read_bytes(4)
  File "$HOME/.local/lib/python3.9/site-packages/pymysql/connections.py", line 683, in _read_bytes
    data = self._rfile.read(num_bytes)
  File "$HOME/miniconda/envs/pyfunceble4/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
KeyboardInterrupt
Traceback (most recent call last):
  File "$HOME/miniconda/envs/pyfunceble4/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "$HOME/miniconda/envs/pyfunceble4/lib/python3.9/site-packages/PyFunceble/cli/processes/workers/base.py", line 354, in run
    result = self.target(consumed)
  File "$HOME/miniconda/envs/pyfunceble4/lib/python3.9/site-packages/PyFunceble/cli/processes/workers/producer.py", line 381, in target
    self.run_inactive_backup(test_dataset, test_result)
  File "$HOME/miniconda/envs/pyfunceble4/lib/python3.9/site-packages/PyFunceble/cli/processes/workers/producer.py", line 245, in run_inactive_backup
    self.inactive_dataset.update(dataset)
  File "$HOME/miniconda/envs/pyfunceble4/lib/python3.9/site-packages/PyFunceble/dataset/db_base.py", line 106, in wrapper
    return func(self, *args, **kwargs)  # pylint: disable=not-callable
  File "$HOME/miniconda/envs/pyfunceble4/lib/python3.9/site-packages/PyFunceble/dataset/mariadb_base.py", line 198, in update
    self.add(row)
  File "$HOME/miniconda/envs/pyfunceble4/lib/python3.9/site-packages/PyFunceble/dataset/db_base.py", line 106, in wrapper
    return func(self, *args, **kwargs)  # pylint: disable=not-callable
  File "$HOME/miniconda/envs/pyfunceble4/lib/python3.9/site-packages/PyFunceble/dataset/mariadb_base.py", line 115, in wrapper
    return func(self, *args, **kwargs)  # pylint: disable=not-callable
  File "$HOME/miniconda/envs/pyfunceble4/lib/python3.9/site-packages/PyFunceble/dataset/mariadb_base.py", line 330, in add
    db_session.commit()
  File "$HOME/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1042, in commit
    self.transaction.commit()
  File "$HOME/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 504, in commit
    self._prepare_impl()
  File "$HOME/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 483, in _prepare_impl
    self.session.flush()
  File "$HOME/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 2536, in flush
    self._flush(objects)
  File "$HOME/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 2678, in _flush
    transaction.rollback(_capture_exception=True)
  File "$HOME/.local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.raise_(
  File "$HOME/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "$HOME/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 2638, in _flush
    flush_context.execute()
  File "$HOME/.local/lib/python3.9/site-packages/sqlalchemy/orm/unitofwork.py", line 422, in execute
    rec.execute(self)
  File "$HOME/.local/lib/python3.9/site-packages/sqlalchemy/orm/unitofwork.py", line 586, in execute
    persistence.save_obj(
  File "$HOME/.local/lib/python3.9/site-packages/sqlalchemy/orm/persistence.py", line 239, in save_obj
    _emit_insert_statements(
  File "$HOME/.local/lib/python3.9/site-packages/sqlalchemy/orm/persistence.py", line 1135, in _emit_insert_statements
    result = cached_connections[connection].execute(
  File "$HOME/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1011, in execute
    return meth(self, multiparams, params)
  File "$HOME/.local/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "$HOME/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1124, in _execute_clauseelement
    ret = self._execute_context(
  File "$HOME/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1316, in _execute_context
    self._handle_dbapi_exception(
  File "$HOME/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1514, in _handle_dbapi_exception
    util.raise_(exc_info[1], with_traceback=exc_info[2])
  File "$HOME/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "$HOME/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "$HOME/.local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
  File "$HOME/.local/lib/python3.9/site-packages/pymysql/cursors.py", line 163, in execute
    result = self._query(query)
  File "$HOME/.local/lib/python3.9/site-packages/pymysql/cursors.py", line 321, in _query
    conn.query(q)
  File "$HOME/.local/lib/python3.9/site-packages/pymysql/connections.py", line 505, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "$HOME/.local/lib/python3.9/site-packages/pymysql/connections.py", line 724, in _read_query_result
    result.read()
  File "$HOME/.local/lib/python3.9/site-packages/pymysql/connections.py", line 1069, in read
    first_packet = self.connection._read_packet()
  File "$HOME/.local/lib/python3.9/site-packages/pymysql/connections.py", line 646, in _read_packet
    packet_header = self._read_bytes(4)
  File "$HOME/.local/lib/python3.9/site-packages/pymysql/connections.py", line 683, in _read_bytes
    data = self._rfile.read(num_bytes)
  File "$HOME/miniconda/envs/pyfunceble4/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
KeyboardInterrupt


        Thank you for feting me with all that junk food, I used to like you too...
^CTraceback (most recent call last):
  File "$HOME/miniconda/envs/pyfunceble4/bin/pyfunceble", line 8, in <module>
    sys.exit(tool())
  File "$HOME/miniconda/envs/pyfunceble4/lib/python3.9/site-packages/PyFunceble/cli/entry_points/pyfunceble/cli.py", line 1037, in tool
```

</details>

**Comment by spirillen** [comment]
Appendix to the above

I did forget to add the `--adblock` #161 to the args line....

2 runs before these got stocked with the `--local` while using our cdb

**Comment by funilrys** [comment]
Considering this as successful. @\me if I'm wrong :wink:

**Comment by spirillen** [comment]
Since the DB test is still running from yesterday, i'll say it is :)
