### ISSUE TITLE
pip install -pre warning MarkUpSafe

### ISSUE THREAD

**Issue by spirillen** [funilrys/PyFunceble#173]
## Bug description
This is less a bug, than something we should keep in mind...

When install through `sudo -H python3.9 -m pip install -U --pre PyFunceble-dev` The following warning appears

```python
sudo -H python3.9 -m pip install -U --pre PyFunceble-dev 
Collecting PyFunceble-dev
  Downloading PyFunceble_dev-4.0.0b1-py3-none-any.whl (457 kB)
     |████████████████████████████████| 457 kB 5.0 MB/s 
Requirement already satisfied: setuptools in /usr/local/lib/python3.9/site-packages (from PyFunceble-dev) (49.2.1)
Collecting dnspython[doh]>=2.0.0
  Downloading dnspython-2.1.0rc1-py3-none-any.whl (241 kB)
     |████████████████████████████████| 241 kB 23.1 MB/s 
Collecting domain2idna>=1.12.0
  Downloading domain2idna-1.12.0-py3-none-any.whl (10 kB)
Collecting python-box[all]>=5.0.0
  Downloading python_box-5.2.0-py3-none-any.whl (20 kB)
Collecting requests<3
  Downloading requests-2.25.1-py2.py3-none-any.whl (61 kB)
     |████████████████████████████████| 61 kB 5.9 MB/s 
Collecting certifi>=2017.4.17
  Downloading certifi-2020.12.5-py2.py3-none-any.whl (147 kB)
     |████████████████████████████████| 147 kB 19.3 MB/s 
Collecting chardet<5,>=3.0.2
  Downloading chardet-4.0.0-py2.py3-none-any.whl (178 kB)
     |████████████████████████████████| 178 kB 18.7 MB/s 
Collecting idna<3,>=2.5
  Downloading idna-2.10-py2.py3-none-any.whl (58 kB)
     |████████████████████████████████| 58 kB 4.7 MB/s 
Collecting urllib3<1.27,>=1.21.1
  Downloading urllib3-1.26.2-py2.py3-none-any.whl (136 kB)
     |████████████████████████████████| 136 kB 26.2 MB/s 
Collecting alembic
  Downloading alembic-1.4.3-py2.py3-none-any.whl (159 kB)
     |████████████████████████████████| 159 kB 19.5 MB/s 
Collecting python-editor>=0.3
  Downloading python_editor-1.0.4-py3-none-any.whl (4.9 kB)
Collecting sqlalchemy
  Downloading SQLAlchemy-1.4.0b1-cp39-cp39-manylinux2010_x86_64.whl (1.5 MB)
     |████████████████████████████████| 1.5 MB 14.1 MB/s 
Collecting colorama
  Downloading colorama-0.4.4-py2.py3-none-any.whl (16 kB)
Collecting cryptography
  Downloading cryptography-3.3.1-cp36-abi3-manylinux2010_x86_64.whl (2.6 MB)
     |████████████████████████████████| 2.6 MB 14.1 MB/s 
Collecting cffi>=1.12
  Downloading cffi-1.14.4-cp39-cp39-manylinux1_x86_64.whl (405 kB)
     |████████████████████████████████| 405 kB 27.0 MB/s 
Collecting six>=1.4.1
  Downloading six-1.15.0-py2.py3-none-any.whl (10 kB)
Collecting greenlet
  Downloading greenlet-1.0a1-cp39-cp39-manylinux2010_x86_64.whl (162 kB)
     |████████████████████████████████| 162 kB 28.2 MB/s 
Collecting inflection
  Downloading inflection-0.5.1-py2.py3-none-any.whl (9.5 kB)
Collecting Mako
  Downloading Mako-1.1.3-py2.py3-none-any.whl (75 kB)
     |████████████████████████████████| 75 kB 3.4 MB/s 
Collecting MarkupSafe>=0.9.2
  Downloading MarkupSafe-2.0.0a1.tar.gz (16 kB)
  WARNING: Requested MarkupSafe>=0.9.2 from https://files.pythonhosted.org/packages/e0/bf/acc45baeb2d7333ed724c30af188640d9cb0be4b28533edfc3e2ae5aad72/MarkupSafe-2.0.0a1.tar.gz#sha256=beac28ed60c8e838301226a7a85841d0af2068eba2dcb1a58c2d32d6c05e440e (from Mako->alembic->PyFunceble-dev), but installing version 2.0.0a1
Collecting msgpack
  Downloading msgpack-1.0.2-cp39-cp39-manylinux1_x86_64.whl (294 kB)
     |████████████████████████████████| 294 kB 21.3 MB/s 
Collecting pycparser
  Downloading pycparser-2.20-py2.py3-none-any.whl (112 kB)
     |████████████████████████████████| 112 kB 24.7 MB/s 
Collecting PyMySQL
  Downloading PyMySQL-1.0.0-py3-none-any.whl (43 kB)
     |████████████████████████████████| 43 kB 2.2 MB/s 
Collecting python-dateutil
  Downloading python_dateutil-2.8.1-py2.py3-none-any.whl (227 kB)
     |████████████████████████████████| 227 kB 27.9 MB/s 
Collecting python-dotenv
  Downloading python_dotenv-0.15.0-py2.py3-none-any.whl (18 kB)
Collecting PyYAML
  Downloading PyYAML-5.3.1.tar.gz (269 kB)
     |████████████████████████████████| 269 kB 24.0 MB/s 
Collecting requests-toolbelt
  Downloading requests_toolbelt-0.9.1-py2.py3-none-any.whl (54 kB)
     |████████████████████████████████| 54 kB 2.2 MB/s 
Collecting ruamel.yaml
  Downloading ruamel.yaml-0.16.12-py2.py3-none-any.whl (111 kB)
     |████████████████████████████████| 111 kB 27.5 MB/s 
Collecting toml
  Downloading toml-0.10.2-py2.py3-none-any.whl (16 kB)
Using legacy 'setup.py install' for MarkupSafe, since package 'wheel' is not installed.
Using legacy 'setup.py install' for PyYAML, since package 'wheel' is not installed.
Installing collected packages: urllib3, idna, chardet, certifi, six, requests, pycparser, MarkupSafe, greenlet, toml, sqlalchemy, ruamel.yaml, requests-toolbelt, python-editor, python-dateutil, python-box, msgpack, Mako, dnspython, colorama, cffi, PyYAML, python-dotenv, PyMySQL, inflection, domain2idna, cryptography, alembic, PyFunceble-dev
    Running setup.py install for MarkupSafe ... done
    Running setup.py install for PyYAML ... done
Successfully installed Mako-1.1.3 MarkupSafe-2.0.0a1 PyFunceble-dev-4.0.0b1 PyMySQL-1.0.0 PyYAML-5.3.1 alembic-1.4.3 certifi-2020.12.5 cffi-1.14.4 chardet-4.0.0 colorama-0.4.4 cryptography-3.3.1 dnspython-2.1.0rc1 domain2idna-1.12.0 greenlet-1.0a1 idna-2.10 inflection-0.5.1 msgpack-1.0.2 pycparser-2.20 python-box-5.2.0 python-dateutil-2.8.1 python-dotenv-0.15.0 python-editor-1.0.4 requests-2.25.1 requests-toolbelt-0.9.1 ruamel.yaml-0.16.12 six-1.15.0 sqlalchemy-1.4.0b1 toml-0.10.2 urllib3-1.26.2
```

AND :sob: this fellow have returned outside conda...

```python
pyfunceble --version
Traceback (most recent call last):
  File "/usr/local/bin/pyfunceble", line 5, in <module>
    from PyFunceble.cli.entry_points.pyfunceble.cli import tool
  File "/usr/local/lib/python3.9/site-packages/PyFunceble/__init__.py", line 56, in <module>
    from PyFunceble.checker.availability.domain import DomainAvailabilityChecker
  File "/usr/local/lib/python3.9/site-packages/PyFunceble/checker/availability/domain.py", line 57, in <module>
    from PyFunceble.checker.availability.base import AvailabilityCheckerBase
  File "/usr/local/lib/python3.9/site-packages/PyFunceble/checker/availability/base.py", line 58, in <module>
    import PyFunceble.checker.utils.whois
  File "/usr/local/lib/python3.9/site-packages/PyFunceble/checker/utils/whois.py", line 61, in <module>
    from PyFunceble.dataset.whois.mariadb import MariaDBWhoisDataset
  File "/usr/local/lib/python3.9/site-packages/PyFunceble/dataset/whois/mariadb.py", line 65, in <module>
    from PyFunceble.dataset.mariadb_base import MariaDBDatasetBase
  File "/usr/local/lib/python3.9/site-packages/PyFunceble/dataset/mariadb_base.py", line 56, in <module>
    from sqlalchemy.ext.declarative.api import DeclarativeMeta
ModuleNotFoundError: No module named 'sqlalchemy.ext.declarative.api'
```

Even tried with `-I`

```shell
sudo -H pip3 install -I --no-cache --pre pyfunceble-dev
```

to force reinstall all subpackages and deleted the following from `$HOME/.config/PyFunceble`

```shell
rm dir_structure.json public-suffix.json .PyFunceble_production.yaml .PyFunceble.yaml
```

![image](https://user-images.githubusercontent.com/44526987/103921172-763e7d00-5112-11eb-9530-799aea333ae5.png)

![image](https://user-images.githubusercontent.com/44526987/103921235-8b1b1080-5112-11eb-8b0a-289b94071c08.png)

**Comment by spirillen** [comment]
This issue is in reply to <https://github.com/funilrys/PyFunceble/issues/134#issuecomment-755691141>

**Comment by funilrys** [comment]
Yup, I noticed this while looking @mitchellkrogza's internal workflow after switching to 4.0.0. 
I simply can't explain this. Installing `SQLAlchemy` (case sensitive) manually fixed it ... And I can't understand it.

**Comment by funilrys** [comment]
Oh ! I think I get it. You are downloading:

```
Downloading SQLAlchemy-1.4.0b1-cp39-cp39-manylinux2010_x86_64.whl (1.5 MB)
```

Mhh I need to test that one.

**Comment by spirillen** [comment]
Will look into this in 1 minutes, would just explain the `-I`

The `-I` (capital) When upgrading, reinstall all packages even if they are already up-to-date.

```
pip install -I <package>
pip install --ignore-installed <package>
```

Ignores the installed packages (reinstalling instead).

**Comment by spirillen** [comment]
> SQLAlchemy

Because we uses `--pre` then we get the beta of `SQLAlchemy` vs the stable release :stuck_out_tongue_closed_eyes:

**Comment by funilrys** [comment]
The patch is on its way out 😄.

**Comment by funilrys** [comment]
The patch is now out. It will be into `b2` which is under deployment.

GHA: https://github.com/funilrys/PyFunceble/actions/runs/469543082

**Comment by spirillen** [comment]
> The patch is on its way out smile.

and it made a conflict with <https://github.com/funilrys/PyFunceble/pull/174> :unamused:

**Comment by funilrys** [comment]
How can a single commit create a conflict !? I thought you were just into the docs 😂  I will try to look into that while reviewing your patch.

**Comment by funilrys** [comment]
Update: There was a problem because of an error in the format of the README. 

New GHA for the deployment of `b2`: https://github.com/funilrys/PyFunceble/actions/runs/469586032

**Comment by funilrys** [comment]
`b2` available to the world. Closing.

**Comment by spirillen** [comment]
Believes we should move this project to done :smirk: 
https://github.com/funilrys/PyFunceble/projects/6#card-52384189
