### ISSUE TITLE
orm (PyFunceble_dev-4.0.0b7-py3-none-any.whl)

### ISSUE THREAD

**Issue by spirillen** [funilrys/PyFunceble#187]
## Bug description
<details><summary>Long log</summary>

pip install -UI --pre pyfunceble-dev
Collecting pyfunceble-dev
  Downloading PyFunceble_dev-4.0.0b7-py3-none-any.whl (459 kB)
     |████████████████████████████████| 459 kB 3.4 MB/s 
Collecting dnspython[doh]>=2.0.0
  Downloading dnspython-2.1.0-py3-none-any.whl (241 kB)
     |████████████████████████████████| 241 kB 21.3 MB/s 
Collecting domain2idna>=1.12.0
  Downloading domain2idna-1.12.0-py3-none-any.whl (10 kB)
Collecting python-box[all]>=5.0.0
  Downloading python_box-5.2.0-py3-none-any.whl (20 kB)
Collecting requests<3
  Downloading requests-2.25.1-py2.py3-none-any.whl (61 kB)
     |████████████████████████████████| 61 kB 2.1 MB/s 
Collecting certifi>=2017.4.17
  Downloading certifi-2020.12.5-py2.py3-none-any.whl (147 kB)
     |████████████████████████████████| 147 kB 26.2 MB/s 
Collecting chardet<5,>=3.0.2
  Downloading chardet-4.0.0-py2.py3-none-any.whl (178 kB)
     |████████████████████████████████| 178 kB 23.1 MB/s 
Collecting idna<3,>=2.5
  Downloading idna-2.10-py2.py3-none-any.whl (58 kB)
     |████████████████████████████████| 58 kB 14.1 MB/s 
Collecting SQLAlchemy>=1.3.20
  Downloading SQLAlchemy-1.4.0b1-cp39-cp39-manylinux2010_x86_64.whl (1.5 MB)
     |████████████████████████████████| 1.5 MB 20.9 MB/s 
Collecting urllib3<1.27,>=1.21.1
  Downloading urllib3-1.26.2-py2.py3-none-any.whl (136 kB)
     |████████████████████████████████| 136 kB 27.4 MB/s 
Collecting alembic
  Downloading alembic-1.4.3-py2.py3-none-any.whl (159 kB)
     |████████████████████████████████| 159 kB 22.1 MB/s 
Collecting python-editor>=0.3
  Downloading python_editor-1.0.4-py3-none-any.whl (4.9 kB)
Collecting colorama
  Downloading colorama-0.4.4-py2.py3-none-any.whl (16 kB)
Collecting cryptography
  Downloading cryptography-3.3.1-cp36-abi3-manylinux2010_x86_64.whl (2.6 MB)
     |████████████████████████████████| 2.6 MB 25.9 MB/s 
Collecting cffi>=1.12
  Downloading cffi-1.14.4-cp39-cp39-manylinux1_x86_64.whl (405 kB)
     |████████████████████████████████| 405 kB 25.1 MB/s 
Collecting six>=1.4.1
  Downloading six-1.15.0-py2.py3-none-any.whl (10 kB)
Collecting greenlet
  Downloading greenlet-1.0a1-cp39-cp39-manylinux2010_x86_64.whl (162 kB)
     |████████████████████████████████| 162 kB 21.8 MB/s 
Collecting inflection
  Downloading inflection-0.5.1-py2.py3-none-any.whl (9.5 kB)
Collecting Mako
  Downloading Mako-1.1.3-py2.py3-none-any.whl (75 kB)
     |████████████████████████████████| 75 kB 8.8 MB/s 
Collecting MarkupSafe>=0.9.2
  Downloading MarkupSafe-2.0.0a1.tar.gz (16 kB)
  WARNING: Requested MarkupSafe>=0.9.2 from https://files.pythonhosted.org/packages/e0/bf/acc45baeb2d7333ed724c30af188640d9cb0be4b28533edfc3e2ae5aad72/MarkupSafe-2.0.0a1.tar.gz#sha256=beac28ed60c8e838301226a7a85841d0af2068eba2dcb1a58c2d32d6c05e440e (from Mako->alembic->pyfunceble-dev), but installing version 2.0.0a1                           
Collecting msgpack
  Downloading msgpack-1.0.2-cp39-cp39-manylinux1_x86_64.whl (294 kB)
     |████████████████████████████████| 294 kB 21.2 MB/s 
Collecting pycparser
  Downloading pycparser-2.20-py2.py3-none-any.whl (112 kB)
     |████████████████████████████████| 112 kB 22.1 MB/s 
Collecting PyMySQL
  Downloading PyMySQL-1.0.2-py3-none-any.whl (43 kB)
     |████████████████████████████████| 43 kB 5.5 MB/s 
Collecting python-dateutil
  Downloading python_dateutil-2.8.1-py2.py3-none-any.whl (227 kB)
     |████████████████████████████████| 227 kB 19.2 MB/s 
Collecting python-dotenv
  Downloading python_dotenv-0.15.0-py2.py3-none-any.whl (18 kB)
Collecting PyYAML
  Downloading PyYAML-5.3.1.tar.gz (269 kB)
     |████████████████████████████████| 269 kB 22.7 MB/s 
Collecting requests-toolbelt
  Downloading requests_toolbelt-0.9.1-py2.py3-none-any.whl (54 kB)
     |████████████████████████████████| 54 kB 3.1 MB/s 
Collecting ruamel.yaml
  Downloading ruamel.yaml-0.16.12-py2.py3-none-any.whl (111 kB)
     |████████████████████████████████| 111 kB 27.6 MB/s 
Collecting toml
  Downloading toml-0.10.2-py2.py3-none-any.whl (16 kB)
Collecting setuptools
  Downloading setuptools-51.1.2-py3-none-any.whl (784 kB)
     |████████████████████████████████| 784 kB 23.3 MB/s 
Building wheels for collected packages: MarkupSafe, PyYAML
  Building wheel for MarkupSafe (setup.py) ... done
  Created wheel for MarkupSafe: filename=MarkupSafe-2.0.0a1-cp39-cp39-linux_x86_64.whl size=14621 sha256=9d6b0070cbe90f698e6516a21053f120a90f94fd24765552819aad51ad1980c1
  Stored in directory: /home/spirillen/.cache/pip/wheels/5f/b9/dd/472dc449d66ee87116e227569d91c5a5a70d5288bbad1a4c77
  Building wheel for PyYAML (setup.py) ... done
  Created wheel for PyYAML: filename=PyYAML-5.3.1-cp39-cp39-linux_x86_64.whl size=44618 sha256=5ad4ba56a2d068ea900b55fbbc3a468be14b83caf824c63bb384ce050befdb2b
  Stored in directory: /home/spirillen/.cache/pip/wheels/69/60/81/5cd74b8ee068fbe9e04ca0d53148f28f5c6e2c5b177d5dd622
Successfully built MarkupSafe PyYAML
Installing collected packages: urllib3, idna, chardet, certifi, six, requests, pycparser, MarkupSafe, greenlet, toml, SQLAlchemy, setuptools, ruamel.yaml, requests-toolbelt, python-editor, python-dateutil, python-box, msgpack, Mako, dnspython, colorama, cffi, PyYAML, python-dotenv, PyMySQL, inflection, domain2idna, cryptography, alembic, pyfunceble-dev
Successfully installed Mako-1.1.3 MarkupSafe-2.0.0a1 PyMySQL-1.0.2 PyYAML-5.3.1 SQLAlchemy-1.4.0b1 alembic-1.4.3 certifi-2020.12.5 cffi-1.14.4 chardet-4.0.0 colorama-0.4.4 cryptography-3.3.1 dnspython-2.1.0 domain2idna-1.12.0 greenlet-1.0a1 idna-2.10 inflection-0.5.1 msgpack-1.0.2 pycparser-2.20 pyfunceble-dev-4.0.0b7 python-box-5.2.0 python-dateutil-2.8.1 python-dotenv-0.15.0 python-editor-1.0.4 requests-2.25.1 requests-toolbelt-0.9.1 ruamel.yaml-0.16.12 setuptools-51.1.2 six-1.15.0 toml-0.10.2 urllib3-1.26.2
spirillen@e350c:/var/storage01/repos/github/PyFunceble-Templates/pyfunceble-miniconda$ pyfunceble -database-type mariadb -f /var/storage01/repos/github/PyFunceble-Templates/pyfunceble-miniconda/test.list 
Traceback (most recent call last):
  File "/home/spirillen/miniconda/envs/pyfunceble4/bin/pyfunceble", line 5, in <module>
    from PyFunceble.cli.entry_points.pyfunceble.cli import tool
  File "/home/spirillen/miniconda/envs/pyfunceble4/lib/python3.9/site-packages/PyFunceble/__init__.py", line 56, in <module>
    from PyFunceble.checker.availability.domain import DomainAvailabilityChecker
  File "/home/spirillen/miniconda/envs/pyfunceble4/lib/python3.9/site-packages/PyFunceble/checker/availability/domain.py", line 57, in <module>
    from PyFunceble.checker.availability.base import AvailabilityCheckerBase
  File "/home/spirillen/miniconda/envs/pyfunceble4/lib/python3.9/site-packages/PyFunceble/checker/availability/base.py", line 58, in <module>
    import PyFunceble.checker.utils.whois
  File "/home/spirillen/miniconda/envs/pyfunceble4/lib/python3.9/site-packages/PyFunceble/checker/utils/whois.py", line 61, in <module>
    from PyFunceble.dataset.whois.mariadb import MariaDBWhoisDataset
  File "/home/spirillen/miniconda/envs/pyfunceble4/lib/python3.9/site-packages/PyFunceble/dataset/whois/mariadb.py", line 65, in <module>
    from PyFunceble.dataset.mariadb_base import MariaDBDatasetBase
  File "/home/spirillen/miniconda/envs/pyfunceble4/lib/python3.9/site-packages/PyFunceble/dataset/mariadb_base.py", line 57, in <module>
    from sqlalchemy.ext.declarative.api import DeclarativeMeta
  File "/home/spirillen/miniconda/envs/pyfunceble4/lib/python3.9/site-packages/sqlalchemy/ext/declarative/api.py", line 24, in <module>
    from ...orm import comparable_property
ImportError: cannot import name 'comparable_property' from 'sqlalchemy.orm' (/home/spirillen/miniconda/envs/pyfunceble4/lib/python3.9/site-packages/sqlalchemy/orm/__init__.py)
spirillen@e350c:/var/storage01/repos/github/PyFunceble-Templates/pyfunceble-miniconda$ pyfunceble --version
Traceback (most recent call last):
  File "/home/spirillen/miniconda/envs/pyfunceble4/bin/pyfunceble", line 5, in <module>
    from PyFunceble.cli.entry_points.pyfunceble.cli import tool
  File "/home/spirillen/miniconda/envs/pyfunceble4/lib/python3.9/site-packages/PyFunceble/__init__.py", line 56, in <module>
    from PyFunceble.checker.availability.domain import DomainAvailabilityChecker
  File "/home/spirillen/miniconda/envs/pyfunceble4/lib/python3.9/site-packages/PyFunceble/checker/availability/domain.py", line 57, in <module>
    from PyFunceble.checker.availability.base import AvailabilityCheckerBase
  File "/home/spirillen/miniconda/envs/pyfunceble4/lib/python3.9/site-packages/PyFunceble/checker/availability/base.py", line 58, in <module>
    import PyFunceble.checker.utils.whois
  File "/home/spirillen/miniconda/envs/pyfunceble4/lib/python3.9/site-packages/PyFunceble/checker/utils/whois.py", line 61, in <module>
    from PyFunceble.dataset.whois.mariadb import MariaDBWhoisDataset
  File "/home/spirillen/miniconda/envs/pyfunceble4/lib/python3.9/site-packages/PyFunceble/dataset/whois/mariadb.py", line 65, in <module>
    from PyFunceble.dataset.mariadb_base import MariaDBDatasetBase
  File "/home/spirillen/miniconda/envs/pyfunceble4/lib/python3.9/site-packages/PyFunceble/dataset/mariadb_base.py", line 57, in <module>
    from sqlalchemy.ext.declarative.api import DeclarativeMeta
  File "/home/spirillen/miniconda/envs/pyfunceble4/lib/python3.9/site-packages/sqlalchemy/ext/declarative/api.py", line 24, in <module>
    from ...orm import comparable_property
ImportError: cannot import name 'comparable_property' from 'sqlalchemy.orm' (/home/spirillen/miniconda/envs/pyfunceble4/lib/python3.9/site-packages/sqlalchemy/orm/__init__.py)

</details>

## Modifications under `.PyFunceble.yaml`

Nada

## Reproduction

See log above

## Versions

**OS:** Ubuntu 20 + Conda
**Python Version:** for example 3.9.1
**PyFunceble Version:** PyFunceble_dev-4.0.0b7-py3-none-any.whl

**Comment by spirillen** [comment]
shoud be in the "Done" at https://github.com/funilrys/PyFunceble/projects/6#card-52575707
