### ISSUE TITLE
SQL more than one match of WHOIS

### ISSUE THREAD

**Issue by spirillen** [funilrys/PyFunceble#189]
## Bug description
sqlalchemy.orm.exc.StaleDataError: UPDATE statement on table 'pyfunceble_whois_record' expected to update 1 row(s); 12 were matched.

Simply just merge them, as in this example it actually reasons of a broken import

![image](https://user-images.githubusercontent.com/44526987/104239030-23d6c680-545a-11eb-8896-4f27bf96423e.png)

**Comment by spirillen** [comment]
While we are at the MariaDB

This happens on both MariaDB and MySql when I was exporting / importing
![image](https://user-images.githubusercontent.com/44526987/104239666-2b4a9f80-545b-11eb-92ed-bf4bc17c20a2.png)

![image](https://user-images.githubusercontent.com/44526987/104239687-37cef800-545b-11eb-8600-0989319bdfce.png)

![image](https://user-images.githubusercontent.com/44526987/104239714-3ef60600-545b-11eb-9619-a8bb78f07ae7.png)

**Comment by funilrys** [comment]
They actually have a default value. But not a server-side one. They are client-side. Meaning that if inserted by PyFunceble, such things (images) should not happen. Unless, when we played with it and I was not ready with the structure of the dataset. 

Just put a default date of your choice in there. Those 2 `created_at` and `modified_at`, are just meant for humans and are not used by PyFunceble directly. About the OP question, the stack is incomplete meaning that I have to imagine where it happened. But such a thing shouldn't happen. There are mechanisms in place to avoid that 🤔

I played with my database and there is no way, I could not introduce a duplicate in there... 🤔  What is happening here?

**Comment by spirillen** [comment]
> Just put a default date of your choice in there. Those 2 created_at and modified_at

Will try that :+1: 

> I played with my database and there is no way, I could introduce a duplicate in there..

Try keybase://chat/spirillen,funilrys/2581

**Comment by spirillen** [comment]
Still happens on mariadb

![image](https://user-images.githubusercontent.com/44526987/104695962-cec2db00-570d-11eb-9c24-570590ef4a9a.png)

**Comment by spirillen** [comment]
From local db to [cdb.mypdns.org](https://www.mypdns.org/project/view/34/)

![image](https://user-images.githubusercontent.com/44526987/104696582-cb7c1f00-570e-11eb-8698-85eb82effd53.png)

See also: <https://github.com/funilrys/PyFunceble/issues/188#issuecomment-760780457>

**Comment by spirillen** [comment]
Hmm https://github.com/funilrys/PyFunceble/issues/188#issuecomment-760780457

```python
4chan.org                                                                                            ACTIVE      WHOIS      14-feb-2023       Unknown    AVAILABILITY 
Process pyfunceble_producer_worker_1:
Traceback (most recent call last):
  File "/var/storage01/repos/github/pyfunceble/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/var/storage01/repos/github/pyfunceble/venv/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 609, in do_execute
    cursor.execute(statement, parameters)
  File "/var/storage01/repos/github/pyfunceble/venv/lib/python3.9/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "/var/storage01/repos/github/pyfunceble/venv/lib/python3.9/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "/var/storage01/repos/github/pyfunceble/venv/lib/python3.9/site-packages/pymysql/connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/var/storage01/repos/github/pyfunceble/venv/lib/python3.9/site-packages/pymysql/connections.py", line 775, in _read_query_result
    result.read()
  File "/var/storage01/repos/github/pyfunceble/venv/lib/python3.9/site-packages/pymysql/connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "/var/storage01/repos/github/pyfunceble/venv/lib/python3.9/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "/var/storage01/repos/github/pyfunceble/venv/lib/python3.9/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/var/storage01/repos/github/pyfunceble/venv/lib/python3.9/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1062, "Duplicate entry '773703' for key 'PRIMARY'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/var/storage01/repos/github/pyfunceble/PyFunceble/cli/processes/workers/base.py", line 419, in run
    raise exception
  File "/var/storage01/repos/github/pyfunceble/PyFunceble/cli/processes/workers/base.py", line 404, in run
    result = self.target(consumed)
  File "/var/storage01/repos/github/pyfunceble/PyFunceble/cli/processes/workers/producer.py", line 382, in target
    self.run_continue_backup(test_dataset, test_result)
  File "/var/storage01/repos/github/pyfunceble/PyFunceble/cli/processes/workers/producer.py", line 271, in run_continue_backup
    self.continue_dataset.update(dataset)
  File "/var/storage01/repos/github/pyfunceble/PyFunceble/dataset/db_base.py", line 106, in wrapper
    return func(self, *args, **kwargs)  # pylint: disable=not-callable
  File "/var/storage01/repos/github/pyfunceble/PyFunceble/dataset/mariadb_base.py", line 200, in update
    self.update(row)
  File "/var/storage01/repos/github/pyfunceble/PyFunceble/dataset/db_base.py", line 106, in wrapper
    return func(self, *args, **kwargs)  # pylint: disable=not-callable
  File "/var/storage01/repos/github/pyfunceble/PyFunceble/dataset/mariadb_base.py", line 194, in update
    db_session.execute(self.ORM_OBJ.__table__.update(), row)
  File "/var/storage01/repos/github/pyfunceble/venv/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1295, in execute
    return self._connection_for_bind(bind, close_with_result=True).execute(
  File "/var/storage01/repos/github/pyfunceble/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1011, in execute
    return meth(self, multiparams, params)
  File "/var/storage01/repos/github/pyfunceble/venv/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/var/storage01/repos/github/pyfunceble/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1124, in _execute_clauseelement
    ret = self._execute_context(
  File "/var/storage01/repos/github/pyfunceble/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1316, in _execute_context
    self._handle_dbapi_exception(
  File "/var/storage01/repos/github/pyfunceble/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1510, in _handle_dbapi_exception
    util.raise_(
  File "/var/storage01/repos/github/pyfunceble/venv/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/var/storage01/repos/github/pyfunceble/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/var/storage01/repos/github/pyfunceble/venv/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 609, in do_execute
    cursor.execute(statement, parameters)
  File "/var/storage01/repos/github/pyfunceble/venv/lib/python3.9/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "/var/storage01/repos/github/pyfunceble/venv/lib/python3.9/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "/var/storage01/repos/github/pyfunceble/venv/lib/python3.9/site-packages/pymysql/connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/var/storage01/repos/github/pyfunceble/venv/lib/python3.9/site-packages/pymysql/connections.py", line 775, in _read_query_result
    result.read()
  File "/var/storage01/repos/github/pyfunceble/venv/lib/python3.9/site-packages/pymysql/connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "/var/storage01/repos/github/pyfunceble/venv/lib/python3.9/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "/var/storage01/repos/github/pyfunceble/venv/lib/python3.9/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/var/storage01/repos/github/pyfunceble/venv/lib/python3.9/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
sqlalchemy.exc.IntegrityError: (pymysql.err.IntegrityError) (1062, "Duplicate entry '773703' for key 'PRIMARY'")
[SQL: UPDATE pyfunceble_continue SET id=%(id)s, modified_at=%(modified_at)s, idna_subject=%(idna_subject)s, checker_type=%(checker_type)s, destination=%(destination)s, source=%(source)s, tested_at=%(tested_at)s, session_id=%(session_id)s]
[parameters: {'id': 773703, 'modified_at': datetime.datetime(2021, 1, 15, 9, 34, 51, 816853), 'idna_subject': '4chan.org', 'checker_type': 'AVAILABILITY', 'destination': 'strict_adult.txt', 'source': '/var/storage01/repos/github/pyfunceble/strict_adult.txt', 'tested_at': datetime.datetime(2021, 1, 15, 7, 53, 12, 888251), 'session_id': '6dc3a23fc29d3242e16c0414'}]
(Background on this error at: http://sqlalche.me/e/13/gkpj)
Fatal Error: (pymysql.err.IntegrityError) (1062, "Duplicate entry '773703' for key 'PRIMARY'")
[SQL: UPDATE pyfunceble_continue SET id=%(id)s, modified_at=%(modified_at)s, idna_subject=%(idna_subject)s, checker_type=%(checker_type)s, destination=%(destination)s, source=%(source)s, tested_at=%(tested_at)s, session_id=%(session_id)s]
[parameters: {'id': 773703, 'modified_at': datetime.datetime(2021, 1, 15, 9, 34, 51, 816853), 'idna_subject': '4chan.org', 'checker_type': 'AVAILABILITY', 'destina ... (51 characters truncated) ... 1/repos/github/pyfunceble/strict_adult.txt', 'tested_at': datetime.datetime(2021, 1, 15, 7, 53, 12, 888251), 'session_id': '6dc3a23fc29d3242e16c0414'}]
```
