### ISSUE TITLE
Hangs at end of test

### ISSUE THREAD

**Issue by spirillen** [funilrys/PyFunceble#190]
## Bug description
First reported by @ZeroDot1 in <https://github.com/funilrys/PyFunceble/issues/134#issuecomment-758178503>

> Addition, as soon as the entire list is processed it hangs again.

Can confirm this on latest commit..., It have been hanging for 10 hours after last test...

![image](https://user-images.githubusercontent.com/44526987/104549508-4f60d900-5633-11eb-8254-2f45a923ecca.png)

```console
git log
commit 0d5e5450473aff6712277d8dd0bbc240e2f953f1 (HEAD -> dev)
Author: funilrys <contact@funilrys.com>
Date:   Sun Jan 10 16:25:26 2021 +0100

    Fix issue when the logger is not configured (yet).
```

**Comment by spirillen** [comment]
Appendix.. almost latest... retesting with

git log
commit 773e5f96746ddf779da2ee68c5b81f0fe212c08c (HEAD -> dev, origin/dev)

**Comment by ZeroDot1** [comment]
Hi @funilrys After some more test runs, I can confirm the problem.

**Comment by ZeroDot1** [comment]
When I kill the process it displays the following message.

```
^C
Thank you for using PyFunceble!
Process pyfunceble_file_sorter_worker_1:
Traceback (most recent call last):
  File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.9/site-packages/PyFunceble/cli/processes/workers/base.py", line 404, in run
    result = self.target(consumed)
  File "/usr/lib/python3.9/site-packages/PyFunceble/cli/processes/workers/file_sorter.py", line 201, in target
    self.process_file_sorting(file)
  File "/usr/lib/python3.9/site-packages/PyFunceble/cli/processes/workers/file_sorter.py", line 157, in process_file_sorting
    ListHelper(to_sort)
  File "/usr/lib/python3.9/site-packages/PyFunceble/helpers/list.py", line 129, in remove_duplicates
    known.append(subject)
KeyboardInterrupt
```

**Comment by funilrys** [comment]
Closing in the hope that my patch fixes this. Please feel free to @\me or reopen if it's not the case.
