### ISSUE TITLE
v4-dev ModuleNotFoundError: No module named 'importlib_resources'

### ISSUE THREAD

**Issue by spirillen** [funilrys/PyFunceble#191]
## Bug description
Fresh install of pyfunceble through git <https://pyfunceble.readthedocs.io/en/dev/installation/index.html>

## Modifications under `.PyFunceble.yaml`

None

## Reproduction

<details><summary>Long log</summary>

```python
pip3 install -e .
Obtaining file:///tmp/pyfunceble
Requirement already satisfied: setuptools in ./venv/lib/python3.6/site-packages (from PyFunceble-dev==4.0.0b9) (51.1.2)
Collecting dnspython[doh]>=2.0.0
  Downloading dnspython-2.1.0-py3-none-any.whl (241 kB)
     |████████████████████████████████| 241 kB 1.7 MB/s 
Collecting domain2idna>=1.12.0
  Downloading domain2idna-1.12.0-py3-none-any.whl (10 kB)
Collecting python-box[all]>=5.0.0
  Downloading python_box-5.2.0-py3-none-any.whl (20 kB)
Collecting requests<3
  Downloading requests-2.25.1-py2.py3-none-any.whl (61 kB)
     |████████████████████████████████| 61 kB 6.0 MB/s 
Collecting certifi>=2017.4.17
  Downloading certifi-2020.12.5-py2.py3-none-any.whl (147 kB)
     |████████████████████████████████| 147 kB 10.2 MB/s 
Collecting chardet<5,>=3.0.2
  Downloading chardet-4.0.0-py2.py3-none-any.whl (178 kB)
     |████████████████████████████████| 178 kB 10.0 MB/s 
Collecting idna<3,>=2.5
  Downloading idna-2.10-py2.py3-none-any.whl (58 kB)
     |████████████████████████████████| 58 kB 5.6 MB/s 
Collecting SQLAlchemy>=1.3.20
  Downloading SQLAlchemy-1.3.22-cp36-cp36m-manylinux2010_x86_64.whl (1.3 MB)
     |████████████████████████████████| 1.3 MB 9.9 MB/s 
Collecting urllib3<1.27,>=1.21.1
  Downloading urllib3-1.26.2-py2.py3-none-any.whl (136 kB)
     |████████████████████████████████| 136 kB 17.2 MB/s 
Collecting alembic
  Downloading alembic-1.4.3-py2.py3-none-any.whl (159 kB)
     |████████████████████████████████| 159 kB 15.3 MB/s 
Collecting python-editor>=0.3
  Downloading python_editor-1.0.4-py3-none-any.whl (4.9 kB)
Collecting colorama
  Downloading colorama-0.4.4-py2.py3-none-any.whl (16 kB)
Collecting cryptography
  Downloading cryptography-3.3.1-cp36-abi3-manylinux2010_x86_64.whl (2.6 MB)
     |████████████████████████████████| 2.6 MB 14.1 MB/s 
Collecting cffi>=1.12
  Downloading cffi-1.14.4-cp36-cp36m-manylinux1_x86_64.whl (401 kB)
     |████████████████████████████████| 401 kB 24.1 MB/s 
Collecting six>=1.4.1
  Using cached six-1.15.0-py2.py3-none-any.whl (10 kB)
Collecting inflection
  Downloading inflection-0.5.1-py2.py3-none-any.whl (9.5 kB)
Collecting Mako
  Downloading Mako-1.1.4.tar.gz (479 kB)
     |████████████████████████████████| 479 kB 23.6 MB/s 
Collecting MarkupSafe>=0.9.2
  Downloading MarkupSafe-1.1.1-cp36-cp36m-manylinux1_x86_64.whl (27 kB)
Collecting msgpack
  Downloading msgpack-1.0.2-cp36-cp36m-manylinux1_x86_64.whl (272 kB)
     |████████████████████████████████| 272 kB 21.2 MB/s 
Collecting pycparser
  Downloading pycparser-2.20-py2.py3-none-any.whl (112 kB)
     |████████████████████████████████| 112 kB 3.3 MB/s 
Collecting PyMySQL
  Downloading PyMySQL-1.0.2-py3-none-any.whl (43 kB)
     |████████████████████████████████| 43 kB 1.1 MB/s 
Collecting python-dateutil
  Downloading python_dateutil-2.8.1-py2.py3-none-any.whl (227 kB)
     |████████████████████████████████| 227 kB 17.4 MB/s 
Collecting python-dotenv
  Downloading python_dotenv-0.15.0-py2.py3-none-any.whl (18 kB)
Collecting PyYAML
  Downloading PyYAML-5.3.1.tar.gz (269 kB)
     |████████████████████████████████| 269 kB 19.7 MB/s 
Collecting requests-toolbelt
  Downloading requests_toolbelt-0.9.1-py2.py3-none-any.whl (54 kB)
     |████████████████████████████████| 54 kB 4.0 MB/s 
Collecting ruamel.yaml
  Downloading ruamel.yaml-0.16.12-py2.py3-none-any.whl (111 kB)
     |████████████████████████████████| 111 kB 21.0 MB/s 
Collecting ruamel.yaml.clib>=0.1.2
  Downloading ruamel.yaml.clib-0.2.2-cp36-cp36m-manylinux1_x86_64.whl (549 kB)
     |████████████████████████████████| 549 kB 20.6 MB/s 
Collecting toml
  Downloading toml-0.10.2-py2.py3-none-any.whl (16 kB)
Building wheels for collected packages: Mako, PyYAML
  Building wheel for Mako (setup.py) ... done
  Created wheel for Mako: filename=Mako-1.1.4-py2.py3-none-any.whl size=75675 sha256=5d1005b7e47e9e0affe8164ab88bb701cfe62e7a5d1140459e804bb6601a335b
  Stored in directory: /root/.cache/pip/wheels/3c/ee/c2/9651c6b977f9d2a1bb766970d190f71213e2ca47b36d8dc488
  Building wheel for PyYAML (setup.py) ... done
  Created wheel for PyYAML: filename=PyYAML-5.3.1-cp36-cp36m-linux_x86_64.whl size=44621 sha256=b86fdf44e8f4e2d82fd712d7b045a3ea53ef776088b5476493947e0c8e726f22
  Stored in directory: /root/.cache/pip/wheels/e5/9d/ad/2ee53cf262cba1ffd8afe1487eef788ea3f260b7e6232a80fc
Successfully built Mako PyYAML
Installing collected packages: urllib3, idna, chardet, certifi, six, ruamel.yaml.clib, requests, pycparser, MarkupSafe, toml, SQLAlchemy, ruamel.yaml, requests-toolbelt, python-editor, python-dateutil, python-box, msgpack, Mako, dnspython, colorama, cffi, PyYAML, python-dotenv, PyMySQL, inflection, domain2idna, cryptography, alembic, PyFunceble-dev
  Running setup.py develop for PyFunceble-dev
Successfully installed Mako-1.1.4 MarkupSafe-1.1.1 PyFunceble-dev PyMySQL-1.0.2 PyYAML-5.3.1 SQLAlchemy-1.3.22 alembic-1.4.3 certifi-2020.12.5 cffi-1.14.4 chardet-4.0.0 colorama-0.4.4 cryptography-3.3.1 dnspython-2.1.0 domain2idna-1.12.0 idna-2.10 inflection-0.5.1 msgpack-1.0.2 pycparser-2.20 python-box-5.2.0 python-dateutil-2.8.1 python-dotenv-0.15.0 python-editor-1.0.4 requests-2.25.1 requests-toolbelt-0.9.1 ruamel.yaml-0.16.12 ruamel.yaml.clib-0.2.2 six-1.15.0 toml-0.10.2 urllib3-1.26.2
(venv) root@www:/tmp/pyfunceble# dig ns1.dns.mypdns.org ns1.dns.mypdns.org +short
95.216.209.53
95.216.209.53
(venv) root@www:/tmp/pyfunceble# dig ns1.dns.mypdns.org ns2.dns.mypdns.org +short
95.216.209.53
116.203.32.67
(venv) root@www:/tmp/pyfunceble# pyfunceble --dns 95.216.209.53 116.203.32.67 --database-type mariadb -f https://raw.githubusercontent.com/Clefspeare13/pornhosts/master/submit_here/hosts.txt --local -w 20 -c -h
Traceback (most recent call last):
  File "/tmp/pyfunceble/PyFunceble/config/loader.py", line 59, in <module>
    import importlib.resources as package_resources
ModuleNotFoundError: No module named 'importlib.resources'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/pyfunceble/venv/bin/pyfunceble", line 33, in <module>
    sys.exit(load_entry_point('PyFunceble-dev', 'console_scripts', 'pyfunceble')())
  File "/tmp/pyfunceble/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 473, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/tmp/pyfunceble/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2843, in load_entry_point
    return ep.load()
  File "/tmp/pyfunceble/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2447, in load
    return self.resolve()
  File "/tmp/pyfunceble/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2453, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/tmp/pyfunceble/PyFunceble/__init__.py", line 56, in <module>
    from PyFunceble.checker.availability.domain import DomainAvailabilityChecker
  File "/tmp/pyfunceble/PyFunceble/checker/availability/domain.py", line 54, in <module>
    import PyFunceble.facility
  File "/tmp/pyfunceble/PyFunceble/facility.py", line 53, in <module>
    from PyFunceble.config.loader import ConfigLoader as config_loader
  File "/tmp/pyfunceble/PyFunceble/config/loader.py", line 61, in <module>
    import importlib_resources as package_resources
ModuleNotFoundError: No module named 'importlib_resources'
```

</details>

## Expected behavior
Not nessecary

## Screenshots
Not needed, it's all in the log

## Versions

**OS:** Ubuntu 18.04 (Virtual image)
**Python Version:** Python 3.6.9
**PyFunceble Version:** 773e5f9

**Comment by spirillen** [comment]
If you uses `pip install pre-commit` you'll also need to install dataclasses as you'll see this message next `ModuleNotFoundError: No module named 'dataclasses'`

`pip3 install dataclasses`

**Comment by funilrys** [comment]
Well, `dataclsses` is in 3.7 (built-in). But not in 3.6.

**Comment by funilrys** [comment]
@spirillen Can you document that if people want to use it with Python 3.6, they need to install https://pypi.org/project/importlib-resources/ manually?

I'm not going to handle this manually. Dropping, 3.6 will be done later (probably next week) but not this night.

**Comment by spirillen** [comment]
Added to the <https://github.com/spirillen/PyFunceble/issues/38> ToDo

**Comment by funilrys** [comment]
Closing as this behavior is now doucmented.
