### ISSUE TITLE
preload disables the -f protocol://

### ISSUE THREAD

**Issue by spirillen** [funilrys/PyFunceble#197]
## Bug description
```shell
pyfunceble -f 'https://gitlab.com/ZeroDot1/CoinBlockerLists/-/raw/master/list.txt' --dns 192.168.1.1 --http -c --preload                     

Started preloading of /var/storage01/repos/github/pyfunceble/list.txt...
Fatal Error: [Errno 2] No such file or directory: '/var/storage01/repos/github/pyfunceble/https:/gitlab.com/ZeroDot1/CoinBlockerLists/-/raw/master/list.txt'
```

VS

```shell
pyfunceble -f 'https://gitlab.com/ZeroDot1/CoinBlockerLists/-/raw/master/list.txt' --dns 192.168.1.1 --http 

Subject                                                                                              Status      Source     Expiration Date   HTTP Code  Checker      
---------------------------------------------------------------------------------------------------- ----------- ---------- ----------------- ---------- -------------
0-0.0-0.00003.04.openvpn.cloud.api.btcchina.com                                                      INACTIVE    STDLOOKUP  Unknown           Unknown    AVAILABILITY 
0-0-sz.inc.antpool.com                                                                               INACTIVE    STDLOOKUP  Unknown           Unknown    AVAILABILITY 
0-0.0-0.00003.04.openvpn.cloud.cloud.btcchina.com                                                    INACTIVE    STDLOOKUP  Unknown           Unknown    AVAILABILITY 
0-0.0-0.00003.04.openvpn.cloud.cloud.api.btcchina.com                                                INACTIVE    STDLOOKUP  Unknown           Unknown    AVAILABILITY 
0-0.0-0.00003.04.openvpn.cloud.openvpn.btcchina.com                                                  INACTIVE    STDLOOKUP  Unknown           Unknown    AVAILABILITY 
0-0.00002.04.openvpn.cloud.api.btcchina.com                                                          INACTIVE    STDLOOKUP  Unknown           Unknown    AVAILABILITY 
0-0.00002.04.openvpn.cloud.cloud.api.btcchina.com                                                    INACTIVE    STDLOOKUP  Unknown           Unknown    AVAILABILITY 
0-0.00002.04.openvpn.cloud.cloud.btcchina.com                                                        INACTIVE    STDLOOKUP  Unknown           Unknown    AVAILABILITY 
^C
Thank you for using PyFunceble!
Process pyfunceble_tester_worker_1:
Process pyfunceble_tester_worker_2:
Process pyfunceble_producer_worker_1:
```

```
pyfunceble -f 'https://gitlab.com/ZeroDot1/CoinBlockerLists/-/raw/master/list.txt' --dns 192.168.1.1 --http -c 

Subject                                                                                              Status      Source     Expiration Date   HTTP Code  Checker      
---------------------------------------------------------------------------------------------------- ----------- ---------- ----------------- ---------- -------------
0-0.0-0.00003.04.openvpn.cloud.api.btcchina.com                                                      INACTIVE    STDLOOKUP  Unknown           Unknown    AVAILABILITY 
^C
Thank you for using PyFunceble!
Share your experience on Twitter with #PyFunceble or @PyFunceble!
Process pyfunceble_tester_worker_2:
Process pyfunceble_tester_worker_1:
Process pyfunceble_producer_worker_1
```
## Modifications under `.PyFunceble.yaml`

```yml
    autocontinue: false
    cooldown_time: 0.0
    db_type: mariadb
        all: true
        hosts: false
        hierarchical: true
dns:
    protocol: UDP
    server:
    - 185.109.89.254
    - 130.225.244.166
    - 130.226.161.34
    - 185.38.24.52
    - 198.180.150.12
    - 94.126.178.9
    - 192.168.1.1
    - 91.239.100.100
    - 89.233.43.71
    - 198.180.150.12
    - 185.38.24.52
    - 130.226.161.34
    - 95.216.209.53
    - 116.203.32.67
    - 192.168.1.2
    - 192.168.1.3
    - 192.168.1.4
    - 192.168.1.5
    - 192.168.1.53
```

## Reproduction

See description remote-location becomes local stored file

## Expected behavior
Hmm let's see...

## Versions

**OS:** Ubuntu 20.04 + virtualenv
**Python Version:** 3.9.1
**PyFunceble Version:** 0d5e5450..365d1332  dev

## Additional context
was going to reproduce https://github.com/funilrys/PyFunceble/issues/134#issuecomment-761691545

## output/__pyfunceble_loggging__/
```log
[2021-01-17 05:03:10,089 | CRITICAL | /var/storage01/repos/github/pyfunceble/PyFunceble/cli/system/launcher.py:858@start | TPID139747686434624:MainThread | PPID45820:MainProcess]:
Fatal error.
Traceback (most recent call last):
  File "/var/storage01/repos/github/pyfunceble/PyFunceble/cli/system/launcher.py", line 844, in start
    self.fill_to_test_queue_from_protocol()
  File "/var/storage01/repos/github/pyfunceble/PyFunceble/cli/system/launcher.py", line 569, in fill_to_test_queue_from_protocol
    handle_file(protocol)
  File "/var/storage01/repos/github/pyfunceble/PyFunceble/cli/system/launcher.py", line 458, in handle_file
    self.file_preloader.set_protocol(protocol).start(
  File "/var/storage01/repos/github/pyfunceble/PyFunceble/cli/file_preloader.py", line 174, in wrapper
    return func(self, *args, **kwargs)  # pylint: disable=not-callable
  File "/var/storage01/repos/github/pyfunceble/PyFunceble/cli/file_preloader.py", line 194, in wrapper
    return func(self, *args, **kwargs)  # pylint: disable=not-callable
  File "/var/storage01/repos/github/pyfunceble/PyFunceble/cli/file_preloader.py", line 338, in start
    self.__description["hash"] = HashHelper().hash_file(file_helper.path)
  File "/var/storage01/repos/github/pyfunceble/PyFunceble/helpers/hash.py", line 140, in hash_file
    with FileHelper(file_path).open("rb") as file_stream:
  File "/var/storage01/repos/github/pyfunceble/PyFunceble/helpers/file.py", line 202, in open
    return open(self.path, *args, **kwargs)
FileNotFoundError: [Errno 2] No such file or directory: '/var/storage01/repos/github/pyfunceble/https:/gitlab.com/ZeroDot1/CoinBlockerLists/-/raw/master/list.txt'
```

**Comment by spirillen** [comment]
pyfunceble -f coinblocker.txt --dns 192.168.1.1 --http -c --preload (MariaDB)

As it preload very very slow, after about 10 minutes only 1123 records in `pyfunceble_continue`

**Comment by spirillen** [comment]
Retested = done
