### ISSUE TITLE
--rpz Fatal Error: <value> should not be empty.

### ISSUE THREAD

**Issue by spirillen** [funilrys/PyFunceble#206]
## Bug description
```python
cat output/__pyfunceble_loggging__/critical.log 
[2021-01-24 15:42:41,897 | CRITICAL | $HOME/miniconda/envs/pyfunceble4/lib/python3.9/site-packages/PyFunceble/cli/system/launcher.py:855@start | TPID139926900918080:MainThread | PPID191613:MainProcess]:
Fatal error.
Traceback (most recent call last):
  File "$HOME/miniconda/envs/pyfunceble4/lib/python3.9/site-packages/PyFunceble/cli/system/launcher.py", line 839, in start
    self.fill_to_test_queue_from_protocol()
  File "$HOME/miniconda/envs/pyfunceble4/lib/python3.9/site-packages/PyFunceble/cli/system/launcher.py", line 569, in fill_to_test_queue_from_protocol
    handle_file(protocol)
  File "$HOME/miniconda/envs/pyfunceble4/lib/python3.9/site-packages/PyFunceble/cli/system/launcher.py", line 501, in handle_file
    for subject in get_subjects_from_line(
  File "$HOME/miniconda/envs/pyfunceble4/lib/python3.9/site-packages/PyFunceble/cli/utils/testing.py", line 239, in get_subjects_from_line
    netloc = url2netloc.set_data_to_convert(subject).get_converted()
  File "$HOME/miniconda/envs/pyfunceble4/lib/python3.9/site-packages/PyFunceble/converter/base.py", line 94, in set_data_to_convert
    self.data_to_convert = value
  File "$HOME/miniconda/envs/pyfunceble4/lib/python3.9/site-packages/PyFunceble/converter/url2netloc.py", line 80, in data_to_convert
    raise ValueError("<value> should not be empty.")
ValueError: <value> should not be empty.
```

## Modifications under `.PyFunceble.yaml`

doesn't matter...

## Reproduction

pyfunceble -f test_data/rpz.mypdns.cloud.list --rpz -ex --logging-level critical

https://github.com/dns-test/rpz.mypdns.cloud/actions

## Expected behavior
:thinking: 

## Screenshots
ot this time

## Versions

**OS:** for example Arch Linux (5.0.5-arch1-1-ARCH)
**Python Version:** for example 3.6.5
**PyFunceble Version:** for example 1.2.0

**Comment by funilrys** [comment]
Just for the clarification @spirillen, was the `test_data/rpz.mypdns.cloud.list` file different at that time?

**Comment by spirillen** [comment]
> Just for the clarification @spirillen, was the `test_data/rpz.mypdns.cloud.list` file different at that time?

There have been some removals, as entries have been moved to the right locations as adware/tracking etc. but we are only talking about 5-800 records in total as they have been wildcarded and therefor lowered to 2 records :100: (the zone holds about 630-650.000 records) So the changes are insignificant.

**Comment by funilrys** [comment]
Just wanted to know before writing the patch. I couldn't reproduce but wrote the patch which theoretically fixes the issue.

**Comment by spirillen** [comment]
And it seems to have fixed the issue :smiley: 

I think the `empty record` can be a leftover from drill, but I'm not sure, as if I do it locally, everything looks right (except from a double SOA record)

However we are still waiting for a successful run at https://github.com/dns-test/rpz.mypdns.cloud/actions to make the true answer.

But as the source contains over 630.000 records, it's a bit tricky to get it to make a run with output for commit.

**Comment by BARMOLEY007** [comment]
7529

Вс, 24 янв. 2021, 20:46 spirillen <notifications@github.com>:
