### ISSUE TITLE
got a response from ('130.225.244.166', 53) instead of ('185.109.89.254', 53)

### ISSUE THREAD

**Issue by spirillen** [funilrys/PyFunceble#222]
## Bug description
Fatal Error: got a response from ('130.225.244.166', 53) instead of ('185.109.89.254', 53)

## Modifications under `.PyFunceble.yaml`

None

## Reproduction

1. Run <https://github.com/Clefspeare13/pornhosts/blob/master/toolbox/domain-test.sh>
2. Run with `-ex -h -a --hierarchical --database-type mariadb --dns 185.109.89.254 130.225.244.166 130.226.161.34 185.38.24.52 198.180.150.12 --complements -w (40|50)`

## Screenshots
![image](https://user-images.githubusercontent.com/44526987/108190048-b893aa80-7111-11eb-9780-7d164e9fdff0.png)

## Versions

**OS:** Ubuntu 20.04 + Conda
**Python Version:** 3.9.1
**PyFunceble Version:** 4.0.0b22.dev

## Additional context
Seen this error at least twice

**Comment by funilrys** [comment]
I tried to find where this is coming from, and I can't locate it.

**Comment by spirillen** [comment]
I'll run it with the `--loggin-level debug` next time, we will then find a sweetspot to upload the complete output, (BIIIIG data) as it might be near the end of the test, do to the time before failure.

**Comment by funilrys** [comment]
My last commit will always provide a traceback when such a thing happens.

**Comment by spirillen** [comment]
![image](https://user-images.githubusercontent.com/44526987/109056959-70602380-76e1-11eb-9cc5-bb50562d4707.png)

```python
Traceback (most recent call last):
  File "/$HOME/miniconda/envs/pyfunceble4/lib/python3.9/site-packages/PyFunceble/cli/system/launcher.py", line 845, in start
    self.stop_and_wait_for_all_manager()
  File "/$HOME/miniconda/envs/pyfunceble4/lib/python3.9/site-packages/PyFunceble/cli/system/launcher.py", line 783, in stop_and_wait_for_all_manager
    self.tester_process_manager.wait()
  File "/$HOME/miniconda/envs/pyfunceble4/lib/python3.9/site-packages/PyFunceble/cli/processes/base.py", line 288, in wait
    raise worker_error
dns.query.UnexpectedSource: got a response from ('130.226.161.34', 53) instead of ('185.109.89.254', 53)
```

remote: Resolving deltas: 100% (2/2), completed with 2 local objects.
remote: error: GH001: Large files detected. You may want to try Git Large File Storage - https://git-lfs.github.com.
remote: error: Trace: bf03f2169e5e02d3f29bbb117cacf6320debab1b3e0e96cd23744daaa4f7e85a
remote: error: See http://git.io/iEPt8g for more information.
remote: error: File test_results/output/__pyfunceble_loggging__/info.log is 379.39 MB; this exceeds GitHub's file size limit of 100.00 MB
remote: error: File test_results/output/__pyfunceble_loggging__/debug.log is 522.61 MB; this exceeds GitHub's file size limit of 100.00 MB
To github.com:Clefspeare13/pornhosts.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'github.com:Clefspeare13/pornhosts.git

**Comment by spirillen** [comment]
New error occurred.

Same script...
Test line: `-ex -a --hierarchical --database-type mariadb --dns 185.109.89.254 130.225.244.166 130.226.161.34 185.38.24.52 --complements -w 30 --trust-dns-server --follow-server-order`

<details><summary>error log</summary>

```python
www.yetisblog.com                                                                                    ACTIVE      NETINFO    Unknown           Unknown    AVAILABILITY 
Fatal Error: got a response from ('130.225.244.166', 53) instead of ('185.109.89.254', 53)
Traceback (most recent call last):
  File "/home/joakim/miniconda/envs/pyfunceble4/lib/python3.9/site-packages/PyFunceble/cli/system/launcher.py", line 862, in start
    self.stop_and_wait_for_all_manager()
  File "/home/joakim/miniconda/envs/pyfunceble4/lib/python3.9/site-packages/PyFunceble/cli/system/launcher.py", line 800, in stop_and_wait_for_all_manager
    self.tester_process_manager.wait()
  File "/home/joakim/miniconda/envs/pyfunceble4/lib/python3.9/site-packages/PyFunceble/cli/processes/base.py", line 288, in wait
    raise worker_error
dns.query.UnexpectedSource: got a response from ('130.225.244.166', 53) instead of ('185.109.89.254', 53)

Exception during reset or similar
Traceback (most recent call last):
  File "/home/joakim/miniconda/envs/pyfunceble4/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 749, in _rollback_impl
    self.engine.dialect.do_rollback(self.connection)
  File "/home/joakim/miniconda/envs/pyfunceble4/lib/python3.9/site-packages/sqlalchemy/dialects/mysql/base.py", line 2509, in do_rollback
    dbapi_connection.rollback()
  File "/home/joakim/miniconda/envs/pyfunceble4/lib/python3.9/site-packages/pymysql/connections.py", line 479, in rollback
    self._execute_command(COMMAND.COM_QUERY, "ROLLBACK")
  File "/home/joakim/miniconda/envs/pyfunceble4/lib/python3.9/site-packages/pymysql/connections.py", line 793, in _execute_command
    raise err.InterfaceError(0, "")
pymysql.err.InterfaceError: (0, '')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/joakim/miniconda/envs/pyfunceble4/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 697, in _finalize_fairy
    fairy._reset(pool)
  File "/home/joakim/miniconda/envs/pyfunceble4/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 891, in _reset
    self._reset_agent.rollback()
  File "/home/joakim/miniconda/envs/pyfunceble4/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1751, in rollback
    self._do_rollback()
  File "/home/joakim/miniconda/envs/pyfunceble4/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1789, in _do_rollback
    self.connection._rollback_impl()
  File "/home/joakim/miniconda/envs/pyfunceble4/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 751, in _rollback_impl
    self._handle_dbapi_exception(e, None, None, None, None)
  File "/home/joakim/miniconda/envs/pyfunceble4/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1510, in _handle_dbapi_exception
    util.raise_(
  File "/home/joakim/miniconda/envs/pyfunceble4/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/home/joakim/miniconda/envs/pyfunceble4/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 749, in _rollback_impl
    self.engine.dialect.do_rollback(self.connection)
  File "/home/joakim/miniconda/envs/pyfunceble4/lib/python3.9/site-packages/sqlalchemy/dialects/mysql/base.py", line 2509, in do_rollback
    dbapi_connection.rollback()
  File "/home/joakim/miniconda/envs/pyfunceble4/lib/python3.9/site-packages/pymysql/connections.py", line 479, in rollback
    self._execute_command(COMMAND.COM_QUERY, "ROLLBACK")
  File "/home/joakim/miniconda/envs/pyfunceble4/lib/python3.9/site-packages/pymysql/connections.py", line 793, in _execute_command
    raise err.InterfaceError(0, "")
sqlalchemy.exc.InterfaceError: (pymysql.err.InterfaceError) (0, '')
(Background on this error at: http://sqlalche.me/e/13/rvf5)
```

</details>

**Comment by spirillen** [comment]
Found a relation to this issue, it's a odd vs even.

Every time i use a odd number, the job fails ie 5

When I use a even number the job succeds ie 6 

^:^

**Comment by funilrys** [comment]
This looks like a false positive issue. What I mean: dnspython is returning this issue because it queried to `185.109.89.254` but it got a response from `130.225.244.166`. 

Tell me, are you using the UDP protocol?

From [the documentation](https://dnspython.readthedocs.io/en/latest/_modules/dns/query.html) of dnspython:

```
class UnexpectedSource(dns.exception.DNSException):
    """A DNS query response came from an unexpected address or port."""
```

**Comment by spirillen** [comment]
Yeps, all UDP.

**Comment by funilrys** [comment]
What about switching to TCP ?

**Comment by spirillen** [comment]
Would be non-standard.... durable, but not std

**Comment by funilrys** [comment]
This is an issue for dnspython. But actually, it's a good thing. dnspython just checks that the answer comes from the one requested. 

Therefore, I'm closing this.
