### ISSUE TITLE
Fatal Error: Invalid IPv6 URL

### ISSUE THREAD

**Issue by Yuki2718** [funilrys/PyFunceble#226]
## Bug description
Every time I scan for my Yuki's uBlock Japanese filters (jp-filters.txt on my repo) it returns the error above but at different point (due to database cache, maybe). It doesn't occur for other files so something on my list may be interpreted as IPv6 address?

## Modifications under `.PyFunceble.yaml`

None AFAIK

## Reproduction

1. Get the list of mine
2. Run `PyFunceble --adblock -f filepath`

## Expected behavior
Since I do not use any IPv6 address in my list, the error should not occur.

## Screenshots

![error](https://user-images.githubusercontent.com/58900598/109994674-e05d5200-7d50-11eb-9645-079f44527fda.png)

## Versions

**OS:** Windows 10
**Python Version:** 3.8.8 / conda 4.9.2
**PyFunceble Version:** 4.0.0b19.dev

**Comment by spirillen** [comment]
Reproduced with conda, and the location is diffrent each time as well, however I noticed that it happent to one of the `blogimg.jp` for me each time.

If you @Yuki2718  take a look at the exact error location is there a pattern of ?

```
||blogimg.jp/beelzeboulxxx/imgs/7/c/7cca15f0.gif$domain=beelzeboulxxx.com
||blogimg.jp/anigam-eloelog2ch/imgs/4/7/$domain=blog.livedoor.jp
||blogimg.jp/aomuke_please-oppao/imgs/3/b/3bca2ae0-$domain=oppao.blog.jp
```

Test string:
```
pyfunceble --database-type mariadb --adblock -f https://raw.githubusercontent.com/Yuki2718/adblock/master/japanese/jp-filters.txt
```

```
blogimg.jp                                                                                           INACTIVE    STDLOOKUP 
Fatal Error: Invalid IPv6 URL
Traceback (most recent call last):
  File "/home/joakim/miniconda/envs/pyfunceble4/lib/python3.9/site-packages/PyFunceble/cli/system/launcher.py", line 860, in start
    self.fill_to_test_queue_from_protocol()
  File "/home/joakim/miniconda/envs/pyfunceble4/lib/python3.9/site-packages/PyFunceble/cli/system/launcher.py", line 589, in fill_to_test_queue_from_protocol
    handle_file(protocol)
  File "/home/joakim/miniconda/envs/pyfunceble4/lib/python3.9/site-packages/PyFunceble/cli/system/launcher.py", line 521, in handle_file
    for subject in get_subjects_from_line(
  File "/home/joakim/miniconda/envs/pyfunceble4/lib/python3.9/site-packages/PyFunceble/cli/utils/testing.py", line 220, in get_subjects_from_line
    adblock_inputline2subject.set_aggressive(
  File "/home/joakim/miniconda/envs/pyfunceble4/lib/python3.9/site-packages/PyFunceble/converter/adblock_input_line2subject.py", line 351, in get_converted
    result.extend(self.__decode_v3(self.data_to_convert))
  File "/home/joakim/miniconda/envs/pyfunceble4/lib/python3.9/site-packages/PyFunceble/converter/adblock_input_line2subject.py", line 316, in __decode_v3
    result.extend(self.__format_decoded(rematch))
  File "/home/joakim/miniconda/envs/pyfunceble4/lib/python3.9/site-packages/PyFunceble/converter/adblock_input_line2subject.py", line 183, in __format_decoded
    return cls.__format_decoded(
  File "/home/joakim/miniconda/envs/pyfunceble4/lib/python3.9/site-packages/PyFunceble/converter/adblock_input_line2subject.py", line 183, in __format_decoded
    return cls.__format_decoded(
  File "/home/joakim/miniconda/envs/pyfunceble4/lib/python3.9/site-packages/PyFunceble/converter/adblock_input_line2subject.py", line 190, in __format_decoded
    DomainSyntaxChecker(data).is_valid() or IPSyntaxChecker(data).is_valid()
  File "/home/joakim/miniconda/envs/pyfunceble4/lib/python3.9/site-packages/PyFunceble/checker/syntax/domain.py", line 84, in __init__
    super().__init__(subject)
  File "/home/joakim/miniconda/envs/pyfunceble4/lib/python3.9/site-packages/PyFunceble/checker/syntax/domain_base.py", line 99, in __init__
    super().__init__(subject)
  File "/home/joakim/miniconda/envs/pyfunceble4/lib/python3.9/site-packages/PyFunceble/checker/syntax/base.py", line 84, in __init__
    super().__init__(subject=subject, db_session=db_session)
  File "/home/joakim/miniconda/envs/pyfunceble4/lib/python3.9/site-packages/PyFunceble/checker/base.py", line 93, in __init__
    self.subject = subject
  File "/home/joakim/miniconda/envs/pyfunceble4/lib/python3.9/site-packages/PyFunceble/checker/syntax/domain_base.py", line 110, in wrapper
    return func(self, *args, **kwargs)  # pylint: disable=not-callable
  File "/home/joakim/miniconda/envs/pyfunceble4/lib/python3.9/site-packages/PyFunceble/checker/syntax/domain_base.py", line 122, in wrapper
    result = func(self, *args, **kwargs)  # pylint: disable=not-callable
  File "/home/joakim/miniconda/envs/pyfunceble4/lib/python3.9/site-packages/PyFunceble/checker/syntax/domain_base.py", line 147, in subject
    super(DomainSyntaxCheckerBase, self.__class__).subject.fset(self, value)
  File "/home/joakim/miniconda/envs/pyfunceble4/lib/python3.9/site-packages/PyFunceble/checker/base.py", line 108, in wrapper
    result = func(self, *args, **kwargs)  # pylint: disable=not-callable
  File "/home/joakim/miniconda/envs/pyfunceble4/lib/python3.9/site-packages/PyFunceble/checker/base.py", line 194, in subject
    self.idna_subject = domain2idna.domain2idna(value)
  File "/home/joakim/.local/lib/python3.9/site-packages/domain2idna/__init__.py", line 66, in domain2idna
    return Converter(subject, original_encoding=encoding).get_converted()
  File "/home/joakim/.local/lib/python3.9/site-packages/domain2idna/converter.py", line 152, in get_converted
    return self.__get_converted(self.subject)
  File "/home/joakim/.local/lib/python3.9/site-packages/domain2idna/converter.py", line 137, in __get_converted
    [
  File "/home/joakim/.local/lib/python3.9/site-packages/domain2idna/converter.py", line 138, in <listcomp>
    self.convert_to_idna(x, original_encoding=self.encoding)
  File "/home/joakim/.local/lib/python3.9/site-packages/domain2idna/converter.py", line 100, in convert_to_idna
    parsed_url = urlparse(subject)
  File "/home/joakim/miniconda/envs/pyfunceble4/lib/python3.9/urllib/parse.py", line 390, in urlparse
    splitresult = urlsplit(url, scheme, allow_fragments)
  File "/home/joakim/miniconda/envs/pyfunceble4/lib/python3.9/urllib/parse.py", line 476, in urlsplit
    raise ValueError("Invalid IPv6 URL")
ValueError: Invalid IPv6 URL
```

**Comment by funilrys** [comment]
Closing.

This should be fixed by PyFuncebe `v4.0.0b33`. Feel free to upgrade, test, and come back here it is still not working.

**Comment by spirillen** [comment]
I'll say it is fixed

```
Status      Percentage   Amount      
----------- ------------ ------------
ACTIVE      94%          13837       
INACTIVE    5%           767         
INVALID     1%           67
```

**Comment by Yuki2718** [comment]
I can't install ver 4.x via `pip3 install --user --pre pyfunceble-dev`, `PyFunceble --version` says my version is 3.3.9.

**Comment by funilrys** [comment]
@Yuki2718 What is your current PATH ?

**Comment by funilrys** [comment]
I will try to uninstall it completely and try to reinstall it. 🤔

**Comment by Yuki2718** [comment]
@funilrys You mean environment variable? I set `C:\Users\Username\AppData\Roaming\Python\Python38\Scripts\` and `C:\Users\Username\AppData\Roaming\Python\Python39\Scripts\` tho actual Python version is 3.8.

> I will try to uninstall it completely and try to reinstall it. 🤔

I uninstalled miniconda completely and reinstalled, the same. Is Python 3.9 mandatory?

**Comment by funilrys** [comment]
No Python version is mandatory as long as it is greater than 3.7.

Mhh that's weird ... `pip3 install --user --pre pyfunceble-dev` is correct.

Can you check where is PyFunceble located through the following?

``` 
$ python
Python 3.9.2 (default, Feb 20 2021, 18:40:11) 
[GCC 10.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import PyFunceble
>>> PyFunceble.__file__
'/[path-to]/PyFunceble/__init__.py'
>>> 
```

**Comment by Yuki2718** [comment]
It returned `'C:\\Users\\Username\\AppData\\Roaming\\Python\\Python38\\site-packages\\PyFunceble\\__init__.py'`

**Comment by Yuki2718** [comment]
Thx, 4.0.0b36.dev is now installed!
