### ISSUE TITLE
BUG: Logo generation causes error in PyPy 3

### ISSUE THREAD

**Issue by T145** [funilrys/PyFunceble#264]
## Description

```
(pypy) # pyfunceble -d example.com
Fatal Error: 'ascii' codec can't encode characters in position 20-26: ordinal not in range(128)
Traceback (most recent call last):
  File "/pypy/site-packages/PyFunceble/cli/system/launcher.py", line 893, in start
    self.print_home_ascii()
  File "/pypy/site-packages/PyFunceble/cli/system/launcher.py", line 264, in print_home_ascii
    print(PyFunceble.cli.utils.ascii_logo.get_home_representation())
  File "/pypy/site-packages/colorama/ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "/pypy/site-packages/colorama/ansitowin32.py", line 164, in write
    self.wrapped.write(text)
  File "/usr/lib/pypy3/lib-python/3/encodings/ascii.py", line 22, in encode
    return codecs.ascii_encode(input, self.errors)[0]
UnicodeEncodeError: 'ascii' codec can't encode characters in position 20-26: ordinal not in range(128)
```

## Configuration

N/A

## Reproduction

```
virtualenv -p pypy3 pypy && chmod +x ./pypy/bin/activate && . /pypy/bin/activate && pip install -U pip wheel && pip install --upgrade --pre pyfunceble-dev
```
Then run the command from the description.

## Expected behavior

No errors.

## Screenshots

N/A

## Versions

```
(pypy) # python --version
Python 3.7.10 (7.3.5+dfsg-2, Jun 04 2021, 05:13:55)
[PyPy 7.3.5 with GCC 10.3.0]
(pypy) # cat /etc/os-release
PRETTY_NAME="Ubuntu 21.10"
NAME="Ubuntu"
VERSION_ID="21.10"
VERSION="21.10 (Impish Indri)"
VERSION_CODENAME=impish
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=impish
(pypy) # pyfunceble --version
pyfunceble 4.0.2b1.dev (Blue Duckling: Chestnut)
```

## Additional context

I'd just go ahead and remove logo generation entirely. An abridged license header has the same affect.

**Comment by spirillen** [comment]
Thanks for the report, and I do understand you would like to run this script within pypy, however I have never been able to do this my self either, going back to early 3.x.  I'm not sure pypy is or will be supported by @funilrys .
