### ISSUE TITLE
BUG: Error while only scanning against HTTP return codes in PyPy3

### ISSUE THREAD

**Issue by T145** [funilrys/PyFunceble#269]
## Description

```
Process pyfunceble_tester_worker_6:
Traceback (most recent call last):
  File "/usr/lib/pypy3/lib-python/3/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/pypy/site-packages/PyFunceble/cli/processes/workers/base.py", line 388, in run
    raise exception
  File "/pypy/site-packages/PyFunceble/cli/processes/workers/base.py", line 366, in run
    result = self.target(consumed)
  File "/pypy/site-packages/PyFunceble/cli/processes/workers/tester.py", line 275, in target
    self.testing_object.set_subject(test_dataset["idna_subject"])
  File "/pypy/site-packages/PyFunceble/checker/base.py", line 157, in wrapper
    return func(self, *args, **kwargs)  # pylint: disable=not-callable
  File "/pypy/site-packages/PyFunceble/checker/base.py", line 182, in wrapper
    result = func(self, *args, **kwargs)  # pylint: disable=not-callable
  File "/pypy/site-packages/PyFunceble/checker/availability/domain_and_ip.py", line 109, in query_status
    result = query_object.query_status()
  File "/pypy/site-packages/PyFunceble/checker/base.py", line 157, in wrapper
    return func(self, *args, **kwargs)  # pylint: disable=not-callable
  File "/pypy/site-packages/PyFunceble/checker/base.py", line 182, in wrapper
    result = func(self, *args, **kwargs)  # pylint: disable=not-callable
  File "/pypy/site-packages/PyFunceble/checker/availability/domain.py", line 182, in query_status
    ExtraRulesHandler(self.status).start()
  File "/pypy/site-packages/PyFunceble/checker/availability/extra_rules.py", line 132, in wrapper
    return func(self, *args, **kwargs)  # pylint: disable=not-callable
  File "/pypy/site-packages/PyFunceble/checker/availability/extra_rules.py", line 343, in start
    self.__handle_active2inactive()
  File "/pypy/site-packages/PyFunceble/checker/availability/extra_rules.py", line 324, in __handle_active2inactive
    self.__regex_registry_handler(self.regex_active2inactive)
  File "/pypy/site-packages/PyFunceble/checker/availability/extra_rules.py", line 221, in __regex_registry_handler
    element()
  File "/pypy/site-packages/PyFunceble/checker/availability/extra_rules.py", line 313, in __handle_fc2_dot_com
    if "error.fc2.com" in req.headers["Location"]:
  File "/pypy/site-packages/requests/structures.py", line 54, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'location'
Process pyfunceble_tester_worker_1:
Traceback (most recent call last):
  File "/usr/lib/pypy3/lib-python/3/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/pypy/site-packages/PyFunceble/cli/processes/workers/base.py", line 388, in run
    raise exception
  File "/pypy/site-packages/PyFunceble/cli/processes/workers/base.py", line 366, in run
    result = self.target(consumed)
  File "/pypy/site-packages/PyFunceble/cli/processes/workers/tester.py", line 275, in target
    self.testing_object.set_subject(test_dataset["idna_subject"])
  File "/pypy/site-packages/PyFunceble/checker/base.py", line 157, in wrapper
    return func(self, *args, **kwargs)  # pylint: disable=not-callable
  File "/pypy/site-packages/PyFunceble/checker/base.py", line 182, in wrapper
    result = func(self, *args, **kwargs)  # pylint: disable=not-callable
  File "/pypy/site-packages/PyFunceble/checker/availability/domain_and_ip.py", line 109, in query_status
    result = query_object.query_status()
  File "/pypy/site-packages/PyFunceble/checker/base.py", line 157, in wrapper
    return func(self, *args, **kwargs)  # pylint: disable=not-callable
  File "/pypy/site-packages/PyFunceble/checker/base.py", line 182, in wrapper
    result = func(self, *args, **kwargs)  # pylint: disable=not-callable
  File "/pypy/site-packages/PyFunceble/checker/availability/domain.py", line 169, in query_status
    self.try_to_query_status_from_http_status_code()
  File "/pypy/site-packages/PyFunceble/checker/availability/base.py", line 870, in try_to_query_status_from_http_status_code
    lookup_result = self.http_status_code_query_tool.get_status_code()
  File "/pypy/site-packages/PyFunceble/query/http_status_code.py", line 125, in wrapper
    return func(self, *args, **kwargs)  # pylint: disable=not-callable
  File "/pypy/site-packages/PyFunceble/query/http_status_code.py", line 344, in get_status_code
    allow_redirects=True,
  File "/pypy/site-packages/PyFunceble/query/requests/requester.py", line 157, in wrapper
    req = getattr(self.session, verb.lower())(*args, **kwargs)
  File "/pypy/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/pypy/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/pypy/site-packages/requests/sessions.py", line 677, in send
    history = [resp for resp in gen]
  File "/pypy/site-packages/requests/sessions.py", line 677, in <listcomp>
    history = [resp for resp in gen]
  File "/pypy/site-packages/requests/sessions.py", line 245, in resolve_redirects
    **adapter_kwargs
  File "/pypy/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/pypy/site-packages/PyFunceble/query/requests/adapter/https.py", line 92, in send
    hostname_ip = self.resolve(parsed_url.hostname)
  File "/pypy/site-packages/PyFunceble/query/requests/adapter/base.py", line 181, in resolve
    return self.resolve_without_cache(hostname)
  File "/pypy/site-packages/PyFunceble/query/requests/adapter/base.py", line 152, in resolve_without_cache
    if not IPSyntaxChecker(hostname).is_valid():
  File "/pypy/site-packages/PyFunceble/checker/base.py", line 154, in wrapper
    f"<self.subject> should be {str}, {type(self.subject)} given."
TypeError: <self.subject> should be <class 'str'>, <class 'NoneType'> given.
Fatal Error: <self.subject> should be <class 'str'>, <class 'NoneType'> given.
Traceback (most recent call last):
  File "/pypy/site-packages/PyFunceble/cli/system/launcher.py", line 918, in start
    self.stop_and_wait_for_all_manager()
  File "/pypy/site-packages/PyFunceble/cli/system/launcher.py", line 855, in stop_and_wait_for_all_manager
    self.tester_process_manager.wait()
  File "/pypy/site-packages/PyFunceble/cli/processes/base.py", line 320, in wait
    raise worker_error
TypeError: <self.subject> should be <class 'str'>, <class 'NoneType'> given.
```

## Configuration

`.PyFunceble.overwrite.yaml`

```
cli_testing:
  max_workers: 8
  autocontinue: True
  inactive_db: False
  whois_db: False
  preload_file: True
  cidr_expand: True

  display_mode:
    percentage: False
    quiet: True
    all: True
    colour: False

  sorting_mode:
    standard: False

  file_generation:
    plain: False

lookup:
  dns: False
  netinfo: False
  special: True
  whois: False
  timeout: 3

dns:
  server:
    - 1.1.1.1
    - 1.0.0.1
    - 8.8.8.8
    - 8.8.4.4
    - 9.9.9.10
    - 9.9.9.9
    - 77.88.8.8
    - 77.88.8.1
    - 208.67.222.222
    - 208.67.220.220

user_agent:
  browser: firefox
```

## Reproduction

https://github.com/T145/san-junipero/commit/5302221cf58534176d5d63110c683a3d4a81258f

Took about 5.5 hours though.

## Expected behavior

No errors

## Versions

Same as before.

**Comment by spirillen** [comment]
Just a little note to one of your confs.

You should leave this one `true` `whois_db: False` for your own sake, otherwise you might get bannen at the NIC servers over time, This value stores a local copy of the WHOIS data and are looked up before quering the NIC server.

**Comment by T145** [comment]
Shouldn't disabling the `whois` lookup function prevent querying WHOIS data?

**Comment by funilrys** [comment]
`cli_testing.whois_db` is ignored when `lookup.whois` is not set to `True`.

**Comment by spirillen** [comment]
Just spotted a thing with your default configuration I would like to point your attention to.

```
dns:
  server:
    - 1.1.1.1
    - 1.0.0.1
    - 8.8.8.8
    - 8.8.4.4
    - 9.9.9.9 (Quad9)
    - 208.67.222.222 (OpenDNS)
    - 208.67.220.220 (OpenDNS)
```

These dns servers are **not** returning trustworthy results regarding the question for testing availability of a record as they all uses some forms of filter.

Article for filtering: https://mypdns.org/mypdns/support/-/issues/247 <kbd>control + f</kbd> `CloudFlare`

A neutral list for not manipulated DNS servers (work in progress) https://mypdns.org/-/snippets/41
for your choices of yandex DNS servers I do not have any information, in relation whether they can be trusted with there answers.

**Comment by T145** [comment]
I'm aware: those were chosen because of their speed predominately. Are domains not tested against each provided DNS?

**Comment by funilrys** [comment]
@T145, if you choose to set `dns.trust_server` to `False`, PyFunceble will test against each provided DNS Server.
