### ISSUE TITLE
BUG: KeyError: 'location'

### ISSUE THREAD

**Issue by spirillen** [funilrys/PyFunceble#271]
## Description

```python
m.juggsarea.com                                                                                      ACTIVE      DNSLOOKUP  Unknown           302        AVAILABILITY 
Process pyfunceble_tester_worker_4:
Traceback (most recent call last):
  File "$HOME/miniconda/envs/pyfunceblecp/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "$HOME/.local/lib/python3.9/site-packages/PyFunceble/cli/processes/workers/base.py", line 388, in run
    raise exception
  File "$HOME/.local/lib/python3.9/site-packages/PyFunceble/cli/processes/workers/base.py", line 366, in run
    result = self.target(consumed)
  File "$HOME/.local/lib/python3.9/site-packages/PyFunceble/cli/processes/workers/tester.py", line 275, in target
    self.testing_object.set_subject(test_dataset["idna_subject"])
  File "$HOME/.local/lib/python3.9/site-packages/PyFunceble/checker/base.py", line 157, in wrapper
    return func(self, *args, **kwargs)  # pylint: disable=not-callable
  File "$HOME/.local/lib/python3.9/site-packages/PyFunceble/checker/base.py", line 182, in wrapper
    result = func(self, *args, **kwargs)  # pylint: disable=not-callable
  File "$HOME/.local/lib/python3.9/site-packages/PyFunceble/checker/availability/domain_and_ip.py", line 109, in query_status
    result = query_object.query_status()
  File "$HOME/.local/lib/python3.9/site-packages/PyFunceble/checker/base.py", line 157, in wrapper
    return func(self, *args, **kwargs)  # pylint: disable=not-callable
  File "$HOME/.local/lib/python3.9/site-packages/PyFunceble/checker/base.py", line 182, in wrapper
    result = func(self, *args, **kwargs)  # pylint: disable=not-callable
  File "$HOME/.local/lib/python3.9/site-packages/PyFunceble/checker/availability/domain.py", line 182, in query_status
    ExtraRulesHandler(self.status).start()
  File "$HOME/.local/lib/python3.9/site-packages/PyFunceble/checker/availability/extra_rules.py", line 132, in wrapper
    return func(self, *args, **kwargs)  # pylint: disable=not-callable
  File "$HOME/.local/lib/python3.9/site-packages/PyFunceble/checker/availability/extra_rules.py", line 343, in start
    self.__handle_active2inactive()
  File "$HOME/.local/lib/python3.9/site-packages/PyFunceble/checker/availability/extra_rules.py", line 324, in __handle_active2inactive
    self.__regex_registry_handler(self.regex_active2inactive)
  File "$HOME/.local/lib/python3.9/site-packages/PyFunceble/checker/availability/extra_rules.py", line 221, in __regex_registry_handler
    element()
  File "$HOME/.local/lib/python3.9/site-packages/PyFunceble/checker/availability/extra_rules.py", line 313, in __handle_fc2_dot_com
    if "error.fc2.com" in req.headers["Location"]:
  File "$HOME/.local/lib/python3.9/site-packages/requests/structures.py", line 54, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'location'
m.mypreciousvirgins.com
```

## Configuration
https://mypdns.org/clefspeare13/pornhosts/-/tree/master/toolbox

## Reproduction

1. git clone https://mypdns.org/clefspeare13/pornhosts/-/tree/master/toolbox.git
2. ./toolbox/domain-test.sh
3. watch the error orrcure several times

## Expected behavior
No Errors

## Versions

**OS:** Ubuntu 20.04

**Python Version:** 3.10

**PyFunceble Version:** 4.0.02b1

**Comment by spirillen** [comment]
This one followed before finishing reporting the first one

```python
11625574.ahcdn.com                                                                                   ACTIVE      DNSLOOKUP  Unknown           403        AVAILABILITY 
Process pyfunceble_tester_worker_2:
Traceback (most recent call last):
  File "$HOME/miniconda/envs/pyfunceblecp/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "$HOME/.local/lib/python3.9/site-packages/PyFunceble/cli/processes/workers/base.py", line 388, in run
    raise exception
  File "$HOME/.local/lib/python3.9/site-packages/PyFunceble/cli/processes/workers/base.py", line 366, in run
    result = self.target(consumed)
  File "$HOME/.local/lib/python3.9/site-packages/PyFunceble/cli/processes/workers/tester.py", line 275, in target
    self.testing_object.set_subject(test_dataset["idna_subject"])
  File "$HOME/.local/lib/python3.9/site-packages/PyFunceble/checker/base.py", line 157, in wrapper
    return func(self, *args, **kwargs)  # pylint: disable=not-callable
  File "$HOME/.local/lib/python3.9/site-packages/PyFunceble/checker/base.py", line 182, in wrapper
    result = func(self, *args, **kwargs)  # pylint: disable=not-callable
  File "$HOME/.local/lib/python3.9/site-packages/PyFunceble/checker/availability/domain_and_ip.py", line 109, in query_status
    result = query_object.query_status()
  File "$HOME/.local/lib/python3.9/site-packages/PyFunceble/checker/base.py", line 157, in wrapper
    return func(self, *args, **kwargs)  # pylint: disable=not-callable
  File "$HOME/.local/lib/python3.9/site-packages/PyFunceble/checker/base.py", line 182, in wrapper
    result = func(self, *args, **kwargs)  # pylint: disable=not-callable
  File "$HOME/.local/lib/python3.9/site-packages/PyFunceble/checker/availability/domain.py", line 182, in query_status
    ExtraRulesHandler(self.status).start()
  File "$HOME/.local/lib/python3.9/site-packages/PyFunceble/checker/availability/extra_rules.py", line 132, in wrapper
    return func(self, *args, **kwargs)  # pylint: disable=not-callable
  File "$HOME/.local/lib/python3.9/site-packages/PyFunceble/checker/availability/extra_rules.py", line 343, in start
    self.__handle_active2inactive()
  File "$HOME/.local/lib/python3.9/site-packages/PyFunceble/checker/availability/extra_rules.py", line 324, in __handle_active2inactive
    self.__regex_registry_handler(self.regex_active2inactive)
  File "$HOME/.local/lib/python3.9/site-packages/PyFunceble/checker/availability/extra_rules.py", line 221, in __regex_registry_handler
    element()
  File "$HOME/.local/lib/python3.9/site-packages/PyFunceble/checker/availability/extra_rules.py", line 311, in __handle_fc2_dot_com
    req = PyFunceble.factory.Requester.get(url, allow_redirects=False)
  File "$HOME/.local/lib/python3.9/site-packages/PyFunceble/query/requests/requester.py", line 157, in wrapper
    req = getattr(self.session, verb.lower())(*args, **kwargs)
  File "$HOME/.local/lib/python3.9/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "$HOME/.local/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "$HOME/.local/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "$HOME/.local/lib/python3.9/site-packages/PyFunceble/query/requests/adapter/http.py", line 118, in send
    return self.fake_response()
  File "$HOME/.local/lib/python3.9/site-packages/PyFunceble/query/requests/adapter/base.py", line 94, in fake_response
    raise PyFunceble.factory.Requester.exceptions.ConnectionError(
requests.exceptions.ConnectionError: Could not resolve.
11779494.ahcdn.com 
```
