### ISSUE TITLE
Bug while testing (INVALID) URLs

### ISSUE THREAD

**Issue by funilrys** [funilrys/PyFunceble#28]
@mitchellkrogza [said](https://github.com/Ultimate-Hosts-Blacklist/dev-center/commit/8e98cd1f7757caa4ca73448513ed927629d54743#commitcomment-33545989):

> Broken builds suddenly - https://travis-ci.org/mitchellkrogza/Phishing-URL-Testing-Database-of-Link-Statuses/jobs/532790699#L365-L366

Full traceback:
```python
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.7.1/bin/PyFunceble", line 10, in <module>
    sys.exit(_command_line())
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/PyFunceble/__init__.py", line 1460, in _command_line
    link_to_test=ARGS.link,
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/PyFunceble/dispatcher.py", line 122, in __init__
    FileCore(url_file_path, "url").read_and_test_file_content()
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/PyFunceble/file_core.py", line 613, in read_and_test_file_content
    self._test_line(line)
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/PyFunceble/file_core.py", line 517, in _test_line
    status = self.__process_test(subject)
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/PyFunceble/file_core.py", line 367, in __process_test
    return self.url(subject)
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/PyFunceble/file_core.py", line 256, in url
    subject, subject_type="file_url", filename=self.file
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/PyFunceble/status.py", line 700, in __init__
    "http_status_code": HTTPCode(self.subject, "url").get(),
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/PyFunceble/http_code.py", line 188, in get
    http_code = self._access()
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/PyFunceble/http_code.py", line 146, in _access
    verify=PyFunceble.CONFIGURATION["verify_ssl_certificate"],
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/requests/api.py", line 101, in head
    return request('head', url, **kwargs)
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/requests/sessions.py", line 519, in request
    prep = self.prepare_request(req)
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/requests/sessions.py", line 462, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/requests/models.py", line 313, in prepare
    self.prepare_url(url, params)
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/requests/models.py", line 387, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '=======': No schema supplied. Perhaps you meant http://=======?
```

**Comment by mitchellkrogza** [comment]
I stopped builds today to add the `--multiprocess` flag, now I'm once again getting `/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.25.2) or chardet (3.0.4) doesn't match a supported version!` > https://travis-ci.org/mitchellkrogza/Phishing-URL-Testing-Database-of-Link-Statuses/builds/533250340#L365

**Comment by funilrys** [comment]
It's just a warning for me :wink: it has no influence with the rest of the logic hehe actually it does not even stop PyFunceble from running ;-)

Will be fixed when I have some time this night or tomorrow !

**Comment by mitchellkrogza** [comment]
@funilrys the builds completely stalled at that point until they eventually timed out

**Comment by funilrys** [comment]
strange ... It worked on my machines 🤔

**Comment by funilrys** [comment]
@mitchellkrogza, Okay you got me. I'll look deeper into that.

**Comment by funilrys** [comment]
@mitchellkrogza I thought we agreed that that repository will only test the URLs ? 🤔

**Comment by funilrys** [comment]
Mitch @mitchellkrogza !? Let's talk ==> Our usually private channels :smile_cat:

**Comment by dnmTX** [comment]
@funilrys  i understand about builds that contain IP's only failing(looks like you guys have some discussion about filtering them or not,aka to be determined) but why there are other builds with domains only that are still failing? I can't even see the error,it says the log is too long or whatever.

**Comment by funilrys** [comment]
@dnmTX Our discussion was about the structrure of the given repo. But yeah as I had to wake up early this morning I could not fix this completly. 

It's all about the new DNS lookup logic :)

**Comment by dnmTX** [comment]
Thanks @funilrys. Keep us posted in the [FEEDBACK](https://github.com/Ultimate-Hosts-Blacklist/dev-center/issues/32) of the progress.That DNS turned out to be a heck of a pain.Crossing fingers all to go fine and back to normal 👍
