### ISSUE TITLE
BUG: Fatal Error: 'cp950' codec can't encode character

### ISSUE THREAD

**Issue by avatartw** [funilrys/PyFunceble#291]
## Description
b5ecdc2960fc981c99ccb13442b0bae8c9e9d48c
```python
Process pyfunceble_producer_worker_1:
Traceback (most recent call last):
  File "D:\Python\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "D:\Python\lib\site-packages\PyFunceble\cli\processes\workers\base.py", line 395, in run
    raise exception
  File "D:\Python\lib\site-packages\PyFunceble\cli\processes\workers\base.py", line 373, in run
    result = self.target(consumed)
  File "D:\Python\lib\site-packages\PyFunceble\cli\processes\workers\producer.py", line 403, in target
    self.run_whois_backup(test_result)
  File "D:\Python\lib\site-packages\PyFunceble\cli\processes\workers\producer.py", line 213, in run_whois_backup
    self.whois_dataset.update(
  File "D:\Python\lib\site-packages\PyFunceble\dataset\db_base.py", line 104, in wrapper
    return func(self, *args, **kwargs)  # pylint: disable=not-callable
  File "D:\Python\lib\site-packages\PyFunceble\dataset\whois\csv.py", line 140, in update
    self.add(row)
  File "D:\Python\lib\site-packages\PyFunceble\dataset\base.py", line 109, in wrapper
    return func(self, *args, **kwargs)  # pylint: disable=not-callable
  File "D:\Python\lib\site-packages\PyFunceble\dataset\db_base.py", line 104, in wrapper
    return func(self, *args, **kwargs)  # pylint: disable=not-callable
  File "D:\Python\lib\site-packages\PyFunceble\dataset\csv_base.py", line 142, in add
    writer.writerow(row)
  File "D:\Python\lib\csv.py", line 154, in writerow
    return self.writer.writerow(self._dict_to_list(rowdict))
UnicodeEncodeError: 'cp950' codec can't encode character '\u8ba1' in position 56: illegal multibyte sequence
Fatal Error: 'cp950' codec can't encode character '\u8ba1' in position 56: illegal multibyte sequence
Traceback (most recent call last):
  File "D:\Python\lib\site-packages\PyFunceble\cli\system\launcher.py", line 990, in start
    self.stop_and_wait_for_all_manager()
  File "D:\Python\lib\site-packages\PyFunceble\cli\system\launcher.py", line 928, in stop_and_wait_for_all_manager
    self.producer_process_manager.wait()
  File "D:\Python\lib\site-packages\PyFunceble\cli\processes\base.py", line 330, in wait
    raise worker_error
UnicodeEncodeError: 'cp950' codec can't encode character '\u8ba1' in position 56: illegal multibyte sequence
```

## Configuration

N/A

## Reproduction

```
PyFunceble -d edu-media.cn
```

## Expected behavior

No Errors

## Screenshots

N/A

## Versions

**OS:** Windows 10

**Python Version:** 3.8.10

**PyFunceble Version:** 4.0.2 ~ 4.1.0b10

**Comment by funilrys** [comment]
Hi @avatartw,

thank you for taking the time to report this. The patch is on its way out. 

Stay safe and healthy!
