### ISSUE TITLE
BUG: ModuleNotFoundError: No module named 'box'

### ISSUE THREAD

**Issue by spirillen** [funilrys/PyFunceble#298]
## Description

```python
Traceback (most recent call last):
  File "/home/$USER/.local/bin/pyfunceble", line 5, in <module>
    from PyFunceble.cli.entry_points.pyfunceble.cli import tool
  File "/home/$USER/.local/lib/python3.10/site-packages/PyFunceble/__init__.py", line 55, in <module>
    import PyFunceble.storage
  File "/home/$USER/.local/lib/python3.10/site-packages/PyFunceble/storage.py", line 58, in <module>
    from box import Box
ModuleNotFoundError: No module named 'box'
```

## Configuration
No relevance

## Reproduction

1. [./scripts/DataTesting.bash](https://mypdns.org/my-privacy-dns/porn-records/-/blob/b2d1670f281483b93bf8a3d73e22549d04571416/scripts/DataTesting.bash)

## Versions

**OS:** Ubuntu / Miniconda

**Python Version:** 3.10

**PyFunceble Version:** 

```python
pyfunceble --version 
Traceback (most recent call last):
  File "/home/$USER/.local/bin/pyfunceble", line 5, in <module>
    from PyFunceble.cli.entry_points.pyfunceble.cli import tool
  File "/home/$USER/.local/lib/python3.10/site-packages/PyFunceble/__init__.py", line 55, in <module>
    import PyFunceble.storage
  File "/home/$USER/.local/lib/python3.10/site-packages/PyFunceble/storage.py", line 58, in <module>
    from box import Box
ModuleNotFoundError: No module named 'box'
```

**Comment by spirillen** [comment]
Second error I meet, when reach [L63](https://mypdns.org/my-privacy-dns/porn-records/-/blob/b2d1670f281483b93bf8a3d73e22549d04571416/scripts/DataTesting.bash#L63)

```python
Installing collected packages: mypdns, pyfunceble-dev
  Attempting uninstall: pyfunceble-dev
    Found existing installation: PyFunceble-dev 4.1.0b17
    Uninstalling PyFunceble-dev-4.1.0b17:
      Successfully uninstalled PyFunceble-dev-4.1.0b17
Successfully installed mypdns-1.0.3 pyfunceble-dev-4.1.1
```

```python
pyfunceble --version
Traceback (most recent call last):
  File "/home/$USER/miniconda/envs/pyfunceble/bin/pyfunceble", line 5, in <module>
    from PyFunceble.cli.entry_points.pyfunceble.cli import tool
  File "/home/$USER/miniconda/envs/pyfunceble/lib/python3.10/site-packages/PyFunceble/__init__.py", line 56, in <module>
    from PyFunceble.checker.availability.domain import DomainAvailabilityChecker
  File "/home/$USER/miniconda/envs/pyfunceble/lib/python3.10/site-packages/PyFunceble/checker/availability/domain.py", line 55, in <module>
    import PyFunceble.factory
  File "/home/$USER/miniconda/envs/pyfunceble/lib/python3.10/site-packages/PyFunceble/factory.py", line 53, in <module>
    from PyFunceble.query.requests.requester import Requester as requester
  File "/home/$USER/miniconda/envs/pyfunceble/lib/python3.10/site-packages/PyFunceble/query/requests/requester.py", line 64, in <module>
    from PyFunceble.query.dns.query_tool import DNSQueryTool
  File "/home/$USER/miniconda/envs/pyfunceble/lib/python3.10/site-packages/PyFunceble/query/dns/query_tool.py", line 66, in <module>
    import dns.query
  File "/home/$USER/.local/lib/python3.10/site-packages/dns/query.py", line 52, in <module>
    import httpx
  File "/home/$USER/.local/lib/python3.10/site-packages/httpx/__init__.py", line 2, in <module>
    from ._api import delete, get, head, options, patch, post, put, request, stream
  File "/home/$USER/.local/lib/python3.10/site-packages/httpx/_api.py", line 4, in <module>
    from ._client import Client
  File "/home/$USER/.local/lib/python3.10/site-packages/httpx/_client.py", line 30, in <module>
    from ._transports.default import AsyncHTTPTransport, HTTPTransport
  File "/home/$USER/.local/lib/python3.10/site-packages/httpx/_transports/default.py", line 81, in <module>
    httpcore.TimeoutException: TimeoutException,
AttributeError: module 'httpcore' has no attribute 'TimeoutException'
```

**Comment by spirillen** [comment]
NON CONDA

```
python-box==5.4.1
httpx==1.0.0b0
```

Conda editions coming up

**Comment by funilrys** [comment]
Mhh I tested on 2 VM and my PC on fresh environment and can't reproduce 😞

**Comment by spirillen** [comment]
> Mhh I tested on 2 VM and my PC on fresh environment and can't reproduce disappointed

Also only happens in CONDA for me

**Comment by funilrys** [comment]
Testing with conda right now ...

**Comment by spirillen** [comment]
The old box is running with 4.1.0-dev and that is working

-------------

```
python3.10 -m pip install -U -I --pre pyfunceble-dev

....

pyfunceble --version
pyfunceble 4.1.1.dev (Blue Duckling: Ixora)

-----------

Conda

pyfunceble --version
pyfunceble 4.1.1.dev (Blue Duckling: Ixora)
```

/closing as suddenly working without doing anything....


Installing collected packages: mypdns
Successfully installed mypdns-1.0.3

done
#
# To activate this environment, use
#
#     $ conda activate pyfunceble
#
# To deactivate an active environment, use
#
#     $ conda deactivate

pyfunceble 4.1.1.dev (Blue Duckling: Ixora)

        You are running with Pyfunceble


    ██████╗ ██╗   ██╗███████╗██╗   ██╗███╗   ██╗ ██████╗███████╗██████╗ ██╗     ███████╗
    ██╔══██╗╚██╗ ██╔╝██╔════╝██║   ██║████╗  ██║██╔════╝██╔════╝██╔══██╗██║     ██╔════╝
    ██████╔╝ ╚████╔╝ █████╗  ██║   ██║██╔██╗ ██║██║     █████╗  ██████╔╝██║     █████╗
    ██╔═══╝   ╚██╔╝  ██╔══╝  ██║   ██║██║╚██╗██║██║     ██╔══╝  ██╔══██╗██║     ██╔══╝
    ██║        ██║   ██║     ╚██████╔╝██║ ╚████║╚██████╗███████╗██████╔╝███████╗███████╗
    ╚═╝        ╚═╝   ╚═╝      ╚═════╝ ╚═╝  ╚═══╝ ╚═════╝╚══════╝╚═════╝ ╚══════╝╚══════╝
    


Subject                                                                                              Status      Source     Expiration Date   Registrar                      HTTP Code  Checker      
---------------------------------------------------------------------------------------------------- ----------- ---------- ----------------- ------------------------------ ---------- -------------
100oj.booru.org

**Comment by funilrys** [comment]
Came to the same conclusion ... It's odd ... Probably cache or something  ...
