### ISSUE TITLE
BUG: Can't pickle <class 'sqlalchemy.orm.session.Session'>: it's not the same object as sqlalchemy.orm.session.Session

### ISSUE THREAD

**Issue by avatartw** [funilrys/PyFunceble#301]
## Description

```python
Fatal Error: Can't pickle <class 'sqlalchemy.orm.session.Session'>: it's not the same object as sqlalchemy.orm.session.Session
Traceback (most recent call last):
  File "C:\Python310\Lib\site-packages\PyFunceble\cli\system\launcher.py", line 985, in start
    self.__start_core_processes()
  File "C:\Python310\Lib\site-packages\PyFunceble\cli\system\launcher.py", line 955, in __start_core_processes
    self.producer_process_manager.start()
  File "C:\Python310\Lib\site-packages\PyFunceble\cli\processes\base.py", line 182, in wrapper
    return func(self, *args, **kwargs)  # pylint: disable=not-callable
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python310\Lib\site-packages\PyFunceble\cli\processes\base.py", line 198, in wrapper
    return func(self, *args, **kwargs)  # pylint: disable=not-callable
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python310\Lib\site-packages\PyFunceble\cli\processes\base.py", line 211, in wrapper
    return func(self, *args, **kwargs)  # pylint: disable=not-callable
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python310\Lib\site-packages\PyFunceble\cli\processes\base.py", line 478, in start
    worker.start()
  File "C:\Python310\Lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
                  ^^^^^^^^^^^^^^^^^
  File "C:\Python310\Lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python310\Lib\multiprocessing\context.py", line 336, in _Popen
    return Popen(process_obj)
           ^^^^^^^^^^^^^^^^^^
  File "C:\Python310\Lib\multiprocessing\popen_spawn_win32.py", line 93, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Python310\Lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
_pickle.PicklingError: Can't pickle <class 'sqlalchemy.orm.session.Session'>: it's not the same object as sqlalchemy.orm.session.Session

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Python310\Lib\multiprocessing\spawn.py", line 111, in spawn_main
    new_handle = reduction.duplicate(pipe_handle,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python310\Lib\multiprocessing\reduction.py", line 79, in duplicate
    return _winapi.DuplicateHandle(
           ^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [WinError 6] 控制代碼無效。
```

## Configuration

N/A

## Reproduction

```
PyFunceble --database-type mysql -d www.google.com
```

## Expected behavior

No Errors

## Versions

**OS:** Windows 10

**Python Version:** 3.10.5

**PyFunceble Version:** 4.1.1.dev (Blue Duckling: Ixora)

**Comment by spirillen** [comment]
1. What database are you actually using? there are diffs between the `mysql` and `mariadb` connectors you need to use the right one.
2.  4.1.1.dev, current -dev version is 4.1.2 with fixes.


on 4.1.2-dev with mariadb 10.7

```
PyFunceble --database-type mysql -d www.google.com

    ██████╗ ██╗   ██╗███████╗██╗   ██╗███╗   ██╗ ██████╗███████╗██████╗ ██╗     ███████╗
    ██╔══██╗╚██╗ ██╔╝██╔════╝██║   ██║████╗  ██║██╔════╝██╔════╝██╔══██╗██║     ██╔════╝
    ██████╔╝ ╚████╔╝ █████╗  ██║   ██║██╔██╗ ██║██║     █████╗  ██████╔╝██║     █████╗
    ██╔═══╝   ╚██╔╝  ██╔══╝  ██║   ██║██║╚██╗██║██║     ██╔══╝  ██╔══██╗██║     ██╔══╝
    ██║        ██║   ██║     ╚██████╔╝██║ ╚████║╚██████╗███████╗██████╔╝███████╗███████╗
    ╚═╝        ╚═╝   ╚═╝      ╚═════╝ ╚═╝  ╚═══╝ ╚═════╝╚══════╝╚═════╝ ╚══════╝╚══════╝
    


Subject                                                                                              Status      Source     Expiration Date   Registrar                      HTTP Code  Checker      
---------------------------------------------------------------------------------------------------- ----------- ---------- ----------------- ------------------------------ ---------- -------------
www.google.com                                                                                       ACTIVE      DNSLOOKUP  Unknown           Unknown                        302        AVAILABILITY 

Execution Time: 00:00:00:9.691963


Thank you for using PyFunceble!
Share your experience on Twitter with #PyFunceble or @PyFunceble!
Do you have a feedback, an issue or an improvement idea? Let us know on GitHub!
```

```
PyFunceble --database-type mariadb -d www.google.com

    ██████╗ ██╗   ██╗███████╗██╗   ██╗███╗   ██╗ ██████╗███████╗██████╗ ██╗     ███████╗
    ██╔══██╗╚██╗ ██╔╝██╔════╝██║   ██║████╗  ██║██╔════╝██╔════╝██╔══██╗██║     ██╔════╝
    ██████╔╝ ╚████╔╝ █████╗  ██║   ██║██╔██╗ ██║██║     █████╗  ██████╔╝██║     █████╗
    ██╔═══╝   ╚██╔╝  ██╔══╝  ██║   ██║██║╚██╗██║██║     ██╔══╝  ██╔══██╗██║     ██╔══╝
    ██║        ██║   ██║     ╚██████╔╝██║ ╚████║╚██████╗███████╗██████╔╝███████╗███████╗
    ╚═╝        ╚═╝   ╚═╝      ╚═════╝ ╚═╝  ╚═══╝ ╚═════╝╚══════╝╚═════╝ ╚══════╝╚══════╝
    


Subject                                                                                              Status      Source     Expiration Date   Registrar                      HTTP Code  Checker      
---------------------------------------------------------------------------------------------------- ----------- ---------- ----------------- ------------------------------ ---------- -------------
www.google.com                                                                                       ACTIVE      DNSLOOKUP  Unknown           Unknown                        302        AVAILABILITY 

Execution Time: 00:00:00:3.121947


Thank you for using PyFunceble!
Do you have a feedback, an issue or an improvement idea? Let us know on GitHub!
```

**Comment by funilrys** [comment]
I think that this is windows specific ... I need to find or setup a Windows Hosts to be able to reproduce this ... @spirillen
