### ISSUE TITLE
BUG: retries exceeded with url: / (Caused by None)

### ISSUE THREAD

**Issue by spirillen** [funilrys/PyFunceble#303]
## Description

Just keeps failing without any obviously reasons.

## Configuration

`.PyFunceble.yaml` Neutral, thanks to `.PyFunceble.overwrite.yaml` 

```yaml
cli_testing:
  autocontinue: true
  cidr_expand: true
  db_type: mariadb
  display_mode:
    all: true
    colour: true
    dots: false
    execution_time: true
    less: false
    percentage: true
    quiet: false
    simple: false
    status: all
  file_generation:
    analytic: true
    hosts: false
    merge_output_dirs: false
    no_file: false
    plain: true
    unified_results: false
  local_network: false
  sorting_mode:
    hierarchical: true
debug:
  active: false
  level: critical
lookup:
  collection: false
  dns: true
  http_status_code: true
  netinfo: true
  reputation: false
  special: true
  timeout: 5
  whois: true
user_agent:
  browser: firefox
  custom: null
  platform: linux
dns:
  follow_server_order: false
  trust_server: false
  protocol: UDP
  server:
    - 130.226.161.34
    - 89.233.43.71
    - 9.9.9.10
    - 149.112.112.10
collection:
  preferred_status_origin: recommended
  push: true
  url_base: https://collection.dead-hosts.funilrys.com
proxy:
  global:
    http: socks5h://127.0.0.1:9050
    https: socks5h://127.0.0.1:9050
  rules:
    - http: socks5h://127.0.0.1:9050
      https: socks5h://127.0.0.1:9050
      tld:
        - onion
```

## Reproduction

1.https://mypdns.org/clefspeare13/pornhosts/-/blob/feature/test_script/toolbox/availability_test.bash

## Versions

**OS:** Conda

**Python Version:** 3.10

**PyFunceble Version:** 4.1.2.dev

## Additional context

```python
Fatal Error: None: Max retries exceeded with url: / (Caused by None)
Traceback (most recent call last):
  File "/home/$USER/Downloads/git_projects/clefspeare13/pornhosts/miniconda/envs/pyfunceble/lib/python3.10/site-packages/PyFunceble/cli/system/launcher.py", line 990, in start
    self.stop_and_wait_for_all_manager()
  File "/home/$USER/Downloads/git_projects/clefspeare13/pornhosts/miniconda/envs/pyfunceble/lib/python3.10/site-packages/PyFunceble/cli/system/launcher.py", line 927, in stop_and_wait_for_all_manager
    self.tester_process_manager.wait()
  File "/home/$USER/Downloads/git_projects/clefspeare13/pornhosts/miniconda/envs/pyfunceble/lib/python3.10/site-packages/PyFunceble/cli/processes/base.py", line 330, in wait
    raise worker_error
requests.exceptions.ConnectTimeout: None: Max retries exceeded with url: / (Caused by None)
```

**Comment by spirillen** [comment]
Hey @funilrys any comment to this one... my pornlist in hosts format have been held back, as i can't test it before releasing.

**Comment by funilrys** [comment]
@spirillen still testing trying to find where the but is ...

**Comment by spirillen** [comment]
Sounds great, as it keep happening to me

**Comment by funilrys** [comment]
@spirillen `v4.1.3a2` should fix this. Unfortunately, GH is dealing with issues with GitHub Actions. Therefore, it will be deployed later on.

Please reopen this issue if the issue still happens under `v4.1.3a2`.

**Comment by funilrys** [comment]
`v4.1.3a2` has been released.

**Comment by spirillen** [comment]
```python
Fatal Error: <subject> should be <class 'str'>, type(subject) given.
Traceback (most recent call last):
  File "/home/$USER/Downloads/clefspeare13/pornhosts/miniconda/envs/pyfunceble/lib/python3.10/site-packages/PyFunceble/cli/system/launcher.py", line 990, in start
    self.stop_and_wait_for_all_manager()
  File "/home/$USER/Downloads/clefspeare13/pornhosts/miniconda/envs/pyfunceble/lib/python3.10/site-packages/PyFunceble/cli/system/launcher.py", line 927, in stop_and_wait_for_all_manager
    self.tester_process_manager.wait()
  File "/home/$USER/Downloads/clefspeare13/pornhosts/miniconda/envs/pyfunceble/lib/python3.10/site-packages/PyFunceble/cli/processes/base.py", line 330, in wait
    raise worker_error
TypeError: <subject> should be <class 'str'>, type(subject) given.
```

**Comment by funilrys** [comment]
@spirillen PyFunceble-dev actually requires at least 6.X.Y ...

https://github.com/funilrys/PyFunceble/blob/ad9a7f4801a119f3d419a457d3b3d8e5cbd0dc3a/requirements.txt#L9

**Comment by funilrys** [comment]
Is that possible that you are actually trying to download `pyfunceble` and not `pyfunceble-dev` ?

**Comment by spirillen** [comment]
LOL keyboard failure

made a dot not a `-`

but same error

```python
python3.10 -m pip install -U -I --pre pyfunceble.dev
Defaulting to user installation because normal site-packages is not writeable
Collecting pyfunceble.dev
Using cached PyFunceble_dev-4.1.3a2-py3-none-any.whl (481 kB)
Collecting PyMySQL
Using cached PyMySQL-1.0.2-py3-none-any.whl (43 kB)
Collecting packaging
Using cached packaging-21.3-py3-none-any.whl (40 kB)
Collecting inflection
Using cached inflection-0.5.1-py2.py3-none-any.whl (9.5 kB)
Collecting PyYAML
Using cached PyYAML-6.0-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (682 kB)
Collecting dnspython[doh]~=2.0.0
Using cached dnspython-2.0.0-py3-none-any.whl (208 kB)
Collecting domain2idna>=1.12.0
Using cached domain2idna-1.12.0-py3-none-any.whl (10 kB)
Collecting python-box[all]~=6.0.0
Using cached python_box-6.0.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.3 MB)
Collecting cryptography>=3.3.2
Downloading cryptography-38.0.1-cp36-abi3-manylinux_2_28_x86_64.whl (4.2 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.2/4.2 MB 30.5 MB/s eta 0:00:00
Collecting colorama
Using cached colorama-0.4.5-py2.py3-none-any.whl (16 kB)
Collecting shtab
Using cached shtab-1.5.5-py2.py3-none-any.whl (13 kB)
Collecting setuptools
Downloading setuptools-65.4.1-py3-none-any.whl (1.2 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 65.4 MB/s eta 0:00:00
Collecting requests[socks]<3
Using cached requests-2.28.1-py3-none-any.whl (62 kB)
Collecting python-dotenv
Downloading python_dotenv-0.21.0-py3-none-any.whl (18 kB)
Collecting alembic
Using cached alembic-1.8.1-py3-none-any.whl (209 kB)
Collecting SQLAlchemy~=1.3.20
Using cached SQLAlchemy-1.3.24-cp310-cp310-linux_x86_64.whl
Collecting cffi>=1.12
Using cached cffi-1.15.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (441 kB)
Collecting requests-toolbelt
Downloading requests_toolbelt-0.10.0-py2.py3-none-any.whl (54 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 54.4/54.4 kB 18.8 MB/s eta 0:00:00
Collecting toml
Using cached toml-0.10.2-py2.py3-none-any.whl (16 kB)
Collecting ruamel.yaml>=0.17
Using cached ruamel.yaml-0.17.21-py3-none-any.whl (109 kB)
Collecting msgpack
Using cached msgpack-1.0.4-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (316 kB)
Collecting certifi>=2017.4.17
Downloading certifi-2022.9.24-py3-none-any.whl (161 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 161.1/161.1 kB 47.0 MB/s eta 0:00:00
Collecting charset-normalizer<3,>=2
Downloading charset_normalizer-2.1.1-py3-none-any.whl (39 kB)
Collecting urllib3<1.27,>=1.21.1
Downloading urllib3-1.26.12-py2.py3-none-any.whl (140 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 140.4/140.4 kB 43.9 MB/s eta 0:00:00
Collecting idna<4,>=2.5
Downloading idna-3.4-py3-none-any.whl (61 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.5/61.5 kB 27.8 MB/s eta 0:00:00
Collecting PySocks!=1.5.7,>=1.5.6
Using cached PySocks-1.7.1-py3-none-any.whl (16 kB)
Collecting Mako
Downloading Mako-1.2.3-py3-none-any.whl (78 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.7/78.7 kB 29.8 MB/s eta 0:00:00
Collecting pyparsing!=3.0.5,>=2.0.2
Using cached pyparsing-3.0.9-py3-none-any.whl (98 kB)
Collecting pycparser
Using cached pycparser-2.21-py2.py3-none-any.whl (118 kB)
Collecting ruamel.yaml.clib>=0.2.6
Using cached ruamel.yaml.clib-0.2.6-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.manylinux_2_24_x86_64.whl (519 kB)
Collecting MarkupSafe>=0.9.2
Using cached MarkupSafe-2.1.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (25 kB)
Installing collected packages: msgpack, urllib3, toml, SQLAlchemy, shtab, setuptools, ruamel.yaml.clib, PyYAML, python-dotenv, python-box, PySocks, pyparsing, PyMySQL, pycparser, MarkupSafe, inflection, idna, dnspython, colorama, charset-normalizer, certifi, ruamel.yaml, requests, packaging, Mako, domain2idna, cffi, requests-toolbelt, cryptography, alembic, pyfunceble.dev
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
pyfunceble 4.1.0 requires python-box[all]<6, but you have python-box 6.0.2 which is incompatible.
Successfully installed Mako-1.2.3 MarkupSafe-2.1.1 PyMySQL-1.0.2 PySocks-1.7.1 PyYAML-6.0 SQLAlchemy-1.4.34 alembic-1.8.1 certifi-2022.9.24 cffi-1.15.1 charset-normalizer-2.1.1 colorama-0.4.5 cryptography-38.0.1 dnspython-2.2.0 domain2idna-1.12.0 idna-3.4 inflection-0.5.1 msgpack-1.0.4 packaging-21.3 pycparser-2.21 pyfunceble.dev-4.1.3a2 pyparsing-3.0.9 python-box-6.0.2 python-dotenv-0.21.0 requests-2.28.1 requests-toolbelt-0.10.0 ruamel.yaml-0.17.21 ruamel.yaml.clib-0.2.6 setuptools-65.4.1 shtab-1.5.5 toml-0.10.2 urllib3-1.26.12
--- Logging error ---
Traceback (most recent call last):
File "/home/spirillen/.local/lib/python3.10/site-packages/pip/_internal/utils/logging.py", line 177, in emit
self.console.print(renderable, overflow="ignore", crop=False, style=style)
File "/home/spirillen/.local/lib/python3.10/site-packages/pip/_vendor/rich/console.py", line 1673, in print
extend(render(renderable, render_options))
File "/home/spirillen/.local/lib/python3.10/site-packages/pip/_vendor/rich/console.py", line 1305, in render
for render_output in iter_render:
File "/home/spirillen/.local/lib/python3.10/site-packages/pip/_internal/utils/logging.py", line 134, in __rich_console__
for line in lines:
File "/home/spirillen/.local/lib/python3.10/site-packages/pip/_vendor/rich/segment.py", line 249, in split_lines
for segment in segments:
File "/home/spirillen/.local/lib/python3.10/site-packages/pip/_vendor/rich/console.py", line 1283, in render
renderable = rich_cast(renderable)
File "/home/spirillen/.local/lib/python3.10/site-packages/pip/_vendor/rich/protocol.py", line 36, in rich_cast
renderable = cast_method()
File "/home/spirillen/.local/lib/python3.10/site-packages/pip/_internal/self_outdated_check.py", line 130, in __rich__
pip_cmd = get_best_invocation_for_this_pip()
File "/home/spirillen/.local/lib/python3.10/site-packages/pip/_internal/utils/entrypoints.py", line 58, in get_best_invocation_for_this_pip
if found_executable and os.path.samefile(
File "/usr/lib/python3.10/genericpath.py", line 101, in samefile
s2 = os.stat(f2)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/bin/pip'
Call stack:
File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
return _run_code(code, main_globals, None,
File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
exec(code, run_globals)
File "/home/spirillen/.local/lib/python3.10/site-packages/pip/__main__.py", line 31, in <module>
sys.exit(_main())
File "/home/spirillen/.local/lib/python3.10/site-packages/pip/_internal/cli/main.py", line 70, in main
return command.main(cmd_args)
File "/home/spirillen/.local/lib/python3.10/site-packages/pip/_internal/cli/base_command.py", line 101, in main
return self._main(args)
File "/home/spirillen/.local/lib/python3.10/site-packages/pip/_internal/cli/base_command.py", line 223, in _main
self.handle_pip_version_check(options)
File "/home/spirillen/.local/lib/python3.10/site-packages/pip/_internal/cli/req_command.py", line 190, in handle_pip_version_check
pip_self_version_check(session, options)
File "/home/spirillen/.local/lib/python3.10/site-packages/pip/_internal/self_outdated_check.py", line 236, in pip_self_version_check
logger.info("[present-rich] %s", upgrade_prompt)
File "/usr/lib/python3.10/logging/__init__.py", line 1477, in info
self._log(INFO, msg, args, **kwargs)
File "/usr/lib/python3.10/logging/__init__.py", line 1624, in _log
self.handle(record)
File "/usr/lib/python3.10/logging/__init__.py", line 1634, in handle
self.callHandlers(record)
File "/usr/lib/python3.10/logging/__init__.py", line 1696, in callHandlers
hdlr.handle(record)
File "/usr/lib/python3.10/logging/__init__.py", line 968, in handle
self.emit(record)
File "/home/spirillen/.local/lib/python3.10/site-packages/pip/_internal/utils/logging.py", line 179, in emit
self.handleError(record)
Message: '[present-rich] %s'
Arguments: (UpgradePrompt(old='22.2', new='22.2.2'),)
spirillen@vision:~/Downloads/git_projects/my_privacy_dns/matrix$ python3.10 -m pip install -U -I --pre pyfunceble-dev
Defaulting to user installation because normal site-packages is not writeable
Collecting pyfunceble-dev
Using cached PyFunceble_dev-4.1.3a2-py3-none-any.whl (481 kB)
Collecting setuptools
Using cached setuptools-65.4.1-py3-none-any.whl (1.2 MB)
Collecting PyYAML
Using cached PyYAML-6.0-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (682 kB)
Collecting inflection
Using cached inflection-0.5.1-py2.py3-none-any.whl (9.5 kB)
Collecting dnspython[doh]~=2.0.0
Using cached dnspython-2.0.0-py3-none-any.whl (208 kB)
Collecting domain2idna>=1.12.0
Using cached domain2idna-1.12.0-py3-none-any.whl (10 kB)
Collecting cryptography>=3.3.2
Using cached cryptography-38.0.1-cp36-abi3-manylinux_2_28_x86_64.whl (4.2 MB)
Collecting alembic
Using cached alembic-1.8.1-py3-none-any.whl (209 kB)
Collecting SQLAlchemy~=1.3.20
Using cached SQLAlchemy-1.3.24-cp310-cp310-linux_x86_64.whl
Collecting colorama
Using cached colorama-0.4.5-py2.py3-none-any.whl (16 kB)
Collecting packaging
Using cached packaging-21.3-py3-none-any.whl (40 kB)
Collecting python-box[all]~=6.0.0
Using cached python_box-6.0.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.3 MB)
Collecting python-dotenv
Using cached python_dotenv-0.21.0-py3-none-any.whl (18 kB)
Collecting requests[socks]<3
Using cached requests-2.28.1-py3-none-any.whl (62 kB)
Collecting shtab
Using cached shtab-1.5.5-py2.py3-none-any.whl (13 kB)
Collecting PyMySQL
Using cached PyMySQL-1.0.2-py3-none-any.whl (43 kB)
Collecting cffi>=1.12
Using cached cffi-1.15.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (441 kB)
Collecting requests-toolbelt
Using cached requests_toolbelt-0.10.0-py2.py3-none-any.whl (54 kB)
Collecting msgpack
Using cached msgpack-1.0.4-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (316 kB)
Collecting ruamel.yaml>=0.17
Using cached ruamel.yaml-0.17.21-py3-none-any.whl (109 kB)
Collecting toml
Using cached toml-0.10.2-py2.py3-none-any.whl (16 kB)
Collecting urllib3<1.27,>=1.21.1
Using cached urllib3-1.26.12-py2.py3-none-any.whl (140 kB)
Collecting idna<4,>=2.5
Using cached idna-3.4-py3-none-any.whl (61 kB)
Collecting certifi>=2017.4.17
Using cached certifi-2022.9.24-py3-none-any.whl (161 kB)
Collecting charset-normalizer<3,>=2
Using cached charset_normalizer-2.1.1-py3-none-any.whl (39 kB)
Collecting PySocks!=1.5.7,>=1.5.6
Using cached PySocks-1.7.1-py3-none-any.whl (16 kB)
Collecting Mako
Using cached Mako-1.2.3-py3-none-any.whl (78 kB)
Collecting pyparsing!=3.0.5,>=2.0.2
Using cached pyparsing-3.0.9-py3-none-any.whl (98 kB)
Collecting pycparser
Using cached pycparser-2.21-py2.py3-none-any.whl (118 kB)
Collecting ruamel.yaml.clib>=0.2.6
Using cached ruamel.yaml.clib-0.2.6-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.manylinux_2_24_x86_64.whl (519 kB)
Collecting MarkupSafe>=0.9.2
Using cached MarkupSafe-2.1.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (25 kB)
Installing collected packages: msgpack, urllib3, toml, SQLAlchemy, shtab, setuptools, ruamel.yaml.clib, PyYAML, python-dotenv, python-box, PySocks, pyparsing, PyMySQL, pycparser, MarkupSafe, inflection, idna, dnspython, colorama, charset-normalizer, certifi, ruamel.yaml, requests, packaging, Mako, domain2idna, cffi, requests-toolbelt, cryptography, alembic, pyfunceble-dev
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
pyfunceble 4.1.0 requires python-box[all]<6, but you have python-box 6.0.2 which is incompatible.
Successfully installed Mako-1.2.3 MarkupSafe-2.1.1 PyMySQL-1.0.2 PySocks-1.7.1 PyYAML-6.0 SQLAlchemy-1.4.34 alembic-1.8.1 certifi-2022.9.24 cffi-1.15.1 charset-normalizer-2.1.1 colorama-0.4.5 cryptography-38.0.1 dnspython-2.2.0 domain2idna-1.12.0 idna-3.4 inflection-0.5.1 msgpack-1.0.4 packaging-21.3 pycparser-2.21 pyfunceble-dev-4.1.3a2 pyparsing-3.0.9 python-box-6.0.2 python-dotenv-0.21.0 requests-2.28.1 requests-toolbelt-0.10.0 ruamel.yaml-0.17.21 ruamel.yaml.clib-0.2.6 setuptools-65.4.1 shtab-1.5.5 toml-0.10.2 urllib3-1.26.12
--- Logging error ---
Traceback (most recent call last):
File "/home/spirillen/.local/lib/python3.10/site-packages/pip/_internal/utils/logging.py", line 177, in emit
self.console.print(renderable, overflow="ignore", crop=False, style=style)
File "/home/spirillen/.local/lib/python3.10/site-packages/pip/_vendor/rich/console.py", line 1673, in print
extend(render(renderable, render_options))
File "/home/spirillen/.local/lib/python3.10/site-packages/pip/_vendor/rich/console.py", line 1305, in render
for render_output in iter_render:
File "/home/spirillen/.local/lib/python3.10/site-packages/pip/_internal/utils/logging.py", line 134, in __rich_console__
for line in lines:
File "/home/spirillen/.local/lib/python3.10/site-packages/pip/_vendor/rich/segment.py", line 249, in split_lines
for segment in segments:
File "/home/spirillen/.local/lib/python3.10/site-packages/pip/_vendor/rich/console.py", line 1283, in render
renderable = rich_cast(renderable)
File "/home/spirillen/.local/lib/python3.10/site-packages/pip/_vendor/rich/protocol.py", line 36, in rich_cast
renderable = cast_method()
File "/home/spirillen/.local/lib/python3.10/site-packages/pip/_internal/self_outdated_check.py", line 130, in __rich__
pip_cmd = get_best_invocation_for_this_pip()
File "/home/spirillen/.local/lib/python3.10/site-packages/pip/_internal/utils/entrypoints.py", line 58, in get_best_invocation_for_this_pip
if found_executable and os.path.samefile(
File "/usr/lib/python3.10/genericpath.py", line 101, in samefile
s2 = os.stat(f2)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/bin/pip'
Call stack:
File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
return _run_code(code, main_globals, None,
File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
exec(code, run_globals)
File "/home/spirillen/.local/lib/python3.10/site-packages/pip/__main__.py", line 31, in <module>
sys.exit(_main())
File "/home/spirillen/.local/lib/python3.10/site-packages/pip/_internal/cli/main.py", line 70, in main
return command.main(cmd_args)
File "/home/spirillen/.local/lib/python3.10/site-packages/pip/_internal/cli/base_command.py", line 101, in main
return self._main(args)
File "/home/spirillen/.local/lib/python3.10/site-packages/pip/_internal/cli/base_command.py", line 223, in _main
self.handle_pip_version_check(options)
File "/home/spirillen/.local/lib/python3.10/site-packages/pip/_internal/cli/req_command.py", line 190, in handle_pip_version_check
pip_self_version_check(session, options)
File "/home/spirillen/.local/lib/python3.10/site-packages/pip/_internal/self_outdated_check.py", line 236, in pip_self_version_check
logger.info("[present-rich] %s", upgrade_prompt)
File "/usr/lib/python3.10/logging/__init__.py", line 1477, in info
self._log(INFO, msg, args, **kwargs)
File "/usr/lib/python3.10/logging/__init__.py", line 1624, in _log
self.handle(record)
File "/usr/lib/python3.10/logging/__init__.py", line 1634, in handle
self.callHandlers(record)
File "/usr/lib/python3.10/logging/__init__.py", line 1696, in callHandlers
hdlr.handle(record)
File "/usr/lib/python3.10/logging/__init__.py", line 968, in handle
self.emit(record)
File "/home/spirillen/.local/lib/python3.10/site-packages/pip/_internal/utils/logging.py", line 179, in emit
self.handleError(record)
Message: '[present-rich] %s'
Arguments: (UpgradePrompt(old='22.2', new='22.2.2'),)
```

**Comment by funilrys** [comment]
Still a dot @spirillen

**Comment by spirillen** [comment]
> Still a dot @spirillen

Hmm seems you only got the first part... Did install it second time with the dash despite the waring :man_shrugging:

**Comment by funilrys** [comment]
@spirillen please test with `4.1.3a3`. It will be deployed next.

**Comment by spirillen** [comment]
> @spirillen please test with `4.1.3a3`. It will be deployed next.

Test is running, will have the result within 3 - 4 days.
