### ISSUE TITLE
BUG: `--collection-lookup` Host unreachable

### ISSUE THREAD

**Issue by spirillen** [funilrys/PyFunceble#315]
## Description
```python
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.contrib.socks.SOCKSConnection object at 0x7f8a83fca500>: Failed to establish a new connection: 0x04: Host unreachable')': /
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.contrib.socks.SOCKSConnection object at 0x7f8a83fcbf40>: Failed to establish a new connection: 0x04: Host unreachable')': /
d18s8yuivfoc6j.cloudfront.net                                                                        INACTIVE    STDLOOKUP  Unknown           Unknown                        Unknown    AVAILABILITY 
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("SOCKSHTTPConnectionPool(host='13.33.141.58', port=80): Read timed out. (read timeout=5.0)")': /
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("SOCKSHTTPConnectionPool(host='d1g1fl82456dtn.cloudfront.net', port=80): Read timed out. (read timeout=5.0)")': /
d1jge1cy7hc6l5.cloudfront.net                                                                        INACTIVE    STDLOOKUP  Unknown           Unknown                        Unknown    AVAILABILITY 
d1j8v290qqvibb.cloudfront.net                                                                        ACTIVE      DNSLOOKUP  Unknown           Unknown                        301        AVAILABILITY 
^C
Thank you for using PyFunceble!
Process pyfunceble_tester_worker_2:
Process pyfunceble_tester_worker_3:
Process pyfunceble_producer_worker_1:
Process pyfunceble_tester_worker_6:
Process pyfunceble_tester_worker_4:
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/home/spirillen/.local/lib/python3.10/site-packages/PyFunceble/cli/processes/workers/base.py", line 373, in run
    result = self.target(consumed)
  File "/home/spirillen/.local/lib/python3.10/site-packages/PyFunceble/cli/processes/workers/tester.py", line 292, in target
    .query_status()
  File "/home/spirillen/.local/lib/python3.10/site-packages/PyFunceble/checker/base.py", line 157, in wrapper
    return func(self, *args, **kwargs)  # pylint: disable=not-callable
  File "/home/spirillen/.local/lib/python3.10/site-packages/PyFunceble/checker/base.py", line 182, in wrapper
    result = func(self, *args, **kwargs)  # pylint: disable=not-callable
  File "/home/spirillen/.local/lib/python3.10/site-packages/PyFunceble/checker/availability/domain_and_ip.py", line 109, in query_status
    result = query_object.query_status()
  File "/home/spirillen/.local/lib/python3.10/site-packages/PyFunceble/checker/base.py", line 157, in wrapper
    return func(self, *args, **kwargs)  # pylint: disable=not-callable
  File "/home/spirillen/.local/lib/python3.10/site-packages/PyFunceble/checker/base.py", line 182, in wrapper
    result = func(self, *args, **kwargs)  # pylint: disable=not-callable
  File "/home/spirillen/.local/lib/python3.10/site-packages/PyFunceble/checker/availability/domain.py", line 147, in query_status
    self.try_to_query_status_from_whois()
  File "/home/spirillen/.local/lib/python3.10/site-packages/PyFunceble/checker/availability/base.py", line 756, in try_to_query_status_from_whois
    known_record = whois_object[self.subject]
  File "/home/spirillen/.local/lib/python3.10/site-packages/PyFunceble/dataset/whois/csv.py", line 87, in __getitem__
    for row in self.get_content():
  File "/home/spirillen/.local/lib/python3.10/site-packages/PyFunceble/dataset/whois/csv.py", line 101, in get_content
    for row in super().get_content():
  File "/home/spirillen/.local/lib/python3.10/site-packages/PyFunceble/dataset/csv_base.py", line 208, in get_content
    for row in reader:
  File "/usr/lib/python3.10/csv.py", line 111, in __next__
    row = next(self.reader)
KeyboardInterrupt
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
Traceback (most recent call last):
  File "/home/spirillen/.local/lib/python3.10/site-packages/PyFunceble/cli/processes/workers/base.py", line 373, in run
    result = self.target(consumed)
  File "/home/spirillen/.local/lib/python3.10/site-packages/PyFunceble/cli/processes/workers/tester.py", line 292, in target
    .query_status()
  File "/home/spirillen/.local/lib/python3.10/site-packages/PyFunceble/checker/base.py", line 157, in wrapper
    return func(self, *args, **kwargs)  # pylint: disable=not-callable
  File "/home/spirillen/.local/lib/python3.10/site-packages/PyFunceble/checker/base.py", line 182, in wrapper
    result = func(self, *args, **kwargs)  # pylint: disable=not-callable
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/home/spirillen/.local/lib/python3.10/site-packages/PyFunceble/cli/processes/workers/base.py", line 373, in run
    result = self.target(consumed)
  File "/home/spirillen/.local/lib/python3.10/site-packages/PyFunceble/checker/availability/domain_and_ip.py", line 109, in query_status
    result = query_object.query_status()
  File "/home/spirillen/.local/lib/python3.10/site-packages/PyFunceble/checker/base.py", line 157, in wrapper
    return func(self, *args, **kwargs)  # pylint: disable=not-callable
  File "/home/spirillen/.local/lib/python3.10/site-packages/PyFunceble/checker/base.py", line 182, in wrapper
    result = func(self, *args, **kwargs)  # pylint: disable=not-callable
  File "/home/spirillen/.local/lib/python3.10/site-packages/PyFunceble/checker/availability/domain.py", line 168, in query_status
    self.try_to_query_status_from_http_status_code()
  File "/home/spirillen/.local/lib/python3.10/site-packages/PyFunceble/checker/availability/base.py", line 900, in try_to_query_status_from_http_status_code
    lookup_result = self.http_status_code_query_tool.get_status_code()
  File "/home/spirillen/.local/lib/python3.10/site-packages/PyFunceble/query/http_status_code.py", line 122, in wrapper
    return func(self, *args, **kwargs)  # pylint: disable=not-callable
  File "/home/spirillen/.local/lib/python3.10/site-packages/PyFunceble/query/http_status_code.py", line 337, in get_status_code
    req = PyFunceble.factory.Requester.get(
  File "/home/spirillen/.local/lib/python3.10/site-packages/PyFunceble/query/requests/requester.py", line 213, in wrapper
    req = getattr(self.session, verb.lower())(*args, **kwargs)
  File "/home/spirillen/.local/lib/python3.10/site-packages/requests/sessions.py", line 600, in get
    return self.request("GET", url, **kwargs)
  File "/home/spirillen/.local/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/spirillen/.local/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/home/spirillen/.local/lib/python3.10/site-packages/PyFunceble/query/requests/adapter/http.py", line 129, in send
    response = super().send(request, **kwargs)
  File "/home/spirillen/.local/lib/python3.10/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/home/spirillen/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/home/spirillen/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/spirillen/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.10/http/client.py", line 1374, in getresponse
    response.begin()
  File "/home/spirillen/.local/lib/python3.10/site-packages/PyFunceble/cli/processes/workers/tester.py", line 292, in target
    .query_status()
  File "/usr/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/home/spirillen/.local/lib/python3.10/site-packages/PyFunceble/checker/base.py", line 157, in wrapper
    return func(self, *args, **kwargs)  # pylint: disable=not-callable
  File "/usr/lib/python3.10/http/client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/home/spirillen/.local/lib/python3.10/site-packages/PyFunceble/checker/base.py", line 182, in wrapper
    result = func(self, *args, **kwargs)  # pylint: disable=not-callable
  File "/usr/lib/python3.10/socket.py", line 705, in readinto
    return self._sock.recv_into(b)
  File "/home/spirillen/.local/lib/python3.10/site-packages/PyFunceble/checker/availability/domain_and_ip.py", line 109, in query_status
    result = query_object.query_status()
  File "/home/spirillen/.local/lib/python3.10/site-packages/PyFunceble/checker/base.py", line 157, in wrapper
    return func(self, *args, **kwargs)  # pylint: disable=not-callable
KeyboardInterrupt
  File "/home/spirillen/.local/lib/python3.10/site-packages/PyFunceble/checker/base.py", line 182, in wrapper
    result = func(self, *args, **kwargs)  # pylint: disable=not-callable
  File "/home/spirillen/.local/lib/python3.10/site-packages/PyFunceble/checker/availability/domain.py", line 168, in query_status
    self.try_to_query_status_from_http_status_code()
  File "/home/spirillen/.local/lib/python3.10/site-packages/PyFunceble/checker/availability/base.py", line 900, in try_to_query_status_from_http_status_code
    lookup_result = self.http_status_code_query_tool.get_status_code()
  File "/home/spirillen/.local/lib/python3.10/site-packages/PyFunceble/query/http_status_code.py", line 122, in wrapper
    return func(self, *args, **kwargs)  # pylint: disable=not-callable
  File "/home/spirillen/.local/lib/python3.10/site-packages/PyFunceble/query/http_status_code.py", line 337, in get_status_code
    req = PyFunceble.factory.Requester.get(
  File "/home/spirillen/.local/lib/python3.10/site-packages/PyFunceble/query/requests/requester.py", line 213, in wrapper
    req = getattr(self.session, verb.lower())(*args, **kwargs)
  File "/home/spirillen/.local/lib/python3.10/site-packages/requests/sessions.py", line 600, in get
    return self.request("GET", url, **kwargs)
  File "/home/spirillen/.local/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/spirillen/.local/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/home/spirillen/.local/lib/python3.10/site-packages/PyFunceble/query/requests/adapter/http.py", line 129, in send
    response = super().send(request, **kwargs)
  File "/home/spirillen/.local/lib/python3.10/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/home/spirillen/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 815, in urlopen
    return self.urlopen(
  File "/home/spirillen/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/home/spirillen/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/spirillen/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.10/http/client.py", line 1374, in getresponse
    response.begin()
  File "/usr/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.10/http/client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.10/socket.py", line 705, in readinto
    return self._sock.recv_into(b)
KeyboardInterrupt
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/home/spirillen/.local/lib/python3.10/site-packages/PyFunceble/cli/processes/workers/base.py", line 320, in run
    worker_name, destination_worker, consumed = self.input_queue.get()
  File "<string>", line 2, in get
  File "/usr/lib/python3.10/multiprocessing/managers.py", line 818, in _callmethod
    kind, result = conn.recv()
  File "/usr/lib/python3.10/multiprocessing/connection.py", line 255, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.10/multiprocessing/connection.py", line 419, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.10/multiprocessing/connection.py", line 384, in _recv
    chunk = read(handle, remaining)
KeyboardInterrupt
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/home/spirillen/.local/lib/python3.10/site-packages/PyFunceble/cli/processes/workers/base.py", line 373, in run
    result = self.target(consumed)
  File "/home/spirillen/.local/lib/python3.10/site-packages/PyFunceble/cli/processes/workers/tester.py", line 292, in target
    .query_status()
  File "/home/spirillen/.local/lib/python3.10/site-packages/PyFunceble/checker/base.py", line 157, in wrapper
    return func(self, *args, **kwargs)  # pylint: disable=not-callable
  File "/home/spirillen/.local/lib/python3.10/site-packages/PyFunceble/checker/base.py", line 182, in wrapper
    result = func(self, *args, **kwargs)  # pylint: disable=not-callable
  File "/home/spirillen/.local/lib/python3.10/site-packages/PyFunceble/checker/availability/domain_and_ip.py", line 109, in query_status
    result = query_object.query_status()
  File "/home/spirillen/.local/lib/python3.10/site-packages/PyFunceble/checker/base.py", line 157, in wrapper
    return func(self, *args, **kwargs)  # pylint: disable=not-callable
  File "/home/spirillen/.local/lib/python3.10/site-packages/PyFunceble/checker/base.py", line 182, in wrapper
    result = func(self, *args, **kwargs)  # pylint: disable=not-callable
  File "/home/spirillen/.local/lib/python3.10/site-packages/PyFunceble/checker/availability/domain.py", line 168, in query_status
    self.try_to_query_status_from_http_status_code()
  File "/home/spirillen/.local/lib/python3.10/site-packages/PyFunceble/checker/availability/base.py", line 900, in try_to_query_status_from_http_status_code
    lookup_result = self.http_status_code_query_tool.get_status_code()
  File "/home/spirillen/.local/lib/python3.10/site-packages/PyFunceble/query/http_status_code.py", line 122, in wrapper
    return func(self, *args, **kwargs)  # pylint: disable=not-callable
  File "/home/spirillen/.local/lib/python3.10/site-packages/PyFunceble/query/http_status_code.py", line 337, in get_status_code
    req = PyFunceble.factory.Requester.get(
  File "/home/spirillen/.local/lib/python3.10/site-packages/PyFunceble/query/requests/requester.py", line 213, in wrapper
    req = getattr(self.session, verb.lower())(*args, **kwargs)
  File "/home/spirillen/.local/lib/python3.10/site-packages/requests/sessions.py", line 600, in get
    return self.request("GET", url, **kwargs)
  File "/home/spirillen/.local/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/spirillen/.local/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/home/spirillen/.local/lib/python3.10/site-packages/PyFunceble/query/requests/adapter/http.py", line 129, in send
    response = super().send(request, **kwargs)
  File "/home/spirillen/.local/lib/python3.10/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/home/spirillen/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/home/spirillen/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/spirillen/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.10/http/client.py", line 1374, in getresponse
    response.begin()
  File "/usr/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.10/http/client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.10/socket.py", line 705, in readinto
    return self._sock.recv_into(b)
KeyboardInterrupt
Process pyfunceble_tester_worker_5:
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/home/spirillen/.local/lib/python3.10/site-packages/PyFunceble/cli/processes/workers/base.py", line 373, in run
    result = self.target(consumed)
  File "/home/spirillen/.local/lib/python3.10/site-packages/PyFunceble/cli/processes/workers/tester.py", line 292, in target
    .query_status()
  File "/home/spirillen/.local/lib/python3.10/site-packages/PyFunceble/checker/base.py", line 157, in wrapper
    return func(self, *args, **kwargs)  # pylint: disable=not-callable
  File "/home/spirillen/.local/lib/python3.10/site-packages/PyFunceble/checker/base.py", line 182, in wrapper
    result = func(self, *args, **kwargs)  # pylint: disable=not-callable
  File "/home/spirillen/.local/lib/python3.10/site-packages/PyFunceble/checker/availability/domain_and_ip.py", line 109, in query_status
    result = query_object.query_status()
  File "/home/spirillen/.local/lib/python3.10/site-packages/PyFunceble/checker/base.py", line 157, in wrapper
    return func(self, *args, **kwargs)  # pylint: disable=not-callable
  File "/home/spirillen/.local/lib/python3.10/site-packages/PyFunceble/checker/base.py", line 182, in wrapper
    result = func(self, *args, **kwargs)  # pylint: disable=not-callable
  File "/home/spirillen/.local/lib/python3.10/site-packages/PyFunceble/checker/availability/domain.py", line 168, in query_status
    self.try_to_query_status_from_http_status_code()
  File "/home/spirillen/.local/lib/python3.10/site-packages/PyFunceble/checker/availability/base.py", line 900, in try_to_query_status_from_http_status_code
    lookup_result = self.http_status_code_query_tool.get_status_code()
  File "/home/spirillen/.local/lib/python3.10/site-packages/PyFunceble/query/http_status_code.py", line 122, in wrapper
    return func(self, *args, **kwargs)  # pylint: disable=not-callable
  File "/home/spirillen/.local/lib/python3.10/site-packages/PyFunceble/query/http_status_code.py", line 337, in get_status_code
    req = PyFunceble.factory.Requester.get(
  File "/home/spirillen/.local/lib/python3.10/site-packages/PyFunceble/query/requests/requester.py", line 213, in wrapper
    req = getattr(self.session, verb.lower())(*args, **kwargs)
  File "/home/spirillen/.local/lib/python3.10/site-packages/requests/sessions.py", line 600, in get
    return self.request("GET", url, **kwargs)
  File "/home/spirillen/.local/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/spirillen/.local/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/home/spirillen/.local/lib/python3.10/site-packages/PyFunceble/query/requests/adapter/http.py", line 129, in send
    response = super().send(request, **kwargs)
  File "/home/spirillen/.local/lib/python3.10/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/home/spirillen/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 815, in urlopen
    return self.urlopen(
  File "/home/spirillen/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/home/spirillen/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/spirillen/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.10/http/client.py", line 1374, in getresponse
    response.begin()
  File "/usr/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.10/http/client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.10/socket.py", line 705, in readinto
    return self._sock.recv_into(b)
KeyboardInterrupt
Process pyfunceble_tester_worker_1:
Changing Directory to GIT Dir
Storing test result in REPO
umount /tmp/pyfunceble
commit test results
warning: in the working copy of 'active_domains/output/explicit_content.domains.list/continue.csv', CRLF will be replaced by LF the next time Git touches it
[master 988106bb] Latest availability test with @pyfunceble
 15 files changed, 348 insertions(+), 176 deletions(-)
```

## Configuration
https://mypdns.org/clefspeare13/pornhosts/-/tree/6665094190cc4a1e71174dc4c7095fddbe87f8f8/PyFunceble

## Reproduction

1. Commit https://mypdns.org/clefspeare13/pornhosts/-/commit/6665094190cc4a1e71174dc4c7095fddbe87f8f8
2. Run `./toolbox/availability_test.bash` (https://mypdns.org/clefspeare13/pornhosts/-/blob/6665094190cc4a1e71174dc4c7095fddbe87f8f8/toolbox/availability_test.bash)

## Screenshots
Not needed

## Versions

**OS:** ubuntu 22 / conda

**Python Version:** 3.10

**PyFunceble Version:** 
(pyfunceble) $: some_path/clefspeare13/pornhosts$ pyfunceble --version
pyfunceble 4.1.3a4.dev (Blue Duckling: Ixora)

## Additional context
```shell
drill collection.dead-hosts.funilrys.com
;; ->>HEADER<<- opcode: QUERY, rcode: NOERROR, id: 16989
;; flags: qr rd ra ; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0 
;; QUESTION SECTION:
;; collection.dead-hosts.funilrys.com.  IN      A

;; ANSWER SECTION:
collection.dead-hosts.funilrys.com.     3600    IN      A       161.97.66.229
```

**Comment by funilrys** [comment]
It has nothing to do with my server. 
Those warnings are just warnings from `urllib` ... PyFunceble can handle them ... It's just that `urllib` prints those messages to STDOUT ...

**Comment by spirillen** [comment]
Ok, but why do it says the connection is broken then?

**Comment by funilrys** [comment]
That's what I'm trying to reproduce right now ... It seems that it has something to do with your tor node but I'm not sure yet ...

**Comment by funilrys** [comment]
So, your specific issue has probably something to do with the tor node you were communicating with. 
I can't reproduce the issue itself but I can reproduce similar issues where `urllib3` logs similar outputs. 

Therefore, https://github.com/funilrys/PyFunceble/commit/4056525e4ec86ac293b128958380b870a605d21f is decreasing the level of the urllib3 package. 

Please note: PyFunceble is capable of handling such situations... It's just that urllib3 logs unnecessarily.

**Comment by funilrys** [comment]
Please keep this issue open. It will be closed automatically, one the commit lands into the `dev` branch.
