### ISSUE TITLE
BUG | TypeError: argument of type 'NoneType' is not iterable [4.3.0a14.dev]

### ISSUE THREAD

**Issue by spirillen** [funilrys/PyFunceble#413]
### What is the problem you are experiencing?

I am experiencing a problem where...
Process ***_tester_worker_1:
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.13.1/x64/lib/python3.13/multiprocessing/process.py", line 313, in _bootstrap
    self.run()
    ~~~~~~~~^^
  File "/opt/hostedtoolcache/Python/3.13.1/x64/lib/python3.13/site-packages/***/cli/processes/workers/base.py", line 408, in run
    raise exception
  File "/opt/hostedtoolcache/Python/3.13.1/x64/lib/python3.13/site-packages/***/cli/processes/workers/base.py", line 380, in run
    result = self.target(consumed)
  File "/opt/hostedtoolcache/Python/3.13.1/x64/lib/python3.13/site-packages/***/cli/processes/workers/tester.py", line 287, in target
    self.testing_object.set_subject(test_dataset["idna_subject"])
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.13.1/x64/lib/python3.13/site-packages/***/checker/base.py", line 238, in set_subject
    self.subject = value
    ^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.13.1/x64/lib/python3.13/site-packages/***/checker/base.py", line 140, in wrapper
    self.subject_propagator()
    ~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/opt/hostedtoolcache/Python/3.13.1/x64/lib/python3.13/site-packages/***/checker/availability/base.py", line 519, in subject_propagator
    return super().subject_propagator()
           ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/opt/hostedtoolcache/Python/3.13.1/x64/lib/python3.13/site-packages/***/checker/base.py", line 387, in subject_propagator
    return self.query_common_checker()
           ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/opt/hostedtoolcache/Python/3.13.1/x64/lib/python3.13/site-packages/***/checker/availability/base.py", line 661, in query_common_checker
    self.domain_syntax_checker.is_valid_second_level()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/opt/hostedtoolcache/Python/3.13.1/x64/lib/python3.13/site-packages/***/checker/base.py", line 161, in wrapper
    return func(self, *args, **kwargs)  # pylint: disable=not-callable
  File "/opt/hostedtoolcache/Python/3.13.1/x64/lib/python3.13/site-packages/***/checker/syntax/domain.py", line 116, in is_valid_second_level
    return self.second_level_checker.is_valid()
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/opt/hostedtoolcache/Python/3.13.1/x64/lib/python3.13/site-packages/***/checker/base.py", line 161, in wrapper
    return func(self, *args, **kwargs)  # pylint: disable=not-callable
  File "/opt/hostedtoolcache/Python/3.13.1/x64/lib/python3.13/site-packages/***/checker/syntax/second_lvl_domain.py", line 97, in is_valid
    extension not in self.iana_dataset
  File "/opt/hostedtoolcache/Python/3.13.1/x64/lib/python3.13/site-packages/***/dataset/iana.py", line 75, in __contains__
    return value in self.get_content()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable
.............Fatal Error: argument of type 'NoneType' is not iterable
Error: Process completed with exit code 1.

### How can we reproduce the problem?

To reproduce the problem:

1.
2.
3.
4.
https://github.com/mypdns/matrix/actions/runs/12529225788
https://github.com/mypdns/matrix/actions/runs/12528176670
https://github.com/mypdns/matrix/actions/runs/12526259637
https://github.com/mypdns/matrix/actions/runs/12520450447

### Do you have a screenshot?

<details><summary>Screenshot</summary>
</details>


### What did you expect to happen?

I expected that...


### Is there a workaround?

I found a workaround...
IT ti run stable 

### How did you configure PyFunceble?

https://github.com/mypdns/matrix/blob/266fae14b9f329a60df33f7cd62c560dd9944d4a/.pyfunceble/.PyFunceble.overwrite.yaml

### Which Operating System did you use?

Ubuntu 22.04 LTS

### Which Python Version did you use?

3.13

### Which PyFunceble Version did you use?

4.3.0a14.dev

### Additional context

I would like to add...

**Comment by funilrys** [comment]
This is interesting. It can only happen when the iana file couldn't be downloaded ... 🤔 I can't remember GitHub being down ...

**Comment by spirillen** [comment]
Vladimir Putin?, Recep Tayyip Erdoğan?, Xi Jinping?, Kim Jong Un?, they are all busy, making trouble in the west these days, latest on Greenland and France
