### ISSUE TITLE
Memory leak? at least a huge memory consumption

### ISSUE THREAD

**Issue by spirillen** [funilrys/PyFunceble#46]
## Bug description
I'm running this app (only) on a virtual host with 4GB, but after a while it have eaten all the memory to final fail 

```
$ free -m
              total        used        free      shared  buff/cache   available
Mem:           3850        3014         326          29         509         596
Swap:             0           0           0
```

```
5 minutes later...
free -m
              total        used        free      shared  buff/cache   available
Mem:           3850        3097         242          29         510         513
Swap:             0           0           0
```

## Modifications under `.PyFunceble.yaml`
Ask @mitchellkrogza running on his [Badd-Boyz-Hosts](https://github.com/mitchellkrogza/Badd-Boyz-Hosts)

## Reproduction

Open source at https://github.com/spirillen/Dead-Domains

## Expected behavior**
freeing memory as each query is processed and written to disk

## Versions

**OS:** Debian 10, (Buster)
**Python Version:** Python 3.7.3
**PyFunceble Version:** pyfunceble 2.2.0. (Green Galago: Skitterbug)

## Additional context
None

**Comment by funilrys** [comment]
Hi @spirillen, are you using the `--multiprocess` switch?

I planned a review or a complete rewrite of the way I handle and read a file in order to remove unused information from memory. I will come back to this issue when I'm that far.

Thanks for the feedback.

Cheers,
Nissar

**Comment by spirillen** [comment]
Hi @funilrys now you mention it.... I do use `-m -p 2` 

I will fetch you full command when it fails in a couple of minuts, then you can have the `free` stat when it's not running + the failure output...

I'll be back.....

**Comment by spirillen** [comment]
The promised output when it crash

```python
Traceback (most recent call last):
  File "/usr/local/bin/pyfunceble", line 10, in <module>
    sys.exit(_command_line())
  File "/usr/local/lib/python3.7/dist-packages/PyFunceble/__init__.py", line 1494, in _command_line
    link_to_test=ARGS.link,
  File "/usr/local/lib/python3.7/dist-packages/PyFunceble/dispatcher.py", line 109, in __init__
    file_path, "domain"
  File "/usr/local/lib/python3.7/dist-packages/PyFunceble/file_multiprocess_core.py", line 429, in read_and_test_file_content
    self._get_list_to_of_subjects_to_test_from_file(file), manager
  File "/usr/local/lib/python3.7/dist-packages/PyFunceble/file_multiprocess_core.py", line 278, in __run_multiprocess_test
    process.start()
  File "/usr/lib/python3.7/multiprocessing/process.py", line 112, in start
    self._popen = self._Popen(self)
  File "/usr/lib/python3.7/multiprocessing/context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/usr/lib/python3.7/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
  File "/usr/lib/python3.7/multiprocessing/popen_fork.py", line 20, in __init__
    self._launch(process_obj)
  File "/usr/lib/python3.7/multiprocessing/popen_fork.py", line 70, in _launch
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory
```

and the memory stats when PyFunceble is inactive

```
free -m
              total        used        free      shared  buff/cache   available
Mem:           3850        1618        2073          29         158        2021
Swap:             0           0           0
```

**Comment by funilrys** [comment]
So, this issue is related to the warning message I introduced into the dev branch :)

![2019-10-03-185707_3360x1080_scrot](https://user-images.githubusercontent.com/14127285/66147729-b65da880-e60f-11e9-94bb-bc7c28f6f833.png)

There is one solution, but I will have to write 2 switches :thinking: Indeed, actually we do the merging (the release of RAM safed information) at the end of the instance. In the beginning, it was after 2 processes finished in your case. But then people especially @mitchellkrogza  argued that it takes time. But yeah they were using 30+ processes which is normal.

I may write the patch which the 2 switches:
* Merge while testing
* Merge at the end


-------------------------------

I'm working for a few days on a third database type in the form of a REST-API which could make every instance in the world be "interconnected" but it's just the beginning of an idea. 🙂 

The future of PyFunceble may be: the interconnection of information.
Indeed, actually everybody has its own information locally but what if someone else already tested your list or element of your list and the results are from a few days ago? You will probably want it to gain some time.

That's what I'm working on. It's not easy as all of those data will have to stay anonymous and saved somewhere but I hope to release it and test it with @Ultimate-Hosts-Blacklist soon.


Let me know if something is not clear or if you have any other questions.

Cheers,
Nissar

**Comment by spirillen** [comment]
Hi Nissar thanks for the in depth reply, and I'm in love with your idea for making the API and your concerns about privacy. But that API would have to connect to a central DB/API with a pretty high caching level as that would be a hole lot of queries. But I sure following your thoughts on this.

I'm thinking but there is not something that's popups to my brain for an submission...

Damned that is some project you started there....

**Comment by funilrys** [comment]
@spirillen,

> But that API would have to connect to a central DB/API with a pretty high caching level as that would be a whole lot of queries.

That's actually the biggest problem. For how much time the data should be stored, and how we distribute them efficiently.

> I'm thinking but there is not something that's popups to my brain for a submission...

Let me know if something comes in mind. This is not only MY project :wink: As it is used by more and more infrastructure, people, ideas and lists, it's actually becoming everyone's project now :smile_cat: 

> Damned that is some project you started there...

Yeah, and it started 2 years ago (next week as it was on `2017-10-15T08:25:14Z`) :joy_cat: with Funceble 😊

-------------------------------------
Hey, I just released the `--multiprocessing-merge-mode` under the dev branch. Do you mind testing it for us? Thanks in advance.

Have a nice day/night.

Cheers,
Nissar

**Comment by spirillen** [comment]
Hey @funilrys 

There is one properly crazy idea, that pops up in my head and it would be a combination of yours and my project...   

We are working with DNS records, right!

> The "NEW" world presents RPZ, now let's combine these two worlds, where we have the Rcode.responses which already is highly cacheble ( My DNS can handle ~250.000qps on 1vcpu/1gb-ram) 

Now if you ask a living domain which should be blocked, we respond with NXDOMAIN
If domain is alive and should NOT be blocked we responded with an (A|AAAA).record not matching (0.0.0.0|127.0.0.1)
Response servfail = not active domain

All of this requires your and @mitchellkrogza python skills, but it is very durable...

I saw you and Mitchell was one some chat, but forgot where, but hit me up and we can make some test/brainstorm on this


> Hey, I just released the --multiprocessing-merge-mode under the dev branch. Do you mind testing it for us? Thanks in advance.

Sure, I'll do this a bit later :smile: 

Cheers Spirillen

**Comment by spirillen** [comment]
Not good I'm affraid

Installed in python3 venv
`python3 -m pip install git+https://github.com/funilrys/PyFunceble.git@dev`

My first run was hanging after 3 lines and then first very mush later testing next 3 lines.

Command used:
```
pyfunceble -dbr 14  --plain --syntax --hierarchical -m -p 2 -f /root/world-dumbest-ultimate-hosts-blacklist/UltimateWorldBiggestDumbestHosts.hosts
```
Terminated by me

Last run:

Command:
```
pyfunceble --syntax -m -p 2 -f /root/world-dumbest-ultimate-hosts-blacklist/UltimateWorldBiggestDumbestHosts.hosts
```
Log:
```
Traceback (most recent call last):
  File "/tmp/pyf/bin/pyfunceble", line 11, in <module>
    load_entry_point('PyFunceble-dev==2.16.1', 'console_scripts', 'pyfunceble')()
  File "/tmp/pyf/lib/python3.7/site-packages/PyFunceble/__init__.py", line 1612, in _command_line
    raise e
  File "/tmp/pyf/lib/python3.7/site-packages/PyFunceble/__init__.py", line 1607, in _command_line
    link_to_test=args.link,
  File "/tmp/pyf/lib/python3.7/site-packages/PyFunceble/dispatcher.py", line 104, in __init__
    self.dispatch_file_test(file_path)
  File "/tmp/pyf/lib/python3.7/site-packages/PyFunceble/dispatcher.py", line 129, in dispatch_file_test
    FileMultiprocessCore(file_path, "domain").read_and_test_file_content()
  File "/tmp/pyf/lib/python3.7/site-packages/PyFunceble/file_multiprocess_core.py", line 419, in read_and_test_file_content
    self._get_list_to_of_subjects_to_test_from_file(file), manager
  File "/tmp/pyf/lib/python3.7/site-packages/PyFunceble/file_multiprocess_core.py", line 287, in __run_multiprocess_test
    process.start()
  File "/usr/lib/python3.7/multiprocessing/process.py", line 112, in start
    self._popen = self._Popen(self)
  File "/usr/lib/python3.7/multiprocessing/context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/usr/lib/python3.7/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
  File "/usr/lib/python3.7/multiprocessing/popen_fork.py", line 20, in __init__
    self._launch(process_obj)
  File "/usr/lib/python3.7/multiprocessing/popen_fork.py", line 70, in _launch
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory
```

A few test runs on travis:
https://travis-ci.com/spirillen/Dead-Domains/builds/131229078
https://travis-ci.com/spirillen/Dead-Domains/builds/131226982
https://travis-ci.com/spirillen/Dead-Domains/builds/131225496

Test command for travis:
https://github.com/spirillen/Dead-Domains/commits/master/dev-tools/DataTesting.sh

Look at the `Commits on Oct 10, 2019`

**Comment by funilrys** [comment]
Uhh interesting ... A `--syntax` check has less (if not none) memory impact 🤯

Thanks for the feedback!

**Comment by funilrys** [comment]
By the way, the SQLite db-type will be dropped in the future (already the case in the dev branch). It's not as efficient as the `mariadb` or `mysql` database types while doing some multiprocessing.

**Comment by spirillen** [comment]
> By the way, the SQLite db-type will be dropped in the future (already the case in the dev branch). It's not as efficient as the `mariadb` or `mysql` database types while doing some multiprocessing.

That was only a fast "test" to "overrule" the the warning about the use of .json db on multiprocessing as no other sql is installed on that temponary installation

And now you mention `--syntax` it's slow.... and does not generating any output file on it's own (As far I have found) that's why I felt like i have to combine the use of `--plain --syntax` to get a plain valid output list I could use to make my promised [test here](https://github.com/StevenBlack/hosts/issues/1057#issuecomment-536523175)

**Comment by funilrys** [comment]
@spirillen, Can you rerun your tests for us (with the dev version)? :smile: 

Thanks in advance.

Cheers,
Nissar

**Comment by spirillen** [comment]
Done.... On a local run in python3 venv it still raises the memory usage step by step up to about 80mb for a list of 121 domains

By installing from git you migt be missing the wheel requirement in the setup.py

```python
env/bin/python3 -m pip install git+https://github.com/funilrys/PyFunceble@dev

Collecting git+https://github.com/funilrys/PyFunceble@dev
  Cloning https://github.com/funilrys/PyFunceble (to revision dev) to ./pip-req-build-v7yxw_wo
Branch 'dev' set up to track remote branch 'dev' from 'origin'.
Switched to a new branch 'dev'
Collecting PyMySQL (from PyFunceble-dev==2.17.9)
  Downloading https://files.pythonhosted.org/packages/ed/39/15045ae46f2a123019aa968dfcba0396c161c20f855f11dea6796bcaae95/PyMySQL-0.9.3-py2.py3-none-any.whl (47kB)
    100% |████████████████████████████████| 51kB 430kB/s 
Collecting PyYAML (from PyFunceble-dev==2.17.9)
  Downloading https://files.pythonhosted.org/packages/e3/e8/b3212641ee2718d556df0f23f78de8303f068fe29cdaa7a91018849582fe/PyYAML-5.1.2.tar.gz (265kB)
    100% |████████████████████████████████| 266kB 851kB/s 
Collecting colorama (from PyFunceble-dev==2.17.9)
  Downloading https://files.pythonhosted.org/packages/4f/a6/728666f39bfff1719fc94c481890b2106837da9318031f71a8424b662e12/colorama-0.4.1-py2.py3-none-any.whl
Collecting cryptography (from PyFunceble-dev==2.17.9)
  Downloading https://files.pythonhosted.org/packages/45/73/d18a8884de8bffdcda475728008b5b13be7fbef40a2acc81a0d5d524175d/cryptography-2.8-cp34-abi3-manylinux1_x86_64.whl (2.3MB)
    100% |████████████████████████████████| 2.3MB 377kB/s 
Collecting dnspython (from PyFunceble-dev==2.17.9)
  Downloading https://files.pythonhosted.org/packages/ec/d3/3aa0e7213ef72b8585747aa0e271a9523e713813b9a20177ebe1e939deb0/dnspython-1.16.0-py2.py3-none-any.whl (188kB)
    100% |████████████████████████████████| 194kB 817kB/s 
Collecting domain2idna>=1.6.1 (from PyFunceble-dev==2.17.9)
  Downloading https://files.pythonhosted.org/packages/0b/e0/e9a7b7eed79a97dbb4a6b8deaafa054a3b5e06c5051ce86831c34a63b501/domain2idna-1.8.0-py3-none-any.whl
Collecting python-box (from PyFunceble-dev==2.17.9)
  Downloading https://files.pythonhosted.org/packages/0a/8f/1797a73eb18d55aafe7a4a97ad9be88eb352b97bca58cfc10226d263d177/python_box-3.4.5-py2.py3-none-any.whl
Collecting python-dotenv (from PyFunceble-dev==2.17.9)
  Downloading https://files.pythonhosted.org/packages/57/c8/5b14d5cffe7bb06bedf9d66c4562bf90330d3d35e7f0266928c370d9dd6d/python_dotenv-0.10.3-py2.py3-none-any.whl
Collecting requests (from PyFunceble-dev==2.17.9)
  Downloading https://files.pythonhosted.org/packages/51/bd/23c926cd341ea6b7dd0b2a00aba99ae0f828be89d72b2190f27c11d4b7fb/requests-2.22.0-py2.py3-none-any.whl (57kB)
    100% |████████████████████████████████| 61kB 144kB/s 
Requirement already satisfied: setuptools in ./env/lib/python3.7/site-packages (from PyFunceble-dev==2.17.9) (40.8.0)
Collecting urllib3 (from PyFunceble-dev==2.17.9)
  Downloading https://files.pythonhosted.org/packages/e0/da/55f51ea951e1b7c63a579c09dd7db825bb730ec1fe9c0180fc77bfb31448/urllib3-1.25.6-py2.py3-none-any.whl (125kB)
    100% |████████████████████████████████| 133kB 407kB/s 
Collecting cffi!=1.11.3,>=1.8 (from cryptography->PyFunceble-dev==2.17.9)
  Downloading https://files.pythonhosted.org/packages/fa/20/b93b26ad86f48403144823f521aa571a71e61575863a260cca2918ec3881/cffi-1.13.0-cp37-cp37m-manylinux1_x86_64.whl (430kB)
    100% |████████████████████████████████| 440kB 337kB/s 
Collecting six>=1.4.1 (from cryptography->PyFunceble-dev==2.17.9)
  Downloading https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
Collecting certifi>=2017.4.17 (from requests->PyFunceble-dev==2.17.9)
  Downloading https://files.pythonhosted.org/packages/18/b0/8146a4f8dd402f60744fa380bc73ca47303cccf8b9190fd16a827281eac2/certifi-2019.9.11-py2.py3-none-any.whl (154kB)
    100% |████████████████████████████████| 163kB 375kB/s 
Collecting idna<2.9,>=2.5 (from requests->PyFunceble-dev==2.17.9)
  Downloading https://files.pythonhosted.org/packages/14/2c/cd551d81dbe15200be1cf41cd03869a46fe7226e7450af7a6545bfc474c9/idna-2.8-py2.py3-none-any.whl (58kB)
    100% |████████████████████████████████| 61kB 618kB/s 
Collecting chardet<3.1.0,>=3.0.2 (from requests->PyFunceble-dev==2.17.9)
  Downloading https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl (133kB)
    100% |████████████████████████████████| 143kB 293kB/s 
Collecting pycparser (from cffi!=1.11.3,>=1.8->cryptography->PyFunceble-dev==2.17.9)
  Downloading https://files.pythonhosted.org/packages/68/9e/49196946aee219aead1290e00d1e7fdeab8567783e83e1b9ab5585e6206a/pycparser-2.19.tar.gz (158kB)
    100% |████████████████████████████████| 163kB 551kB/s 
Building wheels for collected packages: PyFunceble-dev, PyYAML, pycparser
  Running setup.py bdist_wheel for PyFunceble-dev ... error
  Complete output from command /tmp/env/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-req-build-v7yxw_wo/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-lqhz4ilt --python-tag cp37:
  usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help
  
  error: invalid command 'bdist_wheel'
  
  ----------------------------------------
  Failed building wheel for PyFunceble-dev
  Running setup.py clean for PyFunceble-dev
  Running setup.py bdist_wheel for PyYAML ... error
  Complete output from command /tmp/env/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-zvs0pzb4/PyYAML/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-7rkq4mdz --python-tag cp37:
  usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help
  
  error: invalid command 'bdist_wheel'
  
  ----------------------------------------
  Failed building wheel for PyYAML
  Running setup.py clean for PyYAML
  Running setup.py bdist_wheel for pycparser ... error
  Complete output from command /tmp/env/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-zvs0pzb4/pycparser/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-e08c2g61 --python-tag cp37:
  usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help
  
  error: invalid command 'bdist_wheel'
  
  ----------------------------------------
  Failed building wheel for pycparser
  Running setup.py clean for pycparser
Failed to build PyFunceble-dev PyYAML pycparser
Installing collected packages: PyMySQL, PyYAML, colorama, pycparser, cffi, six, cryptography, dnspython, domain2idna, python-box, python-dotenv, certifi, idna, urllib3, chardet, requests, PyFunceble-dev
  Running setup.py install for PyYAML ... done
  Running setup.py install for pycparser ... done
  Running setup.py install for PyFunceble-dev ... done
Successfully installed PyFunceble-dev-2.17.9 PyMySQL-0.9.3 PyYAML-5.1.2 certifi-2019.9.11 cffi-1.13.0 chardet-3.0.4 colorama-0.4.1 cryptography-2.8 dnspython-1.16.0 domain2idna-1.8.0 idna-2.8 pycparser-2.19 python-box-3.4.5 python-dotenv-0.10.3 requests-2.22.0 six-1.12.0 urllib3-1.25.6
```

The install succeed when wheel is "pre-installed"

```python
env/bin/python3 -m pip install git+https://github.com/funilrys/PyFunceble@dev

Collecting git+https://github.com/funilrys/PyFunceble@dev
  Cloning https://github.com/funilrys/PyFunceble (to revision dev) to ./pip-req-build-7inf3y4m
Branch 'dev' set up to track remote branch 'dev' from 'origin'.
Switched to a new branch 'dev'
Requirement already satisfied: PyMySQL in ./env/lib/python3.7/site-packages (from PyFunceble-dev==2.17.9) (0.9.3)
Requirement already satisfied: PyYAML in ./env/lib/python3.7/site-packages (from PyFunceble-dev==2.17.9) (5.1.2)
Requirement already satisfied: colorama in ./env/lib/python3.7/site-packages (from PyFunceble-dev==2.17.9) (0.4.1)
Requirement already satisfied: cryptography in ./env/lib/python3.7/site-packages (from PyFunceble-dev==2.17.9) (2.8)
Requirement already satisfied: dnspython in ./env/lib/python3.7/site-packages (from PyFunceble-dev==2.17.9) (1.16.0)
Requirement already satisfied: domain2idna>=1.6.1 in ./env/lib/python3.7/site-packages (from PyFunceble-dev==2.17.9) (1.8.0)
Requirement already satisfied: python-box in ./env/lib/python3.7/site-packages (from PyFunceble-dev==2.17.9) (3.4.5)
Requirement already satisfied: python-dotenv in ./env/lib/python3.7/site-packages (from PyFunceble-dev==2.17.9) (0.10.3)
Requirement already satisfied: requests in ./env/lib/python3.7/site-packages (from PyFunceble-dev==2.17.9) (2.22.0)
Requirement already satisfied: setuptools in ./env/lib/python3.7/site-packages (from PyFunceble-dev==2.17.9) (40.8.0)
Requirement already satisfied: urllib3 in ./env/lib/python3.7/site-packages (from PyFunceble-dev==2.17.9) (1.25.6)
Requirement already satisfied: cffi!=1.11.3,>=1.8 in ./env/lib/python3.7/site-packages (from cryptography->PyFunceble-dev==2.17.9) (1.13.0)
Requirement already satisfied: six>=1.4.1 in ./env/lib/python3.7/site-packages (from cryptography->PyFunceble-dev==2.17.9) (1.12.0)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in ./env/lib/python3.7/site-packages (from requests->PyFunceble-dev==2.17.9) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in ./env/lib/python3.7/site-packages (from requests->PyFunceble-dev==2.17.9) (2019.9.11)
Requirement already satisfied: idna<2.9,>=2.5 in ./env/lib/python3.7/site-packages (from requests->PyFunceble-dev==2.17.9) (2.8)
Requirement already satisfied: pycparser in ./env/lib/python3.7/site-packages (from cffi!=1.11.3,>=1.8->cryptography->PyFunceble-dev==2.17.9) (2.19)
Building wheels for collected packages: PyFunceble-dev
  Running setup.py bdist_wheel for PyFunceble-dev ... done
  Stored in directory: /tmp/pip-ephem-wheel-cache-qoamh0mn/wheels/44/41/66/3755d1f6f41637a0b1dcee7da30ac84c92b3642b27ffc3e6a3
Successfully built PyFunceble-dev
Installing collected packages: PyFunceble-dev
Successfully installed PyFunceble-dev-2.17.9
```

I'll run a bigger test a bit later, but this is first respond

**Comment by spirillen** [comment]
Second report from that big fat list....

memstats:

Before running
```
free -h
              total        used        free      shared  buff/cache   available
Mem:          3,8Gi       576Mi       3,0Gi        38Mi       179Mi       3,0Gi
Swap:            0B          0B          0B
```

After start:
```
free -h
              total        used        free      shared  buff/cache   available
Mem:          3,8Gi       1,1Gi       1,7Gi        38Mi       979Mi       2,4Gi
Swap:            0B          0B          0B
```

Running command:
```python
pyfunceble --plain -m -p 2 -f /root/world-dumbest-ultimate-hosts-blacklist/UltimateWorldBiggestDumbestHosts.hosts
```


Error:
```python
Traceback (most recent call last):
  File "/tmp/env/bin/pyfunceble", line 10, in <module>
    sys.exit(_command_line())
  File "/tmp/env/lib/python3.7/site-packages/PyFunceble/__init__.py", line 1618, in _command_line
    raise e
  File "/tmp/env/lib/python3.7/site-packages/PyFunceble/__init__.py", line 1613, in _command_line
    generate_results_only=args.generate_files_from_database,
  File "/tmp/env/lib/python3.7/site-packages/PyFunceble/dispatcher.py", line 108, in __init__
    self.dispatch_file_test(file_path, generate_results_only)
  File "/tmp/env/lib/python3.7/site-packages/PyFunceble/dispatcher.py", line 137, in dispatch_file_test
    FileMultiprocessCore(file_path, "domain").read_and_test_file_content()
  File "/tmp/env/lib/python3.7/site-packages/PyFunceble/file_multiprocess_core.py", line 435, in read_and_test_file_content
    self._get_list_to_of_subjects_to_test_from_file(file), manager
  File "/tmp/env/lib/python3.7/site-packages/PyFunceble/file_multiprocess_core.py", line 290, in __run_multiprocess_test
    process.start()
  File "/usr/lib/python3.7/multiprocessing/process.py", line 112, in start
    self._popen = self._Popen(self)
  File "/usr/lib/python3.7/multiprocessing/context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/usr/lib/python3.7/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
  File "/usr/lib/python3.7/multiprocessing/popen_fork.py", line 20, in __init__
    self._launch(process_obj)
  File "/usr/lib/python3.7/multiprocessing/popen_fork.py", line 70, in _launch
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory
```

## A second test with the `--syntax` variable enabled

```
pyfunceble --plain --syntax -m -p 2 -f /root/world-dumbest-ultimate-hosts-blacklist/UltimateWorldBiggestDumbestHosts.hosts
```

Memstat before running
```
free -h
              total        used        free      shared  buff/cache   available
Mem:          3,8Gi       575Mi       3,1Gi        38Mi       147Mi       3,0Gi
Swap:            0B          0B          0B
```

Memstat after script start
```
free -h
              total        used        free      shared  buff/cache   available
Mem:          3,8Gi       1,4Gi       2,2Gi        38Mi       217Mi       2,2Gi
Swap:            0B          0B          0B
```

Error:
```python
On it's way, waiting for failure to occure
```

**Comment by funilrys** [comment]
Thanks. May I ask the size of `inactive_db.json`, `whois_db.json` and `output/continue.json` before you start it ?

**Comment by funilrys** [comment]
About `bdist_wheel` ... I can't explain it ...

```shell
(venv) $ pip install git+https://github.com/funilrys/PyFunceble@dev
Collecting git+https://github.com/funilrys/PyFunceble@dev
  Cloning https://github.com/funilrys/PyFunceble (to revision dev) to /tmp/pip-req-build-oqjnqz23
  Running command git clone -q https://github.com/funilrys/PyFunceble /tmp/pip-req-build-oqjnqz23
  Running command git checkout -b dev --track origin/dev
  Zu neuem Branch 'dev' gewechselt
  Branch 'dev' folgt nun Remote-Branch 'dev' von 'origin'.
Collecting colorama
  Using cached https://files.pythonhosted.org/packages/4f/a6/728666f39bfff1719fc94c481890b2106837da9318031f71a8424b662e12/colorama-0.4.1-py2.py3-none-any.whl
Collecting cryptography
  Using cached https://files.pythonhosted.org/packages/ca/9a/7cece52c46546e214e10811b36b2da52ce1ea7fa203203a629b8dfadad53/cryptography-2.8-cp34-abi3-manylinux2010_x86_64.whl
Collecting dnspython
  Using cached https://files.pythonhosted.org/packages/ec/d3/3aa0e7213ef72b8585747aa0e271a9523e713813b9a20177ebe1e939deb0/dnspython-1.16.0-py2.py3-none-any.whl
Collecting domain2idna>=1.6.1
  Using cached https://files.pythonhosted.org/packages/0b/e0/e9a7b7eed79a97dbb4a6b8deaafa054a3b5e06c5051ce86831c34a63b501/domain2idna-1.8.0-py3-none-any.whl
Collecting PyMySQL
  Using cached https://files.pythonhosted.org/packages/ed/39/15045ae46f2a123019aa968dfcba0396c161c20f855f11dea6796bcaae95/PyMySQL-0.9.3-py2.py3-none-any.whl
Collecting python-box
  Using cached https://files.pythonhosted.org/packages/0a/8f/1797a73eb18d55aafe7a4a97ad9be88eb352b97bca58cfc10226d263d177/python_box-3.4.5-py2.py3-none-any.whl
Collecting python-dotenv
  Using cached https://files.pythonhosted.org/packages/57/c8/5b14d5cffe7bb06bedf9d66c4562bf90330d3d35e7f0266928c370d9dd6d/python_dotenv-0.10.3-py2.py3-none-any.whl
Processing /home/funilrys/.cache/pip/wheels/d9/45/dd/65f0b38450c47cf7e5312883deb97d065e030c5cca0a365030/PyYAML-5.1.2-cp37-cp37m-linux_x86_64.whl
Collecting requests
  Using cached https://files.pythonhosted.org/packages/51/bd/23c926cd341ea6b7dd0b2a00aba99ae0f828be89d72b2190f27c11d4b7fb/requests-2.22.0-py2.py3-none-any.whl
Requirement already satisfied: setuptools in ./venv/lib/python3.7/site-packages (from PyFunceble-dev==2.17.9) (41.4.0)
Collecting urllib3
  Using cached https://files.pythonhosted.org/packages/e0/da/55f51ea951e1b7c63a579c09dd7db825bb730ec1fe9c0180fc77bfb31448/urllib3-1.25.6-py2.py3-none-any.whl
Collecting cffi!=1.11.3,>=1.8
  Using cached https://files.pythonhosted.org/packages/fa/20/b93b26ad86f48403144823f521aa571a71e61575863a260cca2918ec3881/cffi-1.13.0-cp37-cp37m-manylinux1_x86_64.whl
Collecting six>=1.4.1
  Using cached https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
Collecting idna<2.9,>=2.5
  Using cached https://files.pythonhosted.org/packages/14/2c/cd551d81dbe15200be1cf41cd03869a46fe7226e7450af7a6545bfc474c9/idna-2.8-py2.py3-none-any.whl
Collecting certifi>=2017.4.17
  Using cached https://files.pythonhosted.org/packages/18/b0/8146a4f8dd402f60744fa380bc73ca47303cccf8b9190fd16a827281eac2/certifi-2019.9.11-py2.py3-none-any.whl
Collecting chardet<3.1.0,>=3.0.2
  Using cached https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl
Processing /home/funilrys/.cache/pip/wheels/f2/9a/90/de94f8556265ddc9d9c8b271b0f63e57b26fb1d67a45564511/pycparser-2.19-py2.py3-none-any.whl
Building wheels for collected packages: PyFunceble-dev
  Building wheel for PyFunceble-dev (setup.py) ... done
  Created wheel for PyFunceble-dev: filename=PyFunceble_dev-2.17.9-cp37-none-any.whl size=174399 sha256=dbf45e92d04ba39c868d6d134dd16ba1c84db5bc6263eefa5057e22f8e2e0405
  Stored in directory: /tmp/pip-ephem-wheel-cache-1hxi4sks/wheels/44/41/66/3755d1f6f41637a0b1dcee7da30ac84c92b3642b27ffc3e6a3
Successfully built PyFunceble-dev
Installing collected packages: colorama, pycparser, cffi, six, cryptography, dnspython, domain2idna, PyMySQL, python-box, python-dotenv, PyYAML, idna, certifi, chardet, urllib3, requests, PyFunceble-dev
Successfully installed PyFunceble-dev-2.17.9 PyMySQL-0.9.3 PyYAML-5.1.2 certifi-2019.9.11 cffi-1.13.0 chardet-3.0.4 colorama-0.4.1 cryptography-2.8 dnspython-1.16.0 domain2idna-1.8.0 idna-2.8 pycparser-2.19 python-box-3.4.5 python-dotenv-0.10.3 requests-2.22.0 six-1.12.0 urllib3-1.25.6
```

**Comment by spirillen** [comment]
Did you try in a fresh env folder? cos if wheel was installed I didn't get the error either.

**Comment by funilrys** [comment]
> Did you try in a fresh env folder? cos if wheel was installed I didn't get the error either.

I tested it from a fresh virtualenv (with `--always-copy`) indeed.

**Comment by funilrys** [comment]
@spirillen The `restructuration` branch might solve this. But please keep in mind that even I reduced the memory consumption, the databases (JSON db type) are kept in memory... And I can't change that.

Cheers,
Nissar

**Comment by funilrys** [comment]
Can we resume what's working and what's not working now that I merged the `restructuration` branch into the `dev` branch?

Thanks!

**Comment by spirillen** [comment]
For my case I will concur it's working :smiley:
