### ISSUE TITLE
Add a function to check a list of URLs for invalid URLs only.

### ISSUE THREAD

**Issue by ZeroDot1** [funilrys/PyFunceble#50]
**Is your feature request related to a problem? Please describe.**
It takes far too long to test all URLs of a list (Slow Internet).
It would therefore be very good if you could check a list of URLs only for incorrect URLs.
Without DNS query or so, only a check if all URLs are correct and if no errors have occurred e.g. a dot at the end of a URL.

**Describe the solution you'd like**
When I check a list of domains I only want to check if all URLs are correct.
And if there are invalid URLs these should be output in a file.

**Describe alternatives you've considered**
The alternative is to check everything manually, but it takes too much time.

**Additional context**
Example domains for testing: ()
```
0.0.0.0 194.58.122.146\032stratum.aikapool.com
0.0.0.0 POOL.moneropool.com
0.0.0.0 aikapool.com.
0.0.0.0 VPWCHCDEVWEB001.cryptopia.co.nz
0.0.0.0 aikapool.comwww.aikapool.com
```
All these URLs should be output to an extra file with a switch `--invalidcheck`.
Such a feature is very useful because it allows you to create accurate updates and save a lot of time.

**Comment by funilrys** [comment]
Hi @ZeroDot1 and thanks for the feedback!

Did you try to append the `--syntax` flag? 

Cheers,
Nissar

**Comment by ZeroDot1** [comment]
Hi @funilrys,
I use the --syntax (Configfile) flag but not all incorrect URLs are detected.
`PyFunceble -m -a -f '//list3.txt'`

Testfile 
```bash
0.0.0.0 google.de 
amazon.com
0.0.0.0 golem.de
heise.de
twitter.com
t.co
0.0.0.0 194.58.122.146\032stratum.aikapool.com
0.0.0.0 POOL.moneropool.com
0.0.0.0 aikapool.com. # Not detected
0.0.0.0 VPWCHCDEVWEB001.cryptopia.co.nz
0.0.0.0 aikapool.comwww.aikapool.com # Not detected
gitlab.com
github.com
//github.com
github./com
github.com/
github.com/.
http://github.com/
```

```bash
Subject                                                                                              Status      Expiration Date   Source     Analyze Date        
---------------------------------------------------------------------------------------------------- ----------- ----------------- ---------- --------------------
VPWCHCDEVWEB001.cryptopia.co.nz                                                                      INVALID     Unknown           SYNTAX     Fri 01 Nov 14:11:51 CET 2019github.com                                                                                           VALID       Unknown           SYNTAX     Fri 01 Nov 14:11:51 CET 2019

amazon.com                                                                                           VALID       Unknown           SYNTAX     Fri 01 Nov 14:11:51 CET 2019
heise.de                                                                                             VALID       Unknown           SYNTAX     Fri 01 Nov 14:11:51 CET 2019
http://github.com/                                                                                   INVALID     Unknown           SYNTAX     Fri 01 Nov 14:11:51 CET 2019
gitlab.com                                                                                           VALID       Unknown           SYNTAX     Fri 01 Nov 14:11:51 CET 2019
google.de                                                                                            VALID       Unknown           SYNTAX     Fri 01 Nov 14:11:51 CET 2019
//github.com                                                                                         INVALID     Unknown           SYNTAX     Fri 01 Nov 14:11:51 CET 2019
github.com/                                                                                          INVALID     Unknown           SYNTAX     Fri 01 Nov 14:11:51 CET 2019
t.co                                                                                                 VALID       Unknown           SYNTAX     Fri 01 Nov 14:11:51 CET 2019
POOL.moneropool.com                                                                                  INVALID     Unknown           SYNTAX     Fri 01 Nov 14:11:51 CET 2019
twitter.com                                                                                          VALID       Unknown           SYNTAX     Fri 01 Nov 14:11:51 CET 2019
golem.de                                                                                             VALID       Unknown           SYNTAX     Fri 01 Nov 14:11:51 CET 2019
github./com                                                                                          INVALID     Unknown           SYNTAX     Fri 01 Nov 14:11:51 CET 2019
github.com/.                                                                                         INVALID     Unknown           SYNTAX     Fri 01 Nov 14:11:51 CET 2019
aikapool.comwww.aikapool.com                                                                         VALID       Unknown           SYNTAX     Fri 01 Nov 14:11:51 CET 2019
194.58.122.146\032stratum.aikapool.com                                                               INVALID     Unknown           SYNTAX     Fri 01 Nov 14:11:51 CET 2019
aikapool.com.                                                                                        VALID       Unknown           SYNTAX     Fri 01 Nov 14:11:51 CET 2019

Merging cross processes data... This process might take some time.

Merging cross processes data... This process might take some time.
Traceback (most recent call last):
  File "/usr/sbin/PyFunceble", line 11, in <module>
    load_entry_point('PyFunceble==2.2.0', 'console_scripts', 'PyFunceble')()
  File "/usr/lib/python3.7/site-packages/PyFunceble/__init__.py", line 1494, in _command_line
    link_to_test=ARGS.link,
  File "/usr/lib/python3.7/site-packages/PyFunceble/dispatcher.py", line 109, in __init__
    file_path, "domain"
  File "/usr/lib/python3.7/site-packages/PyFunceble/file_multiprocess_core.py", line 439, in read_and_test_file_content
    complements = self.get_complements()
  File "/usr/lib/python3.7/site-packages/PyFunceble/file_core.py", line 410, in get_complements
    complements = self.autocontinue.get_or_generate_complements()
  File "/usr/lib/python3.7/site-packages/PyFunceble/auto_continue.py", line 711, in get_or_generate_complements
    return self.__get_or_generate_complements_json()
  File "/usr/lib/python3.7/site-packages/PyFunceble/auto_continue.py", line 567, in __get_or_generate_complements_json
    for x, y in self.get_already_tested()
  File "/usr/lib/python3.7/site-packages/PyFunceble/auto_continue.py", line 567, in <listcomp>
    for x, y in self.get_already_tested()
ValueError: too many values to unpack (expected 2)

```

**Comment by funilrys** [comment]
Hi @ZeroDot1, 

The issue with that traceback is normally addressed in the `restructuration` branch which I hope to push to the dev branch this weekend and later this month to the master branch.

If you want to test the restructuration branch uninstall PyFunceble and do a `pip install git+https://github.com/funilrys/PyFunceble.git@restructuration`

About those (the point at the end), they are valid. Please report to #17.

```
0.0.0.0 aikapool.com. # Not detected
0 bpool.id. # Not detected
10 dc-3ba5129c147c.saltpool.net. # Not detected
10 gnark-mining.com. # Not detected
10 mail.miningcoins.ca. # Not detected
5 post.blockhunter.info. # Not detected
```

About `aikapool.comwww.aikapool.com # Not detected`, I don't see what's wrong with it :thinking: It's syntactically correct to me :thinking: 

Cheers,
Nissar

**Comment by funilrys** [comment]
Note for self:

```shell
$ PyFunceble -m -f issues/50.list --syntax  --database

██████╗ ██╗   ██╗███████╗██╗   ██╗███╗   ██╗ ██████╗███████╗██████╗ ██╗     ███████╗
██╔══██╗╚██╗ ██╔╝██╔════╝██║   ██║████╗  ██║██╔════╝██╔════╝██╔══██╗██║     ██╔════╝
██████╔╝ ╚████╔╝ █████╗  ██║   ██║██╔██╗ ██║██║     █████╗  ██████╔╝██║     █████╗
██╔═══╝   ╚██╔╝  ██╔══╝  ██║   ██║██║╚██╗██║██║     ██╔══╝  ██╔══██╗██║     ██╔══╝
██║        ██║   ██║     ╚██████╔╝██║ ╚████║╚██████╗███████╗██████╔╝███████╗███████╗
╚═╝        ╚═╝   ╚═╝      ╚═════╝ ╚═╝  ╚═══╝ ╚═════╝╚══════╝╚═════╝ ╚══════╝╚══════╝

Your version is more recent!
You should really think about sharing your changes with the community!
Your version: 2.22.7.restructuration (Green Galago: Skitterbug)
Upstream version: 2.2.0. (Green Galago: Skitterbug)

The 'json' database type is not recommended with the multiprocessing mode.


Subject                                                                                              Status      Source    
---------------------------------------------------------------------------------------------------- ----------- ----------
amazon.com                                                                                           VALID       SYNTAX    
heise.de                                                                                             VALID       SYNTAX    
golem.de                                                                                             VALID       SYNTAX    
google.de                                                                                            VALID       SYNTAX    
twitter.com                                                                                          VALID       SYNTAX    
t.co                                                                                                 VALID       SYNTAX    
194.58.122.146\032stratum.aikapool.com                                                               INVALID     SYNTAX    
POOL.moneropool.com                                                                                  INVALID     SYNTAX    
VPWCHCDEVWEB001.cryptopia.co.nz                                                                      INVALID     SYNTAX    
aikapool.com.                                                                                        VALID       SYNTAX    
gitlab.com                                                                                           VALID       SYNTAX    
aikapool.comwww.aikapool.com                                                                         VALID       SYNTAX    
//github.com                                                                                         INVALID     SYNTAX    
github.com                                                                                           VALID       SYNTAX    
github.com/                                                                                          INVALID     SYNTAX    
github./com                                                                                          INVALID     SYNTAX    
github.com/.                                                                                         INVALID     SYNTAX    
http://github.com/                                                                                   INVALID     SYNTAX    
bpool.id.                                                                                            VALID       SYNTAX    
gnark-mining.com.                                                                                    VALID       SYNTAX    
dc-3ba5129c147c.saltpool.net.                                                                        VALID       SYNTAX    
mail.miningcoins.ca.                                                                                 VALID       SYNTAX    
post.blockhunter.info.                                                                               VALID       SYNTAX    

Merging cross processes data... This process may take some time.

Merging cross processes data... This process may take some time.

Merging cross processes data... This process may take some time.

Merging cross processes data... This process may take some time.


Status      Percentage   Numbers     
----------- ------------ ------------
VALID       65%          15          
INVALID     34%          8           

██████╗ ██╗   ██╗███████╗██╗   ██╗███╗   ██╗ ██████╗███████╗██████╗ ██╗     ███████╗
██╔══██╗╚██╗ ██╔╝██╔════╝██║   ██║████╗  ██║██╔════╝██╔════╝██╔══██╗██║     ██╔════╝
██████╔╝ ╚████╔╝ █████╗  ██║   ██║██╔██╗ ██║██║     █████╗  ██████╔╝██║     █████╗
██╔═══╝   ╚██╔╝  ██╔══╝  ██║   ██║██║╚██╗██║██║     ██╔══╝  ██╔══██╗██║     ██╔══╝
██║        ██║   ██║     ╚██████╔╝██║ ╚████║╚██████╗███████╗██████╔╝███████╗███████╗
╚═╝        ╚═╝   ╚═╝      ╚═════╝ ╚═╝  ╚═══╝ ╚═════╝╚══════╝╚═════╝ ╚══════╝╚══════╝


Thanks for using PyFunceble!
Share your experience on Twitter with #PyFunceble!
Have a feedback, an issue or an improvement idea ?
Let us know on GitHub!
```

**Comment by ZeroDot1** [comment]
`aikapool.comwww.aikapool.com` 
These are 2 URLS/Domains in a row.
During my research for subdomains I noticed this mistake very often.

**Comment by funilrys** [comment]
I could register the `www.google.comwww.funilrys.com` subdomain and it can be valid. It's a trick used by Phisher(s).

**Comment by dnmTX** [comment]
@funilrys  in this case @ZeroDot1  is correct and i see those errors(double in a row domains) very often in his lists and they're all invalid.I can only guess here but i think some of his scripts is messed up or something. 
I'm seconding the request here for more in dept check for invalid domains and for starters @ZeroDot1  can list here examples on what he's stumbled upon so you can start there. Me and many others are using the CoinBlockerList and we all like to have it error/invalid free as possible.
Thanks @funilrys  👍

**Comment by ZeroDot1** [comment]
Hi @funilrys,

While manually checking the CoinBlockerLists I found more URLs which are not detected.
these are URLs with an incomplete topleveldomain.

```
example.hostcontent.li
example.hostingcloud.ac
example.hostingcloud.bi
example.hostingcloud.do
example.hostingcloud.li
example.hostingcloud.pa
example.hostingcloud.re
example.hostingcloud.sc
example.hostingcloud.st
example.hostingcloud.tr
```

At the moment I'm working on deleting all the wrong URLs manually so that everything is perfect when I publish the next update on Monday.

**Comment by spirillen** [comment]
I think this one should have been closed with https://github.com/spirillen/PyFunceble/issues/19 & https://github.com/funilrys/PyFunceble/pull/176
