### ISSUE TITLE
.pyfunceble.yaml

### ISSUE THREAD

**Issue by spirillen** [funilrys/PyFunceble#60]
## Bug description
Installing the -dev version for obtaining your latest commit from ``

## Modifications under `.PyFunceble.yaml`

None, it's empty....

## Reproduction

1. `sudo -H python3 -m pip install --upgrade git+https://gitlab.com/funilrys/PyFunceble@dev`
2. `pyfunceble -m -p 4 -db --database-type mariadb -f`
4. 
```
Try to merge upstream configuration file into /home/$user/.config/PyFunceble/.PyFunceble.yaml ? [y/n] y
Traceback (most recent call last):
  File "/usr/local/bin/pyfunceble", line 8, in <module>
    sys.exit(tool())
  File "/usr/local/lib/python3.7/dist-packages/PyFunceble/cli/__init__.py", line 1041, in tool
    raise exception
  File "/usr/local/lib/python3.7/dist-packages/PyFunceble/cli/__init__.py", line 1024, in tool
    PyFunceble.cconfig.Merge(PyFunceble.CONFIG_DIRECTORY)
  File "/usr/local/lib/python3.7/dist-packages/PyFunceble/config/merge.py", line 108, in __init__
    self._load()
  File "/usr/local/lib/python3.7/dist-packages/PyFunceble/config/merge.py", line 188, in _load
    self._save()
  File "/usr/local/lib/python3.7/dist-packages/PyFunceble/config/merge.py", line 143, in _save
    PyFunceble.helpers.Dict(self.new_config).to_yaml_file(self.path_to_config)
  File "/usr/local/lib/python3.7/dist-packages/PyFunceble/helpers/dict.py", line 345, in to_yaml_file
    sort_keys=sort_keys,
  File "/usr/lib/python3/dist-packages/yaml/__init__.py", line 200, in dump
    return dump_all([data], stream, Dumper=Dumper, **kwds)
TypeError: dump_all() got an unexpected keyword argument 'sort_keys'
```

```
ll /home/$USER/.config/PyFunceble/.PyFunceble.yaml
-rw-rw-r-- 1 $USER $USER 0 Nov 17 23:03  /home/$USER/.config/PyFunceble/.PyFunceble.yaml
```

## Expected behavior**
Leaving this to your imagination :smile: 

## Screenshots
```
🌟 🎉 🍰 We now support IPv6! 🍰 🎉 🌟
A configuration key is missing.
Try to merge upstream configuration file into /home/$USER/.config/PyFunceble/.PyFunceble.yaml ? [y/n] n
Traceback (most recent call last):
  File "/usr/local/bin/pyfunceble", line 8, in <module>
    sys.exit(tool())
  File "/usr/local/lib/python3.6/dist-packages/PyFunceble/cli/__init__.py", line 1041, in tool
    raise exception
  File "/usr/local/lib/python3.6/dist-packages/PyFunceble/cli/__init__.py", line 1024, in tool
    PyFunceble.cconfig.Merge(PyFunceble.CONFIG_DIRECTORY)
  File "/usr/local/lib/python3.6/dist-packages/PyFunceble/config/merge.py", line 108, in __init__
    self._load()
  File "/usr/local/lib/python3.6/dist-packages/PyFunceble/config/merge.py", line 202, in _load
    raise PyFunceble.exceptions.ConfigurationFileNotFound()
PyFunceble.exceptions.ConfigurationFileNotFound
```
## Versions

**OS:** for example Arch Linux (5.0.5-arch1-1-ARCH)
**Python Version:** Python 2.7.16, 3.7.3, 3.7.4
**PyFunceble Version:** for example 1.2.0
```
pyfunceble -v
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/PyFunceble/cli/__init__.py", line 95, in tool
    PyFunceble.load_config(generate_directory_structure=False)
  File "/usr/local/lib/python3.7/dist-packages/PyFunceble/__init__.py", line 682, in load_config
    cconfig.Load(CONFIG_DIRECTORY, custom)
  File "/usr/local/lib/python3.7/dist-packages/PyFunceble/config/load.py", line 90, in __init__
    self.__load_it()
  File "/usr/local/lib/python3.7/dist-packages/PyFunceble/config/load.py", line 101, in __load_it
    self._load_config_file()
  File "/usr/local/lib/python3.7/dist-packages/PyFunceble/config/load.py", line 300, in _load_config_file
    self._install_iana_config()
  File "/usr/local/lib/python3.7/dist-packages/PyFunceble/config/load.py", line 409, in _install_iana_config
    iana_link = self.data["links"]["iana"]
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/pyfunceble", line 8, in <module>
    sys.exit(tool())
  File "/usr/local/lib/python3.7/dist-packages/PyFunceble/cli/__init__.py", line 1039, in tool
    PyFunceble.LOGGER.exception()
AttributeError: 'NoneType' object has no attribute 'exception'
```

**Comment by spirillen** [comment]
forget it.... I have forgotten to uninstall previous version.... buthead ^
