### ISSUE TITLE
pyfunceble --help is not working

### ISSUE THREAD

**Issue by ZeroDot1** [funilrys/PyFunceble#73]
## Bug description
pyfunceble --help is not working. 

`pyfunceble --help`

## Reproduction

1. yay -S pyfunceble-dev
2. pyfunceble --help

## Versions

**OS:** Arch Linux (5.4.8-arch1-1)
**Python Version:**  3.8
**PyFunceble Version:** 2.49.5-1

## Additional context
```bash
$ pyfunceble --help
Traceback (most recent call last):
  File "/usr/sbin/pyfunceble", line 11, in <module>
    load_entry_point('PyFunceble-dev==2.49.5', 'console_scripts', 'pyfunceble')()
  File "/usr/lib/python3.8/site-packages/PyFunceble/cli/__init__.py", line 1084, in tool
    raise exception
  File "/usr/lib/python3.8/site-packages/PyFunceble/cli/__init__.py", line 95, in tool
    PyFunceble.load_config(generate_directory_structure=False)
  File "/usr/lib/python3.8/site-packages/PyFunceble/__init__.py", line 682, in load_config
    cconfig.Load(CONFIG_DIRECTORY, custom)
  File "/usr/lib/python3.8/site-packages/PyFunceble/config/load.py", line 90, in __init__
    self.__load_it()
  File "/usr/lib/python3.8/site-packages/PyFunceble/config/load.py", line 101, in __load_it
    self._load_config_file()
  File "/usr/lib/python3.8/site-packages/PyFunceble/config/load.py", line 294, in _load_config_file
    self._install_iana_config()
  File "/usr/lib/python3.8/site-packages/PyFunceble/config/load.py", line 418, in _install_iana_config
    return PyFunceble.helpers.Download(iana_link).text(destination=destination)
  File "/usr/lib/python3.8/site-packages/PyFunceble/helpers/download.py", line 115, in text
    raise Exception(
Exception: Unable to download https://raw.githubusercontent.com/funilrys/PyFunceble/dev/iana-domains-db.json (status code: 404).

```

**Comment by funilrys** [comment]
Please update to the (just uploaded) new version in AUR.

Cheers!

P.S.: Happy New Year 2020!

**Comment by ZeroDot1** [comment]
Thanks,The help function is working again. 
Upgrade done, I will do a full test tomorrow with a list of URLs.
Thanks for the update, keep up the good work.
