### ISSUE TITLE
Bug: pkg_resources.DistributionNotFound:

### ISSUE THREAD

**Issue by ZeroDot1** [funilrys/PyFunceble#82]
## Bug description
Since the last update of pyfunceble nothing works anymore.
only error messages are displayed.

## Modifications under `.PyFunceble.yaml`
Nothing

## Reproduction
yay -S pyfunceble-dev
pyfunceble -m -a -f 'All.txt'

## Screenshots
```bash
Traceback (most recent call last):
  File "/usr/sbin/pyfunceble", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3254, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3237, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3266, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 584, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 901, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 787, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'toml' distribution was not found and is required by python-box
```

## Versions

**OS:** for example Arch Linux (5.0.5-arch1-1-ARCH)
**Python Version:** for example 3
**PyFunceble Version:** for example 3.0.0

**Comment by ZeroDot1** [comment]
@funilrys Please list all packages that are required for Arch Linux.

Such problems are not good.
