### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: output/XYZ/ZYX

### ISSUE THREAD

**Issue by ZeroDot1** [funilrys/PyFunceble#89]
## Bug description
```bash
Subject                                                                                              Status      Expiration Date   Source     HTTP Code 
---------------------------------------------------------------------------------------------------- ----------- ----------------- ---------- ----------
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/PyFunceble/output/prints.py", line 257, in before_header
    self.file_output_instance.write(link + date_of_generation + header)
UnboundLocalError: local variable 'header' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/PyFunceble/core/multiprocess.py", line 99, in run
    Process.run(self)
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.8/site-packages/PyFunceble/core/multiprocess.py", line 199, in test
    result = APICore(
  File "/usr/lib/python3.8/site-packages/PyFunceble/core/api.py", line 224, in availability
    return self.domain_and_ip()
  File "/usr/lib/python3.8/site-packages/PyFunceble/core/api.py", line 297, in domain_and_ip
    data = PyFunceble.status.DomainAndIpAvailability(
  File "/usr/lib/python3.8/site-packages/PyFunceble/status/availability/domain_and_ip.py", line 81, in __init__
    self.__gather()
  File "/usr/lib/python3.8/site-packages/PyFunceble/status/availability/domain_and_ip.py", line 208, in __gather
    PyFunceble.output.Generate(
  File "/usr/lib/python3.8/site-packages/PyFunceble/output/generate.py", line 959, in status_file
    self.info_files()
  File "/usr/lib/python3.8/site-packages/PyFunceble/output/generate.py", line 481, in info_files
    PyFunceble.output.Prints(
  File "/usr/lib/python3.8/site-packages/PyFunceble/output/prints.py", line 725, in data
    self.before_header()
  File "/usr/lib/python3.8/site-packages/PyFunceble/output/prints.py", line 262, in before_header
    self.file_output_instance.write(link + date_of_generation)
  File "/usr/lib/python3.8/site-packages/PyFunceble/helpers/file.py", line 159, in write
    with open(file_path, "w", encoding=encoding) as file_stream:
FileNotFoundError: [Errno 2] No such file or directory: '/home/user/output/hosts/INACTIVE/hosts'
Merging cross processes data... This process may take some time.
```

## Modifications under `.PyFunceble.yaml`

nothing changed.

## Reproduction

1.  pyfunceble -m -a -f "/All.txt"

## Versions

**OS:** for example Arch Linux 
**Python Version:**  3.8
**PyFunceble Version:** 3.1.0.dev (Teal Blauwbok: Ladybug)

**Comment by funilrys** [comment]
Bug fixed by https://github.com/funilrys/PyFunceble/commit/23d749a9b6bc64e2ca3a69915e3bcf2dfcbc56fc.

**P.S: Help us, DO NOT close this issue manually. This issue is going to be closed automatically once https://github.com/funilrys/PyFunceble/commit/23d749a9b6bc64e2ca3a69915e3bcf2dfcbc56fc will be merged to master.**

**Comment by ZeroDot1** [comment]
Hi @funilrys, It works now, thank you for the quick bug fixing.
